### ISSUE TITLE
Helloworld使用Mosdns做解析，如果设置强制代理的话，应该哪里设置呢

### ISSUE THREAD

**Issue by helllkz** [sbwml/luci-app-mosdns#100]
SSR设置了使用本地5335的Mosdns做DNS，如果要把一个域名比如A设置到强制代理，如果在SSR里面设置成强制代理，但是MosDNS里面又没配置，会有什么效果呢？

**Comment by ichenhe** [comment]
代理环境下的 DNS 行为非常复杂，**你应该去弄清代理软件的 DNS 逻辑**，Mosdns 只有在代理软件请求自己的时候其规则才会生效。

假定你使用的是最传统的 SSR，把域名设置为强制代理后，应该是把 DNS 请求通过 ssr 发送到节点，由节点负责执行 DNS 查询。此时与 Mosdns 完全无关。当然，非说有关的话，如果 ssr 节点地址是域名，那么 SSR 会用系统默认 DNS 查询这个域名，如果你把系统 DNS 重定向到 5335 了，那么就由 Mosdns 负责。

如果开启了 redir / tun 会更加复杂。
