### ISSUE TITLE
启动后有点问题

### ISSUE THREAD

**Issue by cjlhll** [sbwml/luci-app-mosdns#103]
1、只显示国内的日志，国外的passwall2的日志没有显示正常吗？
2、日志时间和系统时间对不上，好像是日志的时区和系统不一致
3、每条国内的日志都是warn状态
![QQ截图20230713204953](https://github.com/sbwml/luci-app-mosdns/assets/26736892/0650e3cf-23fc-4c83-b69d-f62ad5996548)
![QQ截图20230713204932](https://github.com/sbwml/luci-app-mosdns/assets/26736892/19c41f1a-b3fe-458c-9470-3641597f738c)

求帮忙解答。~

**Comment by sbwml** [comment]
1、没有日志属于正常，如果你要看到每一条日志，那么你应该打开 “调试” 日志级别
2、你的固件缺少亚洲时区信息。https://openwrt.org/packages/pkgdata/zoneinfo-asia
3、如果国内每一条都出现警告，并且不能正常解析上网，那它不正常，应该更改本地DNS。如果你能正常上网，但是依然看到很多警告日志，那么你可以设置“错误”日志级别来屏蔽它，因为它是一个常态。https://github.com/IrineSistiana/mosdns/issues/98

**Comment by cjlhll** [comment]
> 1、没有日志属于正常，如果你要看到每一条日志，那么你应该打开 “调试” 日志级别 2、你的固件缺少亚洲时区信息。https://openwrt.org/packages/pkgdata/zoneinfo-asia 3、如果国内每一条都出现警告，并且不能正常解析上网，那它不正常，应该更改本地DNS。如果你能正常上网，但是依然看到很多警告日志，那么你可以设置“错误”日志级别来屏蔽它，因为它是一个常态。[IrineSistiana/mosdns#98](https://github.com/IrineSistiana/mosdns/issues/98)

好的。第三条只要是正常上网，就可以直接无视是吧？时区这个不影响功能和稳定性吧。

**Comment by sbwml** [comment]
只要不影响上网，`context deadline exceeded` 可以无视，但是建议添加两个DNS 以上

至于时区，如果你是强迫症，那你就给固件装个亚洲时区信息包，重启mosdns 后日志时间就是你本地时区。如果不是强迫症，这玩意显示哪里的时区都毫无意义，只要系统时间是准的，都不影响mosdns 工作

**Comment by cjlhll** [comment]
> 只要不影响上网，`context deadline exceeded` 可以无视，但是建议添加两个DNS 以上
> 
> 至于时区，如果你是强迫症，那你就给固件装个亚洲时区信息包，重启mosdns 后日志时间就是你本地时区。如果不是强迫症，这玩意显示哪里的时区都毫无意义，只要系统时间是准的，都不影响mosdns 工作

好的。明白了。感谢~
