### ISSUE TITLE
V5版本试用建议

### ISSUE THREAD

**Issue by lengfwong** [sbwml/luci-app-mosdns#104]
sbwml，您好
之前你提到过OP应该要稳定，不应追新，所以一直用的V4版本+ipset+V2ray的组合。今日有空，配置了下V5，还没觉得有什么好处，建议能否给自定义配置提供去广告域名功能，现在的luci在自定义配置下，/var/mosdns文件夹不生成“geosite_category-ads-all.txt”，我在/usr/share/mosdns/mosdns.sh脚本中加了一个命令，暂时解决了，如果能在luci上定义就方便了。

另，v2dat_dump解密这几个文件是配置的定时吗？还是在geodata update时同步更新解密这几个文件，或者是每次重启MOSDNS才更新？

谢谢。

**Comment by sbwml** [comment]
v5 的 luci 在自定义配置下默认就会导出 geosite_category-ads-all.txt 文件的。除了默认的会导出，还添加了自定义导出的类别设置
![image](https://github.com/sbwml/luci-app-mosdns/assets/16485166/1cee3660-ad01-4bfe-ae28-186d956b04b5)

**Comment by lengfwong** [comment]
> 
v2dat_dump() {
    # env
    v2dat_dir=/usr/share/v2ray
    adblock=$(uci -q get mosdns.config.adblock)
    ad_source=$(uci -q get mosdns.config.ad_source)
    configfile=$(uci -q get mosdns.config.configfile)
    mkdir -p /var/mosdns
    rm -f /var/mosdns/geo*.txt
    if [ "$configfile" = "/etc/mosdns/config.yaml" ]; then
        # default config
        v2dat unpack geoip -o /var/mosdns -f cn $v2dat_dir/geoip.dat
        v2dat unpack geosite -o /var/mosdns -f cn -f 'geolocation-!cn' $v2dat_dir/geosite.dat
        [ "$adblock" -eq 1 ] && [ "$ad_source" = "geosite.dat" ] && v2dat unpack geosite -o /var/mosdns -f category-ads-all $v2dat_dir/geosite.dat
    else
        # custom config
        v2dat unpack geoip -o /var/mosdns -f cn $v2dat_dir/geoip.dat
        v2dat unpack geosite -o /var/mosdns -f cn -f 'geolocation-!cn' $v2dat_dir/geosite.dat
        geoip_tags=$(uci -q get mosdns.config.geoip_tags)
        geosite_tags=$(uci -q get mosdns.config.geosite_tags)
        [ -n "$geoip_tags" ] && v2dat unpack geoip -o /var/mosdns $(echo $geoip_tags | sed -r 's/\S+/-f &/g') $v2dat_dir/geoip.dat
        [ -n "$geosite_tags" ] && v2dat unpack geosite -o /var/mosdns $(echo $geosite_tags | sed -r 's/\S+/-f &/g') $v2dat_dir/geosite.dat
       fi
}
默认情况下，custom config部分/var/mosdns文件夹不生成 geosite_category-ads-all.txt 文件

**Comment by sbwml** [comment]
那就是我记错了。你可以自己添加 `category-ads-all` 到 geosite 标签上。mosdns 启动时会导出自定义标签

**Comment by lengfwong** [comment]
标签怎么加？也是修改这个文件吗？我是把default config 里那行命令复制下来了。:-)

**Comment by sbwml** [comment]
> v5 的 luci 在自定义配置下默认就会导出 geosite_category-ads-all.txt 文件的。除了默认的会导出，还添加了自定义导出的类别设置 ![image](https://user-images.githubusercontent.com/16485166/253736105-1cee3660-ad01-4bfe-ae28-186d956b04b5.png)

👆

**Comment by lengfwong** [comment]
谢谢，明白了
