### ISSUE TITLE
op6.1内核安装不了，op用5.15 的可以正常安装

### ISSUE THREAD

**Issue by sunshineyxc** [sbwml/luci-app-mosdns#108]
6.1内核安装提示有4个kmod的依赖不村子

**Comment by sbwml** [comment]
mosdns 不依赖内核模块、内核版本

**Comment by gavinup** [comment]
我也遇到同样的问题
![image](https://github.com/sbwml/luci-app-mosdns/assets/30076575/f064344e-7b66-4bf6-b81b-ccb88993a801)

**Comment by sbwml** [comment]
我不知道如何解释这种情况。图片显示的错误并不是mosdns 引起，而是你使用的固件不是openwrt 官方固件，虽然它显示了kmod 的依赖错误。但是实际上 mosdns 已经安装成功了。

成功的信息
![image](https://github.com/sbwml/luci-app-mosdns/assets/16485166/6c90a115-a8a2-45c1-b090-16de3ad40fb9)


至于你们这些内核依赖的错误，我只能给的建议是更新官方openwrt 固件，或者使用第三方 hack vermagic 构建的固件才能解决这种情况。因为正常情况下通过第三方编译的openwrt 固件是无法安装任何一个 kmod 包的。即使你不是安装的mosdns，而是安装的其它插件，这个错误一样会出现，因为你固件本身就没有解决这种问题。

不知道你们能不能理解我说意思

**Comment by gavinup** [comment]
确实已经安装成功了，就是启动不上，一直循环下面的错
![image](https://github.com/sbwml/luci-app-mosdns/assets/30076575/542ddea9-6670-40f3-a4bd-954741fdf367)

**Comment by sbwml** [comment]
#73 你需要参考这里，并提供一些相关信息

**Comment by gavinup** [comment]
![image](https://github.com/sbwml/luci-app-mosdns/assets/30076575/8bf3e078-befd-413a-a727-e10235339e8b)
是端口问题，改了能启动了，我测试一下功能，谢了
