### ISSUE TITLE
v4版本使用一键安装脚本出错，麻烦大佬帮忙看一下，谢谢

### ISSUE THREAD

**Issue by hww-png** [sbwml/luci-app-mosdns#111]
![image](https://github.com/sbwml/luci-app-mosdns/assets/77440291/cb659f3b-01b3-4747-8cf3-ed55e30abf98)

curl和libcurl版本一致。

**Comment by sbwml** [comment]
![image](https://github.com/sbwml/luci-app-mosdns/assets/16485166/b1f0a2e0-b232-498e-8735-2ef5bff46ff1)

我在虚拟机的op测试了一下   没啥问题啊。脚本装不上的话，你可以直接下载ipk文件下来装

**Comment by hww-png** [comment]
该问题可以关了，是我这边的问题，路由器没有使用梯子导致的。
