### ISSUE TITLE
日志显示缓存错误

### ISSUE THREAD

**Issue by asnon** [sbwml/luci-app-mosdns#112]
2023-08-09T05:22:28.869Z	ERROR	lazy_cache	dump cache	{"error": "failed to write dump, failed to marshal protobuf, string field contains invalid UTF-8"}
不知道是什么情况，最新版本了

**Comment by sbwml** [comment]
文件损坏了吧    关闭缓存导出功能    再重新开启    应该会重建一个空白的缓存文件

**Comment by sbwml** [comment]
但愿不是你存储出问题，比如一些什么arm机器  然后又是sd卡   又是ext4文件系统的 ，如果是这种就彻底炸了

**Comment by asnon** [comment]
> 但愿不是你存储出问题，比如一些什么arm机器 然后又是sd卡 又是ext4文件系统的 ，如果是这种就彻底炸了

哦哦 我都是用虚拟机的旁路由，最近两个版本的固件都是会这样子，然后我是下载了官方最新版本的呢

**Comment by asnon** [comment]
> 文件损坏了吧 关闭缓存导出功能 再重新开启 应该会重建一个空白的缓存文件

关闭了重建还是出现类似的bug哦，换了好几个固件都是呢

**Comment by sbwml** [comment]
这我就不清楚了，你可以带你的日志找 mosdns 项目作者问问。

**Comment by sbwml** [comment]
上游已经修复
