### ISSUE TITLE
openclash使用fakeip模式，应该如何设置使用mosdns来解析？

### ISSUE THREAD

**Issue by tsgo606** [sbwml/luci-app-mosdns#113]

**Comment by sbwml** [comment]
不知道，没摸过openclsh

从 Windows 版邮件发送

发件人: tsgo606
发送时间: 2023年8月18日 11:40
收件人: sbwml/luci-app-mosdns
抄送: Subscribed
主题: [sbwml/luci-app-mosdns] openclash使用fakeip模式，应该如何设置使用mosdns来解析？ (Issue #113)

**Comment by Aethersailor** [comment]
1、openclash前置：oc的nameserver和fallback分别设置指向mosdns（127.0.0.1:5335），mosdns两组服务器分别设置国内DNS和国外DNS并在设置中勾选防DNS泄漏

2、mosdns前置：mosdns国内服务器组正常设置，远程服务器组设置为oc的dns服务端口（127.0.0.1:7874）。oc的nameserver设置为mosdns地址（127.0.0.1:5335），oc的fallback设置为国外DOT/DOH服务器。mosdns中勾选防DNS泄漏

以上是两种确保dns无泄漏的设置方式

如果你不介意dns泄漏问题，那么在方案2中，mosdns不要勾选防dns泄漏，oc的nameserver设置为国内dns地址，fallback组留空不要设置，理论上这是速度最快效果最好的方式，唯一缺点就是存在泄漏问题

**Comment by cqjerry** [comment]
楼上这位兄台，UP主的https://www.youtube.com/watch?v=BWvJf5KLaWc  这段视频教程里，好像和你所说的2种前置设置方式都不一样。不知道你们谁的方式更正确呢？能否再讨论下。

**Comment by eightsheep67** [comment]
> 楼上这位兄台，UP主的https://www.youtube.com/watch?v=BWvJf5KLaWc 这段视频教程里，好像和你所说的2种前置设置方式都不一样。不知道你们谁的方式更正确呢？能否再讨论下。

我看了你油管这个，他这个方式就是mosdns作为唯一的dns服务器，openclash完全不解析只代理，有一个问题就是评论里讲的openclash根据域名的分流就失效了，然后都走的other，当然你如果本来没有细致的分流的话，那无所谓。

楼上这个modns前置，他就还是把mosdns认为非国内的域名扔给openclash来解析，这样openclash分流还起作用，但是跟油管主说的就是不确定openclash哪个环节还是会产生dns泄露。。。。

没有DNS防泄漏的要求的话，我觉得用楼上的设置就行了吧

**Comment by cqjerry** [comment]
”有一个问题就是评论里讲的openclash根据域名的分流就失效了，然后都走的other“。我现在是按照油管的方式设置的，实际用下来并不会出现你说的分流失效的问题，我的clash配置里有十几个ruleset规则，看log都是分流正常的。并且，按照油管里给的那2个测试泄露的网站跑了下，也并未发现有DNS泄露。

**Comment by avalanceonerd** [comment]
> > 楼上这位兄台，UP主的https://www.youtube.com/watch?v=BWvJf5KLaWc 这段视频教程里，好像和你所说的2种前置设置方式都不一样。不知道你们谁的方式更正确呢？能否再讨论下。
> 
> 我看了你油管这个，他这个方式就是mosdns作为唯一的dns服务器，openclash完全不解析只代理，有一个问题就是评论里讲的openclash根据域名的分流就失效了，然后都走的other，当然你如果本来没有细致的分流的话，那无所谓。
> 
> 楼上这个modns前置，他就还是把mosdns认为非国内的域名扔给openclash来解析，这样openclash分流还起作用，但是跟油管主说的就是不确定openclash哪个环节还是会产生dns泄露。。。。
> 
> 没有DNS防泄漏的要求的话，我觉得用楼上的设置就行了吧

clash的工作原理是规则优先 没有命中才去触发dns解析 所以oc我理解必须前置 劫持dnsmaq 把nameserver和fallback全部转发到mosdns mos那边勾上防泄露 我试了下规则可以命中 同时没有泄露问题 这应该是唯一解了

**Comment by Aethersailor** [comment]
> > 楼上这位兄台，UP主的https://www.youtube.com/watch?v=BWvJf5KLaWc 这段视频教程里，好像和你所说的2种前置设置方式都不一样。不知道你们谁的方式更正确呢？能否再讨论下。
> 
> 
> 
> 我看了你油管这个，他这个方式就是mosdns作为唯一的dns服务器，openclash完全不解析只代理，有一个问题就是评论里讲的openclash根据域名的分流就失效了，然后都走的other，当然你如果本来没有细致的分流的话，那无所谓。
> 
> 
> 
> 楼上这个modns前置，他就还是把mosdns认为非国内的域名扔给openclash来解析，这样openclash分流还起作用，但是跟油管主说的就是不确定openclash哪个环节还是会产生dns泄露。。。。
> 
> 
> 
> 没有DNS防泄漏的要求的话，我觉得用楼上的设置就行了吧

不会呀，我提供的两种方案，中间没有任何一个环节产生泄漏。
DNS泄漏的主要原因就是openclash的判断机制将域名交由nameserver进行解析，这两种方案都将原本交给nameserver的解析转发给了mosdns，而mosdns又将非cn的域名全给了fallback，所以理论上不会有任何泄漏，实际也是如此呀

**Comment by gwd0715** [comment]
> 1、openclash前置：oc的nameserver和fallback分别设置指向mosdns（127.0.0.1:5335），mosdns两组服务器分别设置国内DNS和国外DNS并在设置中勾选防DNS泄漏
> 
> 2、mosdns前置：mosdns国内服务器组正常设置，远程服务器组设置为oc的dns服务端口（127.0.0.1:7874）。oc的nameserver设置为mosdns地址（127.0.0.1:5335），oc的fallback设置为国外DOT/DOH服务器。mosdns中勾选防DNS泄漏
> 
> 以上是两种确保dns无泄漏的设置方式
> 
> 如果你不介意dns泄漏问题，那么在方案2中，mosdns不要勾选防dns泄漏，oc的nameserver设置为国内dns地址，fallback组留空不要设置，理论上这是速度最快效果最好的方式，唯一缺点就是存在泄漏问题

请问这两种配置，oc里面的dns劫持还需要打开吗？如果需要打开，还是选择dnsmasq进行转发吗？

**Comment by Aethersailor** [comment]
> > 1、openclash前置：oc的nameserver和fallback分别设置指向mosdns（127.0.0.1:5335），mosdns两组服务器分别设置国内DNS和国外DNS并在设置中勾选防DNS泄漏
> 
> > 
> 
> > 2、mosdns前置：mosdns国内服务器组正常设置，远程服务器组设置为oc的dns服务端口（127.0.0.1:7874）。oc的nameserver设置为mosdns地址（127.0.0.1:5335），oc的fallback设置为国外DOT/DOH服务器。mosdns中勾选防DNS泄漏
> 
> > 
> 
> > 以上是两种确保dns无泄漏的设置方式
> 
> > 
> 
> > 如果你不介意dns泄漏问题，那么在方案2中，mosdns不要勾选防dns泄漏，oc的nameserver设置为国内dns地址，fallback组留空不要设置，理论上这是速度最快效果最好的方式，唯一缺点就是存在泄漏问题
> 
> 
> 
> 请问这两种配置，oc里面的dns劫持还需要打开吗？如果需要打开，还是选择dnsmasq进行转发吗？

不要打开

**Comment by tsgo606** [comment]
> 1、openclash前置：oc的nameserver和fallback分别设置指向mosdns（127.0.0.1:5335），mosdns两组服务器分别设置国内DNS和国外DNS并在设置中勾选防DNS泄漏
> 
> 2、mosdns前置：mosdns国内服务器组正常设置，远程服务器组设置为oc的dns服务端口（127.0.0.1:7874）。oc的nameserver设置为mosdns地址（127.0.0.1:5335），oc的fallback设置为国外DOT/DOH服务器。mosdns中勾选防DNS泄漏
> 
> 以上是两种确保dns无泄漏的设置方式
> 
> 如果你不介意dns泄漏问题，那么在方案2中，mosdns不要勾选防dns泄漏，oc的nameserver设置为国内dns地址，fallback组留空不要设置，理论上这是速度最快效果最好的方式，唯一缺点就是存在泄漏问题

想知道如果是oc前置的话，还需要劫持dnsmasq吗？如果dnsmasq直接转发到mosdns，OC不劫持dnsmasq，在OC的自定义DNS里面还需要再指向Mosdns吗？ 如果不劫持是不是OC就已经不需要做任何DNS解析了，直接代理。 但是这样好像fake-ip就不起作用了。

**Comment by bluef1ash** [comment]
> 1、openclash前置：oc的nameserver和fallback分别设置指向mosdns（127.0.0.1:5335），mosdns两组服务器分别设置国内DNS和国外DNS并在设置中勾选防DNS泄漏
> 
> 2、mosdns前置：mosdns国内服务器组正常设置，远程服务器组设置为oc的dns服务端口（127.0.0.1:7874）。oc的nameserver设置为mosdns地址（127.0.0.1:5335），oc的fallback设置为国外DOT/DOH服务器。mosdns中勾选防DNS泄漏
> 
> 以上是两种确保dns无泄漏的设置方式
> 
> 如果你不介意dns泄漏问题，那么在方案2中，mosdns不要勾选防dns泄漏，oc的nameserver设置为国内dns地址，fallback组留空不要设置，理论上这是速度最快效果最好的方式，唯一缺点就是存在泄漏问题

这样设置有些网站会打不开

**Comment by AoThen** [comment]
> 1、openclash前置：oc的nameserver和fallback分别设置指向mosdns（127.0.0.1:5335），mosdns两组服务器分别设置国内DNS和国外DNS并在设置中勾选防DNS泄漏
> 
> 2、mosdns前置：mosdns国内服务器组正常设置，远程服务器组设置为oc的dns服务端口（127.0.0.1:7874）。oc的nameserver设置为mosdns地址（127.0.0.1:5335），oc的fallback设置为国外DOT/DOH服务器。mosdns中勾选防DNS泄漏
> 
> 以上是两种确保dns无泄漏的设置方式
> 
> 如果你不介意dns泄漏问题，那么在方案2中，mosdns不要勾选防dns泄漏，oc的nameserver设置为国内dns地址，fallback组留空不要设置，理论上这是速度最快效果最好的方式，唯一缺点就是存在泄漏问题

为啥1中不这样设置呢，fallback组直接留空，mosdns不是有防污染么

**Comment by NubiaYin** [comment]
> > > 1、openclash前置：oc的nameserver和fallback分别设置指向mosdns（127.0.0.1:5335），mosdns两组服务器分别设置国内DNS和国外DNS并在设置中勾选防DNS泄漏
> > 
> > 
> > > 
> > 
> > 
> > > 2、mosdns前置：mosdns国内服务器组正常设置，远程服务器组设置为oc的dns服务端口（127.0.0.1:7874）。oc的nameserver设置为mosdns地址（127.0.0.1:5335），oc的fallback设置为国外DOT/DOH服务器。mosdns中勾选防DNS泄漏
> > 
> > 
> > > 
> > 
> > 
> > > 以上是两种确保dns无泄漏的设置方式
> > 
> > 
> > > 
> > 
> > 
> > > 如果你不介意dns泄漏问题，那么在方案2中，mosdns不要勾选防dns泄漏，oc的nameserver设置为国内dns地址，fallback组留空不要设置，理论上这是速度最快效果最好的方式，唯一缺点就是存在泄漏问题
> > 
> > 
> > 请问这两种配置，oc里面的dns劫持还需要打开吗？如果需要打开，还是选择dnsmasq进行转发吗？
> 
> 不要打开

大佬您好，请教一下:
我是在旁路由部署 mosdns+openclash 的，用的楼上的方案 2。内网的机器网关和 dns 填的都是旁路由的 ip。结果是，在 OC 中如果不开 dns 劫持，外网打不开，开了就正常，请问这是怎么回事呢。打开劫持了能看到有国内的流量过了核心。

**Comment by Aethersailor** [comment]
> > > > 1、openclash前置：oc的nameserver和fallback分别设置指向mosdns（127.0.0.1:5335），mosdns两组服务器分别设置国内DNS和国外DNS并在设置中勾选防DNS泄漏
> 
> > > 
> 
> > > 
> 
> > > > 
> 
> > > 
> 
> > > 
> 
> > > > 2、mosdns前置：mosdns国内服务器组正常设置，远程服务器组设置为oc的dns服务端口（127.0.0.1:7874）。oc的nameserver设置为mosdns地址（127.0.0.1:5335），oc的fallback设置为国外DOT/DOH服务器。mosdns中勾选防DNS泄漏
> 
> > > 
> 
> > > 
> 
> > > > 
> 
> > > 
> 
> > > 
> 
> > > > 以上是两种确保dns无泄漏的设置方式
> 
> > > 
> 
> > > 
> 
> > > > 
> 
> > > 
> 
> > > 
> 
> > > > 如果你不介意dns泄漏问题，那么在方案2中，mosdns不要勾选防dns泄漏，oc的nameserver设置为国内dns地址，fallback组留空不要设置，理论上这是速度最快效果最好的方式，唯一缺点就是存在泄漏问题
> 
> > > 
> 
> > > 
> 
> > > 请问这两种配置，oc里面的dns劫持还需要打开吗？如果需要打开，还是选择dnsmasq进行转发吗？
> 
> > 
> 
> > 不要打开
> 
> 
> 
> 大佬您好，请教一下:
> 
> 我是在旁路由部署 mosdns+openclash 的，用的楼上的方案 2。内网的机器网关和 dns 填的都是旁路由的 ip。结果是，在 OC 中如果不开 dns 劫持，外网打不开，开了就正常，请问这是怎么回事呢。打开劫持了能看到有国内的流量过了核心。

无法回答，设置肯定有问题，自行检查一下

**Comment by youfly** [comment]
> 1、openclash前置：oc的nameserver和fallback分别设置指向mosdns（127.0.0.1:5335），mosdns两组服务器分别设置国内DNS和国外DNS并在设置中勾选防DNS泄漏
> 
> 2、mosdns前置：mosdns国内服务器组正常设置，远程服务器组设置为oc的dns服务端口（127.0.0.1:7874）。oc的nameserver设置为mosdns地址（127.0.0.1:5335），oc的fallback设置为国外DOT/DOH服务器。mosdns中勾选防DNS泄漏
> 
> 以上是两种确保dns无泄漏的设置方式
> 
> 如果你不介意dns泄漏问题，那么在方案2中，mosdns不要勾选防dns泄漏，oc的nameserver设置为国内dns地址，fallback组留空不要设置，理论上这是速度最快效果最好的方式，唯一缺点就是存在泄漏问题

我就直接不用openclash的dns，openclash设置国内外分流，国外ip走代理，fake-ip模式，用起来也很和谐。也避免fakeip污染缓存。

**Comment by QTFIUE** [comment]
但是避免不了webrtc泄漏
