### ISSUE TITLE
【CI-feature request】使用UPX压缩编译生成的二进制产物

### ISSUE THREAD

**Issue by Basstorm** [sbwml/luci-app-mosdns#115]
**场景：**
在小闪存机器上，对二进制可执行文件的体积较敏感，如我用的360 v6，装了openclash，mosdns后，可用空间只剩下5m左右。

**使用upx压缩的效果：**
Release页面中的ipk包，均是未压缩的原始产物，mosdns二进制大小高达16.1m，在使用upx 4.1压缩后，体积可缩小至5.8m，v2dat的二进制可由6.8m缩小至2.6m，效果显著。

**Comment by sbwml** [comment]
这需要你自己去弄了。upx 压缩对小空间的设备确实是一种方法，但是它也会带来一些性能的问题。openwrt 在四五年前曾经也有支持upx 压缩，后来被移除了。

**Comment by Basstorm** [comment]
那是否每个架构可以提供两个版本，一个是原始产物，一个是upx压缩后的？我理解性能问题是出现在代码解压阶段，跑起来之后性能应与原始产物没什么区别。

**Comment by sbwml** [comment]
提供不了，ci 构建使用的 openwrt 官方 sdk，openwrt feeds 已经不存在 upx。你只能是自己在本地编译并使用lede 或者 host 的upx 去呀。这也是一劳永逸，因为mosdns 上游已经停止维护。
