### ISSUE TITLE
forward_remote	upstream error	{"uqid": 121, "qname": "www.google.com.", "qtype": 1, "qclass": 1, "upstream": "tls://208.67.222.222", "error": "context deadline exceeded"}

### ISSUE THREAD

**Issue by maryjeck** [sbwml/luci-app-mosdns#116]
最近一直都是这类提示，

中国电信的网络，R2S

**Comment by sbwml** [comment]
https://github.com/IrineSistiana/mosdns/issues/98

“_解决方法_”：~设置日志等级 -> 错误~

看不见=心理过得去，因为这个⚠警告消息你做不了任何事情，也不影响你任何事情

**Comment by maryjeck** [comment]
这。。。主要是不能科学上网了，

**Comment by sbwml** [comment]
能不能使用国外的dns 这取决于你的科学节点，mosdns 做不了任何事情。如果你是因为科学节点连接的域名是境外域名，mosdns 无法使用远程dns解析，你可以把它添加到白名单上让其通过国内dns 去解析。

**Comment by maryjeck** [comment]
从日志看来，是mosdns使用tls://208.67.222.222查询dns 超时失败，和节点有什么关系？

**Comment by sbwml** [comment]
因为只要你在国内，境外的所有DNS 都需要被节点代理才能正常使用。如果你有留意过任何的科学插件，你会发现境外DNS IP 会处于强制代理列表中。

**Comment by sbwml** [comment]
如果你是所有国外站点的域名都无法打开了。你只能检查你的科学节点是不是有什么问题。如果你能打开，而只是看到mosdns 的一些查询超时，那么你完全可以忽略它，就算是我自己自建的 dns ，我也无法避免这种情况发生
![image](https://github.com/sbwml/luci-app-mosdns/assets/16485166/b6d12b81-bbac-4d3a-9c5e-b533464a0783)

**Comment by maryjeck** [comment]
我依据您的解释，我回头查了一下passwall的设置，科学节点，添加到白名单中了，而且用nslookup也能查询。curl也能正确的识别节点的网站，
