### ISSUE TITLE
升级到最新版本5.1.3-6，DNS泄露了

### ISSUE THREAD

**Issue by xunmoo** [sbwml/luci-app-mosdns#117]
原来用的是5.1.3-4，设置mosdns前置：mosdns国内服务器组正常设置，远程服务器组设置为oc的dns服务端口（127.0.0.1:7874）。oc的nameserver设置为mosdns地址（127.0.0.1:5335），oc的fallback设置为国外DOT/DOH服务器。mosdns中勾选防DNS泄漏，检查可以阻止DNS泄露，早上看到有新版本的，更新到5.1.3-6，没有防DNS泄漏选项了，其他设置保持和5.1.3-4时的设置一样，检查发现DNS泄露了，这个最新版本的搭配OPENCLASH要如何设置啊？

**Comment by sbwml** [comment]
**防止 DNS 泄漏** 的 LuCI 选项是存在的，从来没被删除过（如果不显示了，可以清除 LuCI 缓存后，重启rpcd 进程。或者直接重启路由器）

另外我想说，所谓的 **DNS 泄漏** 没必要太在意它，它只是一些销售隧道网络的商家一种营销说法罢了

至于openclash ，我个人从来没接触过，这个不好说

**Comment by xunmoo** [comment]
![206000249-3fdc64ea-cb4d-47f6-8247-c029f54e405e](https://github.com/sbwml/luci-app-mosdns/assets/23499618/c0383091-1842-4c09-941f-1ee6fc1d6f81)
LUCI界面跟你发布的这个是一样的，确实没找着防DNS泄漏选项来着

**Comment by sbwml** [comment]
因为你根本就没装对luci 版本
