### ISSUE TITLE
重启路由器会失效

### ISSUE THREAD

**Issue by izhima** [sbwml/luci-app-mosdns#119]
重启路由器后。mosdns无法访问外网，要手动关闭再打开才正常，建议加个延时启动。

**Comment by sbwml** [comment]
外网是哪个外网   谷歌那种？

**Comment by izhima** [comment]
是的，无法访问国外的网站，国内的可以，估计是启动顺序问题，我这边是ssrDNS 解析方式是使用本机5335端口提供DNS服务，mosnds设置将 Dnsmasq 域名解析请求转发到 MosDNS 服务器，AdGuard上游是mosdns,DHCP下发AdGuard的DNS给客户端。

**Comment by NEARWN** [comment]
最近在开启SSRPLUS(解析方式是使用本机5335端口提供DNS服务),mosnds默认设置情况下，无法更新节点订阅，关闭mosdns后正常更新

**Comment by sbwml** [comment]
虽然我无法复现你说的开机后需要重启 mosdns 才能访问“外网”，但延时启动也给你加上了，不过你要知道如果你去设置它，必须非常谨慎的设置延时的秒数，延时启动时间不宜设置过大，因为在系统开机后的这个时间内，你是完全无法解析任何网站的
