### ISSUE TITLE
建议增加 cloudflare 优选IP的功能

### ISSUE THREAD

**Issue by Ardentwheel** [sbwml/luci-app-mosdns#121]
找了好多方法，但是不是很会设置

**Comment by sbwml** [comment]
所谓优选就是在直连cf 去ping 它的段，挑选几个延时较低的出来测速。这种臃肿的操作是不可能出现在这个插件上的，你能做到的只有本地选出ip后，通过mosdns 的hosts 重定向域名到优选出来的ip 上。

**Comment by qingtian110** [comment]
+1  我觉得 cloudflare 优选 很有用，建议加入

**Comment by sbwml** [comment]
> +1 我觉得 cloudflare 优选 很有用，建议加入

请大声说出你的思路和实现方式，或者有效 PR

**Comment by sbwml** [comment]
添加了，至于会不会用，怎么用。自行研究。

![1](https://github.com/sbwml/luci-app-mosdns/assets/16485166/e19b30fb-f445-40c8-a19f-08a34b11af08)

**Comment by qingtian110** [comment]
> 添加了，至于会不会用，怎么用。自行研究。
> 

我就知道你是可以的，做的非常简单明了

**Comment by drzazi** [comment]
> 添加了，至于会不会用，怎么用。自行研究。
> 
> ![1](https://private-user-images.githubusercontent.com/16485166/268921696-e19b30fb-f445-40c8-a19f-08a34b11af08.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIyMjM3MTAsIm5iZiI6MTcyMjIyMzQxMCwicGF0aCI6Ii8xNjQ4NTE2Ni8yNjg5MjE2OTYtZTE5YjMwZmItZjQ0NS00MGM4LWExOWYtMDhhMzRiMTFhZjA4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI5VDAzMjMzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFjZWU4MWRjZGI3ODVlYmQ1NzZhMDE3OGIxOGRhM2EyZDhhZGE4MGM5MjgxYzM3M2E4NDc2MjQ2OGM4YWIzN2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.EwWbS8YloqFq2A6_p3Pm40NryBgj8YIa54y7oyr8spw)

你好， @sbwml
可否增加域名支持？现在只能手动加ip。
如果可以填写域名，配合https://hub.docker.com/r/lee1080/cfstddns 就可以实现自动更新ip。

**Comment by gqbre** [comment]
结合了 Cloudflare 自动优选 + MosDNS 的方案，欢迎一起改进：
https://github.com/mingxiaoyu/luci-app-cloudflarespeedtest
