### ISSUE TITLE
更新compress至v1.17.0以同步上游

### ISSUE THREAD

**Issue by brainos233** [sbwml/luci-app-mosdns#122]
本项目所使用的compress版本为v1.16.7，应更新至v1.17.0以同步mosdns上游

**Comment by lengfwong** [comment]
有的，个别版本差一点而已

**Comment by sbwml** [comment]
如果你希望 go mod 每时每刻处于最新状态，我推荐你直接修改makefile 

```diff
diff --git a/mosdns/Makefile b/mosdns/Makefile
index a37fa7c..d96367a 100644
--- a/mosdns/Makefile
+++ b/mosdns/Makefile
@@ -38,6 +38,17 @@ endef
 
 GO_PKG_TARGET_VARS:=$(filter-out CGO_ENABLED=%,$(GO_PKG_TARGET_VARS)) CGO_ENABLED=0
 
+define Build/UpdateDependencies
+	cd $(PKG_BUILD_DIR) && \
+		go get -u && \
+		go mod tidy
+endef
+
+define Build/Compile
+	$(call Build/UpdateDependencies)
+	$(call GoPackage/Build/Compile)
+endef
+
 define Package/mosdns/install
 	$(call GoPackage/Package/Install/Bin,$(1))
 endef

```

**Comment by sbwml** [comment]
![image](https://github.com/sbwml/luci-app-mosdns/assets/16485166/5504a19a-7092-4ef4-ab0e-1ac59cf32af6)
![image](https://github.com/sbwml/luci-app-mosdns/assets/16485166/d1ddd4c4-1926-4143-84ea-f3440567f287)

明白没有

**Comment by brainos233** [comment]
> ![image](https://user-images.githubusercontent.com/16485166/268795039-5504a19a-7092-4ef4-ab0e-1ac59cf32af6.png) ![image](https://user-images.githubusercontent.com/16485166/268795187-d1ddd4c4-1926-4143-84ea-f3440567f287.png)
> 
> 明白没有

这个issue提出是由于在排查新版本mosdns的udp服务器问题时，发现经过patch的代码和mosdns的master版本的代码不一致。虽然udp服务器的问题已经被最新的commit修复了，不过我认为本项目的代码还是应该同上游一致比较好

**Comment by sbwml** [comment]
实际上没有follow main 分支的意思，不然版本也不会是 5.1.3 而是 latest git HEAD
