### ISSUE TITLE
lede编译报错

### ISSUE THREAD

**Issue by dsyo2008** [sbwml/luci-app-mosdns#125]
make[3]: Entering directory '/home/dsyo2008/lede/package/mosdns/mosdns'
rm -f /home/dsyo2008/lede/build_dir/target-x86_64_musl/mosdns-5.1.3/.built
touch /home/dsyo2008/lede/build_dir/target-x86_64_musl/mosdns-5.1.3/.built_check
CONFIG_GOLANG_MOD_CACHE_WORLD_READABLE="" GO_BUILD_CACHE_DIR="/home/dsyo2008/lede/tmp/go-build" GO_MOD_CACHE_DIR="/home/dsyo2008/lede/dl/go-mod-cache" GO_MOD_ARGS="-modcacherw" GO_PKG="github.com/IrineSistiana/mosdns" GO_INSTALL_EXTRA="" GO_INSTALL_ALL="" GO_SOURCE_ONLY="" GO_BUILD_PKG="github.com/IrineSistiana/mosdns/..." GO_EXCLUDES="" GO_GO_GENERATE="" GO_INSTALL_BIN_PATH="/usr/bin" BUILD_DIR="/home/dsyo2008/lede/build_dir/target-x86_64_musl/mosdns-5.1.3" GO_BUILD_DIR="/home/dsyo2008/lede/build_dir/target-x86_64_musl/mosdns-5.1.3/.go_work/build" GO_BUILD_BIN_DIR="/home/dsyo2008/lede/build_dir/target-x86_64_musl/mosdns-5.1.3/.go_work/build/bin" GO_BUILD_DEPENDS_PATH="/usr/share/gocode" GO_BUILD_DEPENDS_SRC="/home/dsyo2008/lede/staging_dir/target-x86_64_musl/usr/share/gocode/src" GOOS="linux" GOARCH="amd64" GO386="" GOAMD64="v1" GOARM="" GOMIPS="" GOMIPS64="" GOPPC64="" CC="x86_64-openwrt-linux-musl-gcc" CXX="x86_64-openwrt-linux-musl-g++" CGO_CFLAGS="-Os -pipe -fno-caller-saves -fno-plt -fhonour-copts -fmacro-prefix-map=/home/dsyo2008/lede/build_dir/target-x86_64_musl/mosdns-5.1.3=mosdns-5.1.3 -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro" CGO_CPPFLAGS="-I/home/dsyo2008/lede/staging_dir/toolchain-x86_64_gcc-11.3.0_musl/usr/include -I/home/dsyo2008/lede/staging_dir/toolchain-x86_64_gcc-11.3.0_musl/include/fortify -I/home/dsyo2008/lede/staging_dir/toolchain-x86_64_gcc-11.3.0_musl/include" CGO_CXXFLAGS="-Os -pipe -fno-caller-saves -fno-plt -fhonour-copts -fmacro-prefix-map=/home/dsyo2008/lede/build_dir/target-x86_64_musl/mosdns-5.1.3=mosdns-5.1.3 -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro" CGO_LDFLAGS="-L/home/dsyo2008/lede/staging_dir/toolchain-x86_64_gcc-11.3.0_musl/usr/lib -L/home/dsyo2008/lede/staging_dir/toolchain-x86_64_gcc-11.3.0_musl/lib -znow -zrelro" CGO_ENABLED=0 GOPATH="/home/dsyo2008/lede/build_dir/target-x86_64_musl/mosdns-5.1.3/.go_work/build" GOCACHE="/home/dsyo2008/lede/tmp/go-build" GOMODCACHE="/home/dsyo2008/lede/dl/go-mod-cache" GOENV=off /usr/bin/env bash /home/dsyo2008/lede/feeds/packages/lang/golang//golang-build.sh build -v -buildvcs=false -trimpath -ldflags "all=-buildid '1695120865' -linkmode external -extldflags '-L/home/dsyo2008/lede/staging_dir/toolchain-x86_64_gcc-11.3.0_musl/usr/lib -L/home/dsyo2008/lede/staging_dir/toolchain-x86_64_gcc-11.3.0_musl/lib -Wl,-z,now -Wl,-z,relro'"        -ldflags " -X main.version=v5.1.3-10 -buildid '1695120865' -linkmode external -extldflags '-L/home/dsyo2008/lede/staging_dir/toolchain-x86_64_gcc-11.3.0_musl/usr/lib -L/home/dsyo2008/lede/staging_dir/toolchain-x86_64_gcc-11.3.0_musl/lib -Wl,-z,now -Wl,-z,relro'"  
Finding targets
go: errors parsing go.mod:
/home/dsyo2008/lede/build_dir/target-x86_64_musl/mosdns-5.1.3/go.mod:5: unknown directive: toolchain

Building targets
go: errors parsing go.mod:
/home/dsyo2008/lede/build_dir/target-x86_64_musl/mosdns-5.1.3/go.mod:5: unknown directive: toolchain

Makefile:46: recipe for target '/home/dsyo2008/lede/build_dir/target-x86_64_musl/mosdns-5.1.3/.built' failed
make[3]: *** [/home/dsyo2008/lede/build_dir/target-x86_64_musl/mosdns-5.1.3/.built] Error 1
make[3]: Leaving directory '/home/dsyo2008/lede/package/mosdns/mosdns'
time: package/mosdns/mosdns/compile#0.09#0.01#0.10
    ERROR: package/mosdns/mosdns failed to build.
package/Makefile:114: recipe for target 'package/mosdns/mosdns/compile' failed
make[2]: *** [package/mosdns/mosdns/compile] Error 1
make[2]: Leaving directory '/home/dsyo2008/lede'
package/Makefile:110: recipe for target '/home/dsyo2008/lede/staging_dir/target-x86_64_musl/stamp/.package_compile' failed
make[1]: *** [/home/dsyo2008/lede/staging_dir/target-x86_64_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/dsyo2008/lede'
/home/dsyo2008/lede/include/toplevel.mk:229: recipe for target 'world' failed
make: *** [world] Error 2

之前没问题，更新后报错，这是啥问题？

**Comment by sbwml** [comment]
两个方法
1】git reset 源码到 e255e8fb98fe138bf543ffdb5d8edb4c289b02a6
2】更新golang到 1.21

**Comment by dsyo2008** [comment]
> 两个方法 1】git reset 源码到 [e255e8f](https://github.com/sbwml/luci-app-mosdns/commit/e255e8fb98fe138bf543ffdb5d8edb4c289b02a6) 2】更新golang到 1.21

OK

**Comment by sbwml** [comment]
已修复
