### ISSUE TITLE
怎么查看是 CPU 架构是 cortex-a53 还是 Cortex-A72

### ISSUE THREAD

**Issue by Skylarzz** [sbwml/luci-app-mosdns#127]
cpuinfo 只给出 ARMv8 Processor rev 4 (v8l) 
搜索 CPU 型号 + datasheet 也没有结果

**Comment by sbwml** [comment]
https://github.com/sbwml/luci-app-mosdns#how-to-install-prebuilt-packages

**Comment by Skylarzz** [comment]
硬路由闪存很小，脚本会提示空间小于 40MB

**Comment by sbwml** [comment]
那就不装它了，反正意义不大。非要装的话考虑 404 大佬的版本 https://github.com/QiuSimons/openwrt-mos

**Comment by Skylarzz** [comment]
手动安装上了，贴个流程供后来者参考

1. 下载以下文件
    1. v2ray-geosite_2023-09-19_all.ipk
    2. v2ray-geoip_2023-09-19_all.ipk
    3. v2dat_2022-12-15-47b8ee51-1_aarch64_cortex-a53.ipk
    4. mosdns_5.1.3-10_aarch64_cortex-a53.ipk
    5. luci-app-mosdns_1.5.8_all.ipk
    6. luci-i18n-mosdns-zh-cn_git-23.262.36291-aa9b562_all.ipk
2. scp 上传至 OpenWrt
    `scp -r "D:\luci-app\openwrt_mosdns" root@192.168.1.11:/tmp/upload`
3. shh 依序安装（可选 `--force-depends`）
    `ssh root@192.168.1.11`
    `cd /tmp/upload/openwrt_mosdns`
    `opkg install v2ray-geosite_2023-09-19_all.ipk`
    `opkg install v2ray-geoip_2023-09-19_all.ipk`
    `opkg install v2dat_2022-12-15-47b8ee51-1_aarch64_cortex-a53.ipk`
    `opkg install mosdns_5.1.3-10_aarch64_cortex-a53.ipk`
    `opkg install luci-app-mosdns_1.5.8_all.ipk`
    `opkg install luci-i18n-mosdns-zh-cn_git-23.262.36291-aa9b562_all.ipk`


最后还是没有找到查询 CPU 架构的方法，只能碰运气

**Comment by sbwml** [comment]
https://github.com/sbwml/luci-app-mentohust/releases/tag/v0.3.1  架构信息参考
