### ISSUE TITLE
无法使用自建的 DoQ

### ISSUE THREAD

**Issue by qingtian110** [sbwml/luci-app-mosdns#129]
使用 ADG 或者 dnsproxy 自建的 DoQ 无法正常使用，但是阿里云DNS 的 DoQ 是正常的。

上游 master 分支直接跑配置文件也有这个问题。https://github.com/IrineSistiana/mosdns/issues/720

我测试 openwrt luci 版本也是无法正常使用自建的 doq 服务。

**Comment by sbwml** [comment]
我能做到的是直接砍掉 doq

从 Windows 版邮件发送

发件人: qingtian110
发送时间: 2023年9月23日 13:58
收件人: sbwml/luci-app-mosdns
抄送: Subscribed
主题: [sbwml/luci-app-mosdns] 无法使用自建的 DoQ (Issue #129)

使用 ADG 或者 dnsproxy 自建的 DoQ 无法正常使用，但是阿里云DNS 的 DoQ 是正常的。
上游 master 分支直接跑配置文件也有这个问题。IrineSistiana/mosdns#720
我测试 openwrt luci 版本也是无法正常使用自建的 doq 服务。

**Comment by qingtian110** [comment]
老哥  上游修复了，求更新一下mosdns pkg
