### ISSUE TITLE
突然无法用命令安装了呢？

### ISSUE THREAD

**Issue by asnon** [sbwml/luci-app-mosdns#131]
看到版本有更新，但是运行sh -c "$(curl -ksS https://raw.githubusercontent.com/sbwml/luci-app-mosdns/v5/install.sh)"提示
Error relocating /usr/bin/curl: curl_global_trace: symbol not found

**Comment by sbwml** [comment]
你的curl 坏掉了，curl 和 libcurl 库不匹配，通常这种情况出现在一些稀奇古怪的固件上，比如官方 openwrt 应该不存在这种情况。

你依然可以通过手动下载 ipk 文件安装

**Comment by asnon** [comment]
> 你的curl 坏掉了，curl 和 libcurl 库不匹配，通常这种情况出现在一些稀奇古怪的固件上，比如官方 openwrt 应该不存在这种情况。
> 
> 你依然可以通过手动下载 ipk 文件安装

哦哦 确实是一个新固件。。应该是有问题。。换回之前的就好了
