### ISSUE TITLE
r2s上安装脚本报错Failed to get version information, Please check the network status.

### ISSUE THREAD

**Issue by shinonomeow** [sbwml/luci-app-mosdns#132]
真的是我的网络问题吗,脚本都拉取下来了,说明可以连接github啊

```
Downloading https://mirrors.cloud.tencent.com/openwrt/releases/18.06.8/packages/aarch64_generic/routing/Packages.sig
Signature check passed.
Package luci-compat (git-22.161.56906-efa5cfe-1) installed in root is up to date.

Download Packages ...

Failed to get version information, Please check the network status.
```

**Comment by sbwml** [comment]
因为你家根本访问不了 api.github.com ，建议直接下ipk 文件去安装。

**Comment by shinonomeow** [comment]
> 因为你家根本访问不了 api.github.com ，建议直接下ipk 文件去安装。

抱歉大佬,再请问一下r2s的 ARMv8 Processor x 4  架构应该下载什么后缀的ipk呢
GPT说可以安装
mosdns_5.1.3-16_aarch64_cortex-a53.ipk
mosdns_5.1.3-16_aarch64_cortex-a72.ipk
mosdns_5.1.3-16_aarch64_generic.ipk
这几个是对的吗

**Comment by sbwml** [comment]
我不知道  理论上 aarch64_generic ，猜的。反正能成功安装的那个就是对的

**Comment by shinonomeow** [comment]
> 我不知道 理论上 aarch64_generic ，猜的。反正能成功安装的那个就是对的

感谢大佬的帮助,确实是 aarch64_generic
