### ISSUE TITLE
能不能把广告过滤选项移动到更新数据库那？

### ISSUE THREAD

**Issue by 4thanks** [sbwml/luci-app-mosdns#133]
目前只有使用内置配置才能设置广告过滤，自定义配置就隐藏了。虽然会自定义配置可能不算小白，但能偷懒就想偷懒😂。

**Comment by sbwml** [comment]
估计不能，会有误导性bug，在没有使用内置配置时，它是一个无功能的存在。如果你用自定义配置了，不应该再去依赖任何的luci选项，自动操作应该交给openwrt的计划任务（crontab）
