### ISSUE TITLE
mosdns 已经更新版本 v5.2.1

### ISSUE THREAD

**Issue by qingtian110** [sbwml/luci-app-mosdns#135]
https://github.com/IrineSistiana/mosdns/releases/tag/v5.2.1

**Comment by sbwml** [comment]
这么快的吗

**Comment by qingtian110** [comment]
forward: 支持 DoQ 上游。bootstrap 支持全部协议。
quic_server: DoQ 服务器。
rate_limiter: 可限制客户端的 qps。
string_exp: 匹配字符串。支持正则。可以匹配 DoH 服务器的 url path，TLS 协议的 SNI。

这是更新的内容。他有 doq server 和 请求限速了，不过非常可惜啊，这些更新的点反而在openwrt 这种本地用的作用不大。它要是有 v4 版本的 auto ecs 和 query_matcher ecs ip，就可以用它在公网上部署了，完替 adg、dnsproxy、mosdns v4。公网部署现在只能苟活在 v4 版本   外加 adg 或 dnsproxy 来支持 doq 协议。

**Comment by lengfwong** [comment]
> forward: 支持 DoQ 上游。bootstrap 支持全部协议。 quic_server: DoQ 服务器。 rate_limiter: 可限制客户端的 qps。 string_exp: 匹配字符串。支持正则。可以匹配 DoH 服务器的 url path，TLS 协议的 SNI。
> 
> 这是更新的内容。他有 doq server 和 请求限速了，不过非常可惜啊，这些更新的点反而在openwrt 这种本地用的作用不大。它要是有 v4 版本的 auto ecs 和 query_matcher ecs ip，就可以用它在公网上部署了，完替 adg、dnsproxy、mosdns v4。公网部署现在只能苟活在 v4 版本 外加 adg 或 dnsproxy 来支持 doq 协议。

doq协议有什么优点呢？

**Comment by naoki66** [comment]
编译过程中有个警告，不知道是哪里问题
sysctl: cannot open "/etc/sysctl.d/20-mosdns-buffer-increase.conf": No such file or directory
immortalwrt-imagebuilder-21.02.7-x86-64.Linux-x86_64/build_dir/target-x86_64_musl/root-x86/etc/init.d/mosdns: line 27: uci: command not found
./etc/init.d/mosdns: line 27: uci: command not found

**Comment by sbwml** [comment]
> 编译过程中有个警告，不知道是哪里问题
> sysctl: cannot open "/etc/sysctl.d/20-mosdns-buffer-increase.conf": No such file or directory
> immortalwrt-imagebuilder-21.02.7-x86-64.Linux-x86_64/build_dir/target-x86_64_musl/root-x86/etc/init.d/mosdns: line 27: uci: command not found
> ./etc/init.d/mosdns: line 27: uci: command not found

这个 pr #102 有提到那个什么imagebuilder，但是这个 pr 是一个错误的解决方式，被我 revert 了


我不清楚imgbuilder 是一个什么样子的环境，如果他只是一个警告不影响构建结果，那么我建议忽略。

如果这个问题已经影响到编译结果，那么你参考 #102

**Comment by lengfwong** [comment]
``> > 编译过程中有个警告，不知道是哪里问题
> > sysctl: cannot open "/etc/sysctl.d/20-mosdns-buffer-increase.conf": No such file or directory
> > immortalwrt-imagebuilder-21.02.7-x86-64.Linux-x86_64/build_dir/target-x86_64_musl/root-x86/etc/init.d/mosdns: line 27: uci: command not found
> > ./etc/init.d/mosdns: line 27: uci: command not found
> 
> 这个 pr #102 有提到那个什么imagebuilder，但是这个 pr 是一个错误的解决方式，被我 revert 了
> 
> 我不清楚imgbuilder 是一个什么样子的环境，如果他只是一个警告不影响构建结果，那么我建议忽略。
> 
> 如果这个问题已经影响到编译结果，那么你参考 #102

看了一下我晚上编译也有类似的提示，不过也编译完成了，似乎也不影响用，前后的输出：
```
Configuring dnsmasq-full.
Setting flags for package libc to hold.
Setting flags for package libgcc1 to hold.
Setting flags for package libatomic1 to hold.
Setting flags for package libstdcpp6 to hold.
Setting flags for package libpthread to hold.
Setting flags for package librt to hold.
cp -fpR /home/wangyf/openwrt/build_dir/target-x86_64_musl/root-x86 /home/wangyf/openwrt/build_dir/target-x86_64_musl/root.orig-x86
/home/wangyf/openwrt/build_dir/target-x86_64_musl/root-x86/etc/init.d/dnsmasq: line 4: /lib/functions.sh: No such file or directory
sysctl: cannot open "/etc/sysctl.d/20-mosdns-buffer-increase.conf": No such file or directory
/home/wangyf/openwrt/build_dir/target-x86_64_musl/root-x86/etc/init.d/mosdns: line 27: uci: command not found
Enabling boot
Enabling cron
./etc/init.d/dnsmasq: line 4: /lib/functions.sh: No such file or directory
Enabling dnsmasq
Enabling done
Enabling dropbear
Enabling firewall
Enabling gpio_switch
Enabling led
Enabling log
Enabling miniupnpd
./etc/init.d/mosdns: line 27: uci: command not found
Enabling mosdns
Enabling network
Enabling odhcpd
```

**Comment by naoki66** [comment]
感谢，imgbuilder 实际上就是基础的固件+自定义安装包，编译时间很快。云编译仅需十来分钟。
可以参考我的
https://github.com/naoki66/Actions_ImmortalWrt_Openwrt/blob/main/.github/workflows/imagebuilder_21.02.7.yml
坏处是内核之类的不能更改。
但是sbwml大佬的这个源彻底解决了我解析缓慢和泄漏的问题。必须start！目前编译通过，暂无影响。

**Comment by sbwml** [comment]
> ``> > 编译过程中有个警告，不知道是哪里问题
> 
> > > sysctl: cannot open "/etc/sysctl.d/20-mosdns-buffer-increase.conf": No such file or directory
> > > immortalwrt-imagebuilder-21.02.7-x86-64.Linux-x86_64/build_dir/target-x86_64_musl/root-x86/etc/init.d/mosdns: line 27: uci: command not found
> > > ./etc/init.d/mosdns: line 27: uci: command not found
> > 
> > 
> > 这个 pr #102 有提到那个什么imagebuilder，但是这个 pr 是一个错误的解决方式，被我 revert 了
> > 我不清楚imgbuilder 是一个什么样子的环境，如果他只是一个警告不影响构建结果，那么我建议忽略。
> > 如果这个问题已经影响到编译结果，那么你参考 #102
> 
> 看了一下我晚上编译也有类似的提示，不过也编译完成了，似乎也不影响用，前后的输出：
> 
> ```
> Configuring dnsmasq-full.
> Setting flags for package libc to hold.
> Setting flags for package libgcc1 to hold.
> Setting flags for package libatomic1 to hold.
> Setting flags for package libstdcpp6 to hold.
> Setting flags for package libpthread to hold.
> Setting flags for package librt to hold.
> cp -fpR /home/wangyf/openwrt/build_dir/target-x86_64_musl/root-x86 /home/wangyf/openwrt/build_dir/target-x86_64_musl/root.orig-x86
> /home/wangyf/openwrt/build_dir/target-x86_64_musl/root-x86/etc/init.d/dnsmasq: line 4: /lib/functions.sh: No such file or directory
> sysctl: cannot open "/etc/sysctl.d/20-mosdns-buffer-increase.conf": No such file or directory
> /home/wangyf/openwrt/build_dir/target-x86_64_musl/root-x86/etc/init.d/mosdns: line 27: uci: command not found
> Enabling boot
> Enabling cron
> ./etc/init.d/dnsmasq: line 4: /lib/functions.sh: No such file or directory
> Enabling dnsmasq
> Enabling done
> Enabling dropbear
> Enabling firewall
> Enabling gpio_switch
> Enabling led
> Enabling log
> Enabling miniupnpd
> ./etc/init.d/mosdns: line 27: uci: command not found
> Enabling mosdns
> Enabling network
> Enabling odhcpd
> ```

这个属于预期行为，因为固件编译到最后会有个 install 操作。而在宿主机的环境下这些东西必然是不存在的。就你发出来的日志就很直观看得到，除了mosdns 这个第三方的插件外，dnsmasq、miniupnpd 这种官方包同样会显示这种“错误”。但实际上这些不需要去关心

**Comment by sbwml** [comment]
# 友情提醒：在 imagebuiler 的环境下如果也仅仅是显示个警告消息而不影响固件生成，我不建议你去动 mosdns 的代码。但如果它是以整个固件编译失败告终的，再参考 #102 （PS：这个操作会导致 rc.d 的问题，这就是我 revert 它的原因 https://github.com/sbwml/luci-app-mosdns/commit/1a2c17a5d0d44362900ecfc597b2d2f98387dbb3 ）

**Comment by qingtian110** [comment]
> doq协议有什么优点呢？

和 http3 一样，拥有 0rtt 的特性。说人话就是，让加密DNS 握手更快。

**Comment by qingtian110** [comment]
> > doq协议有什么优点呢？
> 
> 和 http3 一样，拥有 0rtt 的特性。说人话就是，让加密DNS 握手更快。

但是吧，也没敢直接用h3，因为在openwrt 上如果启用h3，他会让所有 https 协议的dns 都开启了，一些不支持 h3 的dns 在这就会失去工作。

嘿，这个时候quic 来的就特别舒服了，直接关闭 http3 支持，直接使用  quic://  https://（h2）  两者共存。

但我更希望能把 h3 和 h2/h1 彻底区分开来，h3:// 强制使用 doh3 协议，https:// 则使用常规 doh 协议

**Comment by IrineSistiana** [comment]
> > doq协议有什么优点呢？
> 
> 和 http3 一样，拥有 0rtt 的特性。说人话就是，让加密DNS 握手更快。

0rtt 是可选的。mosdns 0rtt 目前全关。

**Comment by qingtian110** [comment]
> > > doq协议有什么优点呢？
> > 
> > 
> > 和 http3 一样，拥有 0rtt 的特性。说人话就是，让加密DNS 握手更快。
> 
> 0rtt 是可选的。mosdns 0rtt 目前全关。

全关？😯

**Comment by IrineSistiana** [comment]
1. 0rtt 只是少一次握手来回。对于一次性的请求确实有很大的提升。 对于 dns 这种一个连接会处理成百上千给请求的，没用。

2. 0rtt 之所以是协议的可选项，因为 0rtt 不是白给的特性，它有代价。

一句话就是，dns 没必要 0rtt。

**Comment by cqjerry** [comment]
今天更新到v5.2.1后，发现 lazy_cache 一直报 failed to update。

**Comment by qingtian110** [comment]
> 今天更新到v5.2.1后，发现 lazy_cache 一直报 failed to update。

估计和更不更新的关系不大，这个日志一直都有，我用公共dns 的时候一直会有这个日志，换了自建的dns 后，就几乎没见过了，提示这个一般都是公共dns 查询失败的时候就会跳出来。尤其一些比较差的dns
