### ISSUE TITLE
感谢去广告支持多个列表了，但是自定义的不生效。

### ISSUE THREAD

**Issue by iamyangyiok** [sbwml/luci-app-mosdns#136]
感谢去广告支持多个列表了，但是自定义的好像不生效。我添加 https://gp.adrules.top/ad-domains.txt，登录上去d-domains.txt文件一直ad-domains.txt为0，不下载。

**Comment by sbwml** [comment]
## 测试一切正常，添加这个列表后：列表的下载、配置文件的生成、拦截效果 均正常。

![image](https://github.com/sbwml/luci-app-mosdns/assets/16485166/d216f761-5f64-4942-8e27-1ba2c01dc35f)

![image](https://github.com/sbwml/luci-app-mosdns/assets/16485166/3250c69d-51b2-4229-a3f8-86b1f266ee55)

![image](https://github.com/sbwml/luci-app-mosdns/assets/16485166/b0913257-c259-442c-8fb0-e19433277acd)


-----------

## 访问该列表其中一个域名 beacon.sina.com.cn

![image](https://github.com/sbwml/luci-app-mosdns/assets/16485166/2238be4d-9ece-4b90-a640-9f76a7377ee4)

----------


# PS：使用 HTTP URL 方式添加广告列表来源的前提需要你的路由器能够正常访问到该列表

**Comment by sbwml** [comment]
## 即使添加多个列表，也都正常

![image](https://github.com/sbwml/luci-app-mosdns/assets/16485166/7f34c876-b2dd-4914-8ddc-5886e27885cb)

![image](https://github.com/sbwml/luci-app-mosdns/assets/16485166/6cc035e6-1f26-4ebc-8592-4ffd037554fc)

![image](https://github.com/sbwml/luci-app-mosdns/assets/16485166/8c471615-f990-47d3-ab86-a47a6fe1956c)

**Comment by sbwml** [comment]
广告列表实现逻辑没有问题，如果文件一直无法被下载，我推荐使用高质量的列表来源。或直接下载文件上传，并使用 `file:///dir/filename.txt` 指定到文件。

**Comment by iamyangyiok** [comment]
那我再试试，默认的这个选项列表 嵌入到文件中 是哪个文件啊。感谢

**Comment by iamyangyiok** [comment]
> 广告列表实现逻辑没有问题，如果文件一直无法被下载，我推荐使用高质量的列表来源。或直接下载文件上传，并使用 `file:///dir/filename.txt` 指定到文件。

我直接浏览器开这个地址没问题，不知道为啥就写进去不行了。

**Comment by sbwml** [comment]
> 那我再试试，默认的这个选项列表 嵌入到文件中 是哪个文件啊。感谢

https://github.com/sbwml/luci-app-mosdns/blob/v5/luci-app-mosdns/luasrc/model/cbi/mosdns/basic.lua

**Comment by sbwml** [comment]
这和luci 选项列表无关，重点看你路由器网络，你可能会可以很顺利使用luci 列表自带的规则，因为这些规则不要求本地网络情况，他自带了规则代理下载的支持
