### ISSUE TITLE
移除 20-mosdns-buffer-increase.conf

### ISSUE THREAD

**Issue by IrineSistiana** [sbwml/luci-app-mosdns#137]
luci-app-mosdns/root/etc/sysctl.d/20-mosdns-buffer-increase.conf

可以删掉。mosdns 用不到。那个 log 是 quic 报的，不是 mosdns 。

~~环境变量 QUIC_GO_DISABLE_RECEIVE_BUFFER_WARNING=true 能把这行log禁了。~~
我下次从mosdns把这log禁了

**Comment by IrineSistiana** [comment]
luci-app-mosdns/root/usr/share/mosdns/cache.dump

也可以删掉。

**Comment by sbwml** [comment]
cache.dump 是不影响的，它存在的目的是让 luci 在禁用 & 启用缓存时，以覆盖的形式去 “清空” 上次存在的 或 被 openwrt 备份功能还原过的 cache 文件
