### ISSUE TITLE
【功能改进】希望 https 与 https3 可以共存

### ISSUE THREAD

**Issue by qingtian110** [sbwml/luci-app-mosdns#138]
目前的存在的不足：

MosDNS - 高级选项 - 国内 DNS 启用 HTTP/3 ✔ / 远程 DNS 启用 HTTP/3 ✔

他会对所有 `https://` 协议的 DNS 启用 http3，这导致无法进行这样的设置：

```
uci add_list mosdns.config.local_dns='https://dns.alidns.com/dns-query'
uci add_list mosdns.config.local_dns='https://doh.pub/dns-query'
```

其中 阿里云DNS 是正常的，因为他支持 HTTP3 协议，但是第二个 腾讯DNS 是无法工作的，因为他不支持 HTTP3，一直报错。

-----------

希望的结果是，移除高级选项中的 “启用 HTTP/3” 协议的选项，然后如果用户要对某个DNS 启用 http3，那么就使用 `h3://dns.alidns.com/dns-query` 的方式，只对 h3:// 开头的启用 `enable_http3: true` ，这样以来就可以共存 https和https3 了。

这个还挺有需要的，因为以独立的选项给全部的 DNS 添加 `enable_http3: true` ，当遇到不支持 h3 协议的DNS 时，他是强制h3而不会回退 h2/h1 的，确实会导致问题的发生。

**Comment by sbwml** [comment]
这个问题我当时就有考虑到了，但是在op 插件这种跑脚本的东西上不好做。我再想想法子吧。

**Comment by qingtian110** [comment]
啊这。 或者可以找 mosdns 上游请求加一个 h3:// 开头的 dns 自动打开 `enable_http3: true` 的？

**Comment by qingtian110** [comment]
呼叫 @IrineSistiana 大佬有法子吗？

**Comment by sbwml** [comment]
问题已解决 https://github.com/sbwml/luci-app-mosdns/commit/e31521dd01ecefb14edd831e0b4821143aa2fff9 。

当使用 `h3://xxxxx` 时才启用 `enable_http3: true`。

**Comment by IrineSistiana** [comment]
h3:// 可以考虑。

自动回退协议。暂时不考虑。我觉得折腾DNS的大多数希望所见即所得。即“我清楚我在干什么，我配置了h3就一定用h3连。”

**Comment by qingtian110** [comment]
> h3:// 可以考虑。
> 
> 自动回退协议。暂时不考虑。我觉得折腾DNS的大多数希望所见即所得。即“我清楚我在干什么，我配置了h3就一定用h3连。”

大佬，要是v5 在后续的更新中，能支持 v4 版本那种 auto ecs 和匹配 ecs ip 就好了
```
  - tag: query_ecs_has_cn_ip
    type: query_matcher
    args:
      ecs:
        - "provider:geoip:cn"
```

在自己服务器上做无污染的DNS服务端，v5 就只差 ecs 了。重点mosdns v5 的服务端协议    他一个就顶好几个程序了。
