### ISSUE TITLE
求助，安装不成功

### ISSUE THREAD

**Issue by Mrican** [sbwml/luci-app-mosdns#139]
root@GL-MT3000:~# opkg update
Downloading https://fw.gl-inet.cn/releases/v21.02.3/kmod-4.2.1/aarch64_cortex-a53/mediatek/mt7981/Packages.gz
Updated list of available packages in /var/opkg-lists/glinet_core
Downloading https://fw.gl-inet.cn/releases/v21.02.3/packages-4.0/aarch64_cortex-a53/glinet/Packages.gz
Updated list of available packages in /var/opkg-lists/glinet_gli_pub
Downloading https://fw.gl-inet.cn/releases/v21.02.3/packages-4.0/aarch64_cortex-a53/packages/Packages.gz
Updated list of available packages in /var/opkg-lists/glinet_gli_packages
Updating database.
Database update completed.
root@GL-MT3000:~# opkg install curl
Package curl (7.83.1-1) installed in root is up to date.
Updating database.
Database update completed.
root@GL-MT3000:~# sh -c "$(curl -ksS https://raw.githubusercontent.com/sbwml/luc
i-app-mosdns/v5/install.sh)"

Checking available space  ...

Checking platform  ...

Update opkg sources ...
Downloading https://fw.gl-inet.cn/releases/v21.02.3/kmod-4.2.1/aarch64_cortex-a53/mediatek/mt7981/Packages.gz
Updated list of available packages in /var/opkg-lists/glinet_core
Downloading https://fw.gl-inet.cn/releases/v21.02.3/packages-4.0/aarch64_cortex-a53/glinet/Packages.gz
Updated list of available packages in /var/opkg-lists/glinet_gli_pub
Downloading https://fw.gl-inet.cn/releases/v21.02.3/packages-4.0/aarch64_cortex-a53/packages/Packages.gz
Updated list of available packages in /var/opkg-lists/glinet_gli_packages
Updating database.
Database update completed.
Package luci-compat (git-22.046.85744-f08a0f6) installed in root is up to date.
Updating database.
Database update completed.

Download Packages ...

Download https://github.com/sbwml/luci-app-mosdns/releases/download/v5.2.1/mosdns_5.2.1-1_aarch64_cortex-a53.ipk ...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 5652k  100 5652k    0     0  2258k      0  0:00:02  0:00:02 --:--:-- 2287k
Download https://github.com/sbwml/luci-app-mosdns/releases/download/v5.2.1/v2dat_2022-12-15-47b8ee51-1_aarch64_cortex-a53.ipk ...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 2555k  100 2555k    0     0  1130k      0  0:00:02  0:00:02 --:--:-- 1131k
Download https://github.com/sbwml/luci-app-mosdns/releases/download/v5.2.1/luci-app-mosdns_1.5.12_all.ipk ...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 77015  100 77015    0     0  58861      0  0:00:01  0:00:01 --:--:-- 58879
Download https://github.com/sbwml/luci-app-mosdns/releases/download/v5.2.1/luci-i18n-mosdns-zh-cn_git-23.271.70451-e31521d_all.ipk ...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  4614  100  4614    0     0   4637      0 --:--:-- --:--:-- --:--:--  4641
Download https://github.com/sbwml/luci-app-mosdns/releases/download/v5.2.1/v2ray-geoip_2023-09-28_all.ipk ...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 34219  100 34219    0     0  25817      0  0:00:01  0:00:01 --:--:-- 25845
Download https://github.com/sbwml/luci-app-mosdns/releases/download/v5.2.1/v2ray-geosite_2023-09-28_all.ipk ...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 1312k  100 1312k    0     0   564k      0  0:00:02  0:00:02 --:--:--  564k

Install Packages ...

Installing v2ray-geoip (2023-09-28) to root...
Configuring v2ray-geoip.
Updating database.
Database update completed.
Installing v2ray-geosite (2023-09-28) to root...
Configuring v2ray-geosite.
Updating database.
Database update completed.
Installing v2dat (2022-12-15-47b8ee51-1) to root...
Configuring v2dat.
Updating database.
Database update completed.
Installing mosdns (5.2.1-1) to root...
Configuring mosdns.
Updating database.
Database update completed.
Unknown package 'luci-app-mosdns'.
Collected errors:
 * pkg_hash_check_unresolved: cannot find dependency luci-lua-runtime for luci-app-mosdns
 * pkg_hash_fetch_best_installation_candidate: Packages for luci-app-mosdns found, but incompatible with the architectures configured
 * opkg_install_cmd: Cannot install package luci-app-mosdns.
Unknown package 'luci-i18n-mosdns-zh-cn'.
Collected errors:
 * pkg_hash_check_unresolved: cannot find dependency luci-app-mosdns for luci-i18n-mosdns-zh-cn
 * pkg_hash_fetch_best_installation_candidate: Packages for luci-i18n-mosdns-zh-cn found, but incompatible with the architectures configured
 * opkg_install_cmd: Cannot install package luci-i18n-mosdns-zh-cn.
Done!

兄弟，帮帮忙

**Comment by maidonghu** [comment]
我也是这个问题。我的机子是电犀牛R68s，装的_aarch64_generic.ipk，结果从luci-app-mosdns_1.5.11到luci-app-mosdns_1.5.12都无法安装，只好退回到luci-app-mosdns_1.5.10才正常安装。错误显示同上。

**Comment by shinonomeow** [comment]
可以手动安装

**Comment by asnon** [comment]
我最新版也是手动安装的，之前每个小版本升级用命令都可以也是奇怪了

**Comment by sbwml** [comment]
。。。因为luci app 我是手动上传，基于OpenWrt 23.05 产出。lua runtime 依赖缘故，你们的固件是 OpenWrt 22以下或者LEDE 就会安装失败。

吃完饭我再用老的sdk 编一下，一小时后再下载试试吧

**Comment by sbwml** [comment]
好了

**Comment by Mrican** [comment]
thinks
