### ISSUE TITLE
关于Apple 域名解析优化

### ISSUE THREAD

**Issue by EdisonCh4n** [sbwml/luci-app-mosdns#140]
大佬我处位置ping不通114.114.114.114，可以自定义指定DNS嘛？我在设置文档中修改DNS配置中114段的DNS，保存或重启后又还原了，当然想到过可以使用自定义配置，但是默认配置用习惯了。谢谢大佬。

**Comment by sbwml** [comment]
信风 114、115 DNS 它是禁 ping 的，它坐标在南京。国内范围的运营商使用它都不会差。

另外你完全没有必要去修改它，因为你只要关闭 “Apple 域名解析优化” ，这个 DNS 就永远不会自动使用。

使用 114 是网友们经过了多个区域测试才决定使用的，使用它解析 Apple 域名不会被解析到全球 CDN 上。虽然百度DNS 也有同样的效果，但是百度的 DNS 日常解析失败率非常高。

**Comment by EdisonCh4n** [comment]
谢谢解惑
