### ISSUE TITLE
拉源编译出来 还是5.13，但LUCI是最新了21版了

### ISSUE THREAD

**Issue by iamyangyiok** [sbwml/luci-app-mosdns#143]
拉这源编译出来。 MOSDNS 5.13，但LUCI是最新21版了。
#MOSDNS源没同步？还是我编译方法不对，请教下大大。
克隆 git clone https://github.com/sbwml/luci-app-mosdns -b v5 package/mosdns

**Comment by sbwml** [comment]
因为你用的op源码已经包含了老版本的mosdns & luci。具体解决方法参考 readme https://github.com/sbwml/luci-app-mosdns#how-to-build

**Comment by iamyangyiok** [comment]
> 因为你用的op源码已经包含了老版本的mosdns & luci。具体解决方法参考 readme https://github.com/sbwml/luci-app-mosdns#how-to-build

感谢 我再试下，用最下面清理的方法 MARK MENUCONFG 我直接报错了 ，我手工去清理试下。

**Comment by sbwml** [comment]
。。。。。。。。。。对编译一知半解的，我更推荐下 ipk 文件安装

**Comment by iamyangyiok** [comment]
> 。。。。。。。。。。对编译一知半解的，我更推荐下 ipk 文件安装

很好了 感谢，不了 MOSDNS自己配搞半一，我昨天半夜写了2个建议 不知道是发到谁那了，估计发错了。空了 我再写个！ GOOD JOB FOR U
