### ISSUE TITLE
优化LUCI2点小建议。

### ISSUE THREAD

**Issue by iamyangyiok** [sbwml/luci-app-mosdns#144]
LUCI-APP-MOSDNS
1、更新广告规则、GeoIP & GeoSite 数据库能分开可选择性更新、因为国内直接更新GEODATA慢且经常不成功，且不知道是不是更新机制问题（推测：是否先删再更），现情况LUCI库更新失败的话，会影响PW的V2RAY分流（基于GEODTATA），导致科学中断无法访问。所以，我现在都不敢开LUCI的自动更新，且本身科学的APP也会自带GEODATA更新。所以，能分开更新项目，按需选择，这样不会有冲突影响。
2、正因为有的科学更新或点网络配置重新设置，DNS转发有时会暂时失效和转发错误，导致DNS不可用。我想能否，有一个保护进程的功能，如轮询检测2-3个域名解析，如果不通，则重启MOSDNS服务应用，拿回DNS主导权。

以上是两点使用体会。再次表示感谢和支持。

**Comment by sbwml** [comment]
一、通过mosdns luci / 定时更新数据库，只有两种结果：
更新成功：数据库文件被更新了。
更新失败：什么都没发生过。

脚本动作：https://github.com/sbwml/luci-app-mosdns/blob/v5/luci-app-mosdns/root/usr/share/mosdns/mosdns.sh#L90

所以不会存在因为 mosdns 数据库更新失败会导致别的插件异常，因为它什么都没动过（如果能看懂上面的脚本，就会明白一切）。

二、Dnsmasq 上游设定被其他插件抢占问题，几点有效建议：

⒈ 不要在 openwrt 上使用多个 dns 插件套娃。

⒉ 把会影响 Dnsmasq 设定的插件直接设置上游为 mosdns 监听端口或 `127.0.0.1`。

⒊ 如果你使用 mosdns 仅仅是为了配合科学插件工作，但是你又不知道如何去正确设置科学插件的 dns 上游为 mosdns。推荐使用 404 的版本，这个版本除了分流解析外，还支持一键设置科学插件的dns 上游到 mosdns （安装前，必须卸载当前luci-app-mosdns 和删除残留数据 `/etc/config/moadns`、`/etc/mosdns` ）项目地址：https://github.com/QiuSimons/openwrt-mos

⒋ 使用 OpenWrt 的 crontab 或 watchcat 来实现你的目的。

⒌ 真正地去了解一下  那些你认为会影响 dns 解析操作的 “插件” 使用说明。

——————————————————

### 总结：1、数据库更新这块没有更改的必要。2、在当前的 luci-app-mosdns 上实现 dnsmasq 上游的锁定、对其它插件进行的 iptables/nftables dns 端口重定向的解除，能实现，且简单，但目前不考虑，因为这种行为很流氓。（参考以上5点建议）


发自我的iPhone

**Comment by iamyangyiok** [comment]
> 一、通过mosdns luci / 定时更新数据库，只有两种结果： 更新成功：数据库文件被更新了。 更新失败：什么都没发生过。 脚本动作：https://github.com/sbwml/luci-app-mosdns/blob/v5/luci-app-mosdns/root/usr/share/mosdns/mosdns.sh#L90 所以不会存在因为 mosdns 数据库更新失败会导致别的插件异常，因为它什么都没动过（如果能看懂上面的脚本，就会明白一切）。 二、Dnsmasq 上游设定被其他插件抢占问题，几点有效建议： ⒈ 不要在 openwrt 上使用多个 dns 插件套娃。 ⒉ 把会影响 Dnsmasq 设定的插件直接设置上游为 mosdns 监听端口或 `127.0.0.1`。 ⒊ 如果你使用 mosdns 仅仅是为了配合科学插件工作，但是你又不知道如何去正确设置科学插件的 dns 上游为 mosdns。推荐使用 404 的版本，这个版本除了分流解析外，还支持一键设置科学插件的dns 上游到 mosdns （安装前，必须卸载当前luci-app-mosdns 和删除残留数据 `/etc/config/moadns`、`/etc/mosdns` ）项目地址：https://github.com/QiuSimons/openwrt-mos ⒋ 使用 OpenWrt 的 crontab 或 watchcat 来实现你的目的。 ⒌ 真正地去了解一下 那些你认为会影响 dns 解析操作的 “插件” 使用说明。 —————————————————— ### 总结：1、数据库更新这块没有更改的必要。2、在当前的 luci-app-mosdns 上实现 dnsmasq 上游的锁定、对其它插件进行的 iptables/nftables dns 端口重定向的解除，能实现，且简单，但目前不考虑，因为这种行为很流氓。（参考以上5点建议） 发自我的iPhone
> […](#)
> 在 2023年10月9日，13:41，iamyangyiok ***@***.***> 写道： ﻿ LUCI-APP-MOSDNS 1、更新广告规则、GeoIP & GeoSite 数据库能分开可选择性更新、因为国内直接更新GEODATA慢且经常不成功，且不知道是不是更新机制问题（推测：是否先删再更），现情况LUCI库更新失败的话，会影响PW的V2RAY分流（基于GEODTATA），导致科学中断无法访问。所以，我现在都不敢开LUCI的自动更新，且本身科学的APP也会自带GEODATA更新。所以，能分开更新项目，这样不会有冲突影响。 2、正因为有的科学更新或点网络配置重新设置，DNS转发有时会暂时失效和转发错误，导致DNS不可用。我想能否，有一个保护进程的功能，如轮询检测2-3个域名解析，如果不通，则重启MOSDNS服务应用，拿回DNS主导权。 以上是两点使用体会。再次表示感谢和支持。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.
 谢谢

> LUCI-APP-MOSDNS 1、更新广告规则、GeoIP & GeoSite 数据库能分开可选择性更新、因为国内直接更新GEODATA慢且经常不成功，且不知道是不是更新机制问题（推测：是否先删再更），现情况LUCI库更新失败的话，会影响PW的V2RAY分流（基于GEODTATA），导致科学中断无法访问。所以，我现在都不敢开LUCI的自动更新，且本身科学的APP也会自带GEODATA更新。所以，能分开更新项目，按需选择，这样不会有冲突影响。 2、正因为有的科学更新或点网络配置重新设置，DNS转发有时会暂时失效和转发错误，导致DNS不可用。我想能否，有一个保护进程的功能，如轮询检测2-3个域名解析，如果不通，则重启MOSDNS服务应用，拿回DNS主导权。
> 
> 以上是两点使用体会。再次表示感谢和支持。

谢谢 回复 更新选项的意思，是把广告规则和GEODATA，做成2个可选项，我只选广告规则更新就可以了。并不像现在要更新就要2者一起更新。

**Comment by sbwml** [comment]
你能做到的只有关闭 mosdns luci 的自动更新，在 OpenWrt “计划任务” 添加

```
0 4 * * * /usr/share/mosdns/mosdns.sh adlist_update
```

每天 04:00 更新一次广告规则。

**Comment by iamyangyiok** [comment]
> 你能做到的只有关闭 mosdns luci 的自动更新，在 OpenWrt “计划任务” 添加
> 
> ```
> 0 4 * * * /usr/share/mosdns/mosdns.sh adlist_update
> ```
> 
> 每天 04:00 更新一次广告规则。

收到
