### ISSUE TITLE
passwall默认屏蔽了udp端口中的quic转发，是否会影响使用doq类dns解析~

### ISSUE THREAD

**Issue by Pacio** [sbwml/luci-app-mosdns#145]
![屏幕截图 2023-10-09 144317](https://github.com/sbwml/luci-app-mosdns/assets/6836705/02c48c4f-c494-4cf2-8512-1c73db9d029e)

小白不懂，随便问问

**Comment by iamyangyiok** [comment]
不是TCP的吗？

**Comment by Pacio** [comment]
> 不是TCP的吗？

Doq和doh3本质都是udp协议，xd

**Comment by sbwml** [comment]
我不清楚，具体会不会影响你去 pw 官方仓库问问。

按我浅薄的认知猜的话，不管你怎么设置它，应该都不影响 mosdns 的 quic 、doh3 协议的使用，但仅限于“国内 DNS”。

“国外 DNS” 的话，应该是不能直接去使用 quic/doh3 的（除非你的国外 DNS 使用的是在国内自建的无污染DNS）

即使你拥有非常良好的 UDP 科学节点，并强制代理对应的 UDP 端口，我都不推荐你在mosdns 的 国外DNS 设置中直接使用 quic / h3。

## 这些都是猜的，不存在参考价值

发自我的iPhone

**Comment by Pacio** [comment]
> 我不清楚，具体会不会影响你去 pw 官方仓库问问。 按我浅薄的认知猜的话，不管你怎么设置它，应该都不影响 mosdns 的 quic 、doh3 协议的使用，但仅限于“国内 DNS”。 “国外 DNS” 的话，应该是不能直接去使用 quic/doh3 的（除非你的国外 DNS 使用的是在国内自建的无污染DNS） 即使你拥有非常良好的 UDP 科学节点，并强制代理对应的 UDP 端口，我都不推荐你在mosdns 的 国外DNS 设置中直接使用 quic / h3。 ## 这些都是猜的，不存在参考价值 发自我的iPhone
> […](#)
> 在 2023年10月9日，16:24，Pacio ***@***.***> 写道： ﻿ 不是TCP的吗？ Doq和doh3本质都是udp协议，xd — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.

国外我用的就是README.md推荐的“quic://dns.cooluc.com”，这个是自建的无污染dns吗？

**Comment by sbwml** [comment]
﻿dns.cooluc.com  个人自建的无污染 DNS，但是不保证可行性，如果被攻击就无法使用。所以使用需谨慎

发自我的iPhone
