### ISSUE TITLE
/var/mosdns/geoip_cn.txt国内IP不全

### ISSUE THREAD

**Issue by skill7899** [sbwml/luci-app-mosdns#147]
我在openclash中可以找到58.20开头是国内IP，但是在/var/mosdns/geoip_cn.txt找不到。因为tiptime-api.com分流失败了。

https://github.com/vernesong/OpenClash/blob/master/luci-app-openclash/root/etc/openclash/china_ip_route.ipset

**Comment by sbwml** [comment]
geoip 来自 https://github.com/Loyalsoldier/v2ray-rules-dat ，我没有自己维护这些数据库，所以没法干预到这些内容。你可以向 https://github.com/Loyalsoldier/v2ray-rules-dat 进行反馈，看看能不能完善国内的 cidr，如果上游完善了，mosdns 只需要更新一下数据库就可以用。
