### ISSUE TITLE
开启mosdns后谷歌商店无法更新app。

### ISSUE THREAD

**Issue by hpqqph** [sbwml/luci-app-mosdns#149]
内置设置，全默认。开启后过mosdns网关的设备无法更新或者下载谷歌商店的任何app，网页浏览则无问题。
googleapis.cn
googleapis.com
google.com.tw
google.com.hk
gstatic.com
xn--ngstr-lra8j.com
已加入灰名单。
如何解决？

**Comment by dsyo2008** [comment]
你应该是用passwall2分流？那是geosite问题，需要加入geosite:google够了，不用输太多了
因为geosite带cn，导致走国内吧

**Comment by hpqqph** [comment]
> 你应该是用passwall2分流？那是geosite问题，需要加入geosite:google够了，不用输太多了 因为geosite带cn，导致走国内吧

用的passwall，没用2，单独用passwall的时候是没问题的。意思是mosdns灰名单只需要加入geosite:google这条规则？萌新不是很懂，我试试。

**Comment by sbwml** [comment]
理论上默认配置应该什么规则都不用设置这些都正常的才对。你有没有打开了ad拦截之类的东西

**Comment by hpqqph** [comment]
> 理论上默认配置应该什么规则都不用设置这些都正常的才对。你有没有打开了ad拦截之类的东西

没有哦，除了passwall和mosdns之外啥都没开。节点也是同一个，单独使用passwall时候没问题。

**Comment by AmberisMyShiba** [comment]
> > 理论上默认配置应该什么规则都不用设置这些都正常的才对。你有没有打开了ad拦截之类的东西
> 
> 没有哦，除了passwall和mosdns之外啥都没开。节点也是同一个，单独使用passwall时候没问题。
可以参考helloworld里的这个[issue](https://github.com/fw876/helloworld/issues/1278#issuecomment-1793359274)

**Comment by hpqqph** [comment]
> > > 理论上默认配置应该什么规则都不用设置这些都正常的才对。你有没有打开了ad拦截之类的东西
> > 
> > 
> > 没有哦，除了passwall和mosdns之外啥都没开。节点也是同一个，单独使用passwall时候没问题。
> > 可以参考helloworld里的这个[issue](https://github.com/fw876/helloworld/issues/1278#issuecomment-1793359274)

我更新到v5.3.1版本又更新了规则，似乎解决了。谢谢。
