### ISSUE TITLE
最新版的mosdns编译进immwortalwrt21.02有部分出现英文是什么原因

### ISSUE THREAD

**Issue by lazyoop** [sbwml/luci-app-mosdns#150]

**Comment by sbwml** [comment]
语言文件没有安装 `luci-i18n-mosdns-zh-cn`

**Comment by lazyoop** [comment]
已经安装了luci-i18n-mosdns-zh-cn
![image](https://github.com/sbwml/luci-app-mosdns/assets/76811944/ab81e52d-e125-44c7-a8cb-917ab1ae17af)

**Comment by sbwml** [comment]
那就刷新浏览器缓存

**Comment by lazyoop** [comment]
还是不行。也无法启动，系统日志里还出现了 Wed Oct 25 21:51:45 2023 daemon.err uhttpd[4405]: sh: /usr/share/mosdns/mosdns.sh: Permission denied  这个问题

**Comment by sbwml** [comment]
按你发出来的东西来说的话，我不推荐你自己编译它。更推荐直接下载 ipk 文件安装 https://github.com/sbwml/luci-app-mosdns/releases

**Comment by lazyoop** [comment]
直接安装ipk正常了

**Comment by lazyoop** [comment]
我好像知道原因了，我是在win机器里搞的插件导致zh_Hans链接出现了问题
![image](https://github.com/sbwml/luci-app-mosdns/assets/76811944/fb5e4284-4d4d-4ab4-a4a5-a96e7784f42a)
放入linux后zh_Hans不再指向zh-cn文件
![image](https://github.com/sbwml/luci-app-mosdns/assets/76811944/a0c3085f-8d08-4f64-b9b8-423a03524508)
