### ISSUE TITLE
如何更方便的更新sbwml的源码？

### ISSUE THREAD

**Issue by naoki66** [sbwml/luci-app-mosdns#153]
sbwml给出的编译指导方案是
`   # remove v2ray-geodata package from feeds (openwrt-22.03 & master)
rm -rf feeds/packages/net/v2ray-geodata

git clone https://github.com/sbwml/luci-app-mosdns -b v5 package/mosdns
git clone https://github.com/sbwml/v2ray-geodata package/v2ray-geodata  `

但是这个仅能一次性拉源，后面不是很方便的更新，我按常规方案在feeds.conf.default文件里添加

`  src-git luci_app_mosdns https://github.com/sbwml/luci-app-mosdns.git;v5`  

`  src-git v2ray_geodata  https://github.com/sbwml/v2ray-geodata.git`  

此方案整体随源码更新而更新，但是会有两个小错误，不知道应该如何修复

`  Create index file './feeds/v2ray_geodata.index'

`  /immortalwrt/feeds/v2ray_geodata.tmp/info/.files-packageinfo.mk:1: *** target pattern contains no '%'.  Stop.`  
`  Installing all packages from feed packages.`  
`  Overriding core package 'v2ray-geodata' with version from packages`  `  

` * pkg_hash_check_unresolved: cannot find dependency v2ray-geoip for luci-app-passwall`
` * pkg_hash_check_unresolved: cannot find dependency v2ray-geosite for luci-app-passwall`
` * pkg_hash_fetch_best_installation_candidate: Packages for luci-app-passwall found, but incompatible with the architectures configured`
` * opkg_install_cmd: Cannot install package luci-app-passwall.`
` * satisfy_dependencies_for: Cannot satisfy the following dependencies for luci-i18n-passwall-zh-cn:`
` *      v2ray-geoip`
` *      v2ray-geosite`
`
.files-packageinfo.mk文件和v2ray-geodata会被覆盖，但是官方源v2ray-geodata应该和sbwml内容一致吧？
期望哪位大佬能够出手帮忙修正下，谢谢

**Comment by lengfwong** [comment]
官方源v2ray-geodata地址不一致。
我是进到mosdns目录里git pull

**Comment by sbwml** [comment]
你可以移除 `git clone https://github.com/sbwml/v2ray-geodata package/v2ray-geodata`

为了更愉快的使用，我个人建议使用 https://github.com/sbwml/v2ray-geodata （源自 https://github.com/Loyalsoldier/v2ray-rules-dat，与原生 v2ray-data，它收录的内容更全面）

**Comment by sbwml** [comment]
如果你要使用标准方式添加到 feeds ，你只能使用openwrt feeds 自带的。其实也相差不大，怎么玩靠自己决定。

**Comment by naoki66** [comment]
> 如果你要使用标准方式添加到 feeds ，你只能使用openwrt feeds 自带的。其实也相差不大，怎么玩靠自己决定。

  /immortalwrt/feeds/v2ray_geodata.tmp/info/.files-packageinfo.mk:1: *** target pattern contains no '%'.  Stop.
这个错误是什么原因呢？

**Comment by sbwml** [comment]
包冲突

> 如果你要使用标准方式添加到 feeds ，你只能使用openwrt feeds 自带的。

**Comment by sbwml** [comment]
意思是，你只需要第一行 
![image](https://github.com/sbwml/luci-app-mosdns/assets/16485166/cb048057-43a7-4965-8293-1ba0659f26e5)

**Comment by naoki66** [comment]
> 意思是，你只需要第一行 ![image](https://user-images.githubusercontent.com/16485166/280032838-cb048057-43a7-4965-8293-1ba0659f26e5.png)
rm -rf feeds/packages/net/v2ray-geodata 已经剔除了，也不会报告Overriding core package 'v2ray-geodata' with version from packages，但是v2ray_geodata.tmp/info/.files-packageinfo.mk依旧报错

**Comment by sbwml** [comment]
测试未复现
```bash
git clone https://github.com/openwrt/openwrt -b openwrt-23.05 --depth=1

cd openwrt

echo 'src-git mosdns https://github.com/sbwml/luci-app-mosdns.git;v5' >> feeds.conf.default

./scripts/feeds update -a

./scripts/feeds install -a

```

Logs
```
...
Installing package 'siproxd' from telephony
Installing package 'sngrep' from telephony
Installing package 'yate' from telephony
Installing all packages from feed mosdns.
Installing package 'luci-app-mosdns' from mosdns
Installing package 'mosdns' from mosdns
Installing package 'v2dat' from mosdns
[sbwml@redhat openwrt]$
```

---------------

考虑你源码缓存问题。
