### ISSUE TITLE
请教个问题，比如广告规则是否也像调用程序一样调用后长驻在内存中了。

### ISSUE THREAD

**Issue by iamyangyiok** [sbwml/luci-app-mosdns#154]
请教个问题，比如广告规则是否也像调用程序一样调用后长驻在内存中了。MOSDNS启动后是长驻内存的，但不清楚规则(包括GEODATA)这些是不是呢。，如果不是，我是想把这些规则映射到内存上，特请教下，谢谢。

**Comment by sbwml** [comment]
所有规则都会加载到内存

发自我的iPhone

**Comment by iamyangyiok** [comment]
> 所有规则都会加载到内存 发自我的iPhone
> […](#)
> 在 2023年11月2日，13:20，iamyangyiok ***@***.***> 写道： ﻿ 请教个问题，比如广告规则是否也像调用程序一样调用后长驻在内存中了。MOSDNS启动后是长驻内存的，但不清楚规则这些是不是呢。，如果不是如果不是，我是想把这些规则映射到内存上，特请教下，谢谢。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.

3Q 。 BIG BOSS
