### ISSUE TITLE
国内数据更新github加速貌似抽风了

### ISSUE THREAD

**Issue by 4thanks** [sbwml/luci-app-mosdns#156]
把ghproxy改gh-proxy，暂时没问题。

**Comment by sbwml** [comment]
这个有木有出处   如果是长期提供服务的可以考虑更换

**Comment by 4thanks** [comment]
油猴脚本更新时发现的 https://github.com/XIU2/UserScript/commit/1d9ad7212354c33f57ecb123e800f1d2271c980a https://github.com/XIU2/UserScript/commit/a5f74329bc6a13b7970774bc668635873b165daf

**Comment by sbwml** [comment]
已支持 gh 的设置或禁用：https://github.com/sbwml/luci-app-mosdns/commit/3232ed6b4649596b7ea675eebbf231c48837abfc
