### ISSUE TITLE
github.com可以上，但“更新广告规则、GeoIP & GeoSite 数据库” 检查并更新却总失败

### ISSUE THREAD

**Issue by Mrican** [sbwml/luci-app-mosdns#158]
想请教一个问题：

github.com可以上，但“更新广告规则、GeoIP & GeoSite 数据库” 检查并更新却总失败，提示：更新失败，请检查网络状态。

刚试过重置固件，没有任何科学插件，只安装luci-app-mosdns，马上就尝试，还是失败，不懂

直接在浏览器下载是可以的

https://github.com/Loyalsoldier/geoip/releases/latest/download/geoip-only-cn-private.dat

看到这

google_status=$(curl -I -4 -m 3 -o /dev/null -s -w %{http_code} http://www.google.com/generate_204)
    [ "$google_status" -ne "204" ] && mirror="https://ghproxy.com/"

估计是因为  https://ghproxy.com   抽风了

**Comment by Mrican** [comment]
google_status=$(curl -I -4 -m 3 -o /dev/null -s -w %{http_code} http://www.google.com/generate_204)
[ "$google_status" -ne "204" ] && mirror="https://ghproxy.com/"

删除了这两行，更新成功了

**Comment by sbwml** [comment]
ghproxy 加速的问题。主要是如果在不开科学的时候，很多地区 githuh raw 链接无法访问，所以才加了 ghproxy ，但是最近这玩意抽风，也暂时找不到合适的替代品。或者我考虑给他添加设置项让用户自己选择是否使用ghproxy 。

发自我的iPhone

**Comment by naoki66** [comment]
> ghproxy 加速的问题。主要是如果在不开科学的时候，很多地区 githuh raw 链接无法访问，所以才加了 ghproxy ，但是最近这玩意抽风，也暂时找不到合适的替代品。或者我考虑给他添加设置项让用户自己选择是否使用ghproxy 。 发自我的iPhone
> […](#)
> 在 2023年11月5日，16:42，Mrican ***@***.***> 写道： ﻿ Closed #158 as completed. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.

是的，我也是加了梯子也不行

**Comment by Mrican** [comment]
> ghproxy 加速的问题。主要是如果在不开科学的时候，很多地区 githuh raw 链接无法访问，所以才加了 ghproxy ，但是最近这玩意抽风，也暂时找不到合适的替代品。或者我考虑给他添加设置项让用户自己选择是否使用ghproxy 。 发自我的iPhone
> […](#)
> 在 2023年11月5日，16:42，Mrican ***@***.***> 写道： ﻿ Closed #158 as completed. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.

没有科学，上github不太稳定，改为"https://gh-proxy.com/"确实可以

交由用户来选择是否使用加速是好办法

**Comment by sbwml** [comment]
已支持 gh 的设置或禁用：https://github.com/sbwml/luci-app-mosdns/commit/3232ed6b4649596b7ea675eebbf231c48837abfc

**Comment by Mrican** [comment]
> 已支持 gh 的设置或禁用：[3232ed6](https://github.com/sbwml/luci-app-mosdns/commit/3232ed6b4649596b7ea675eebbf231c48837abfc)

有ipk吗？  不会编译。。。

**Comment by sbwml** [comment]
目前没有。

从 Windows 版邮件发送

发件人: Mrican
发送时间: 2023年11月5日 20:13
收件人: sbwml/luci-app-mosdns
抄送: Bard; Comment
主题: Re: [sbwml/luci-app-mosdns] github.com可以上，但“更新广告规则、GeoIP & GeoSite 数据库” 检查并更新却总失败 (Issue #158)

已支持 gh 的设置或禁用：3232ed6
有ipk吗？ 不会编译。。。

**Comment by Mrican** [comment]
> 目前没有。 从 Windows 版邮件发送 发件人: Mrican 发送时间: 2023年11月5日 20:13 收件人: sbwml/luci-app-mosdns 抄送: Bard; Comment 主题: Re: [sbwml/luci-app-mosdns] github.com可以上，但“更新广告规则、GeoIP & GeoSite 数据库” 检查并更新却总失败 (Issue #158) 已支持 gh 的设置或禁用：3232ed6 有ipk吗？ 不会编译。。。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***>

上游更新v5.3.1，可以同步编译了
