### ISSUE TITLE
昨天手动取消了DNS转发模式，直接用MOSDNS 53端口代替了DNSMASQ。

### ISSUE THREAD

**Issue by iamyangyiok** [sbwml/luci-app-mosdns#160]
昨天手动取消了DNS转发模式，直接用MOSDNS 53端口代替了DNSMASQ工作，似乎更流畅一些。但是去广告就不灵了，不知道什么原因?
BIG BOSS是否下一版，考虑能加个DNS代理模式选择呢，（上游模式、转发模式、直接53代替），感谢你的付出，我们才方便使用。

**Comment by iamyangyiok** [comment]
更新：看了下解析是有IPV6 AAA地址的，可以是这个原因，广告去不了。

**Comment by iamyangyiok** [comment]
更新：看了下解析是有IPV6 AAA地址的，可以是这个原因，广告去不了。MOSDNS 好像筛选不了 AAA地址吧

**Comment by iamyangyiok** [comment]
更新：看了下解析是有IPV6 AAA地址的，可以是这个原因，广告去不了。

**Comment by sbwml** [comment]
你可能需要的是  adguardhome 而不是 mosdns，如果我没有记错，同为民间制作的 adg luci 带有通过防火墙劫持 53 端口功能。

但是这个 mosdns luci 应该是不可能进行端口劫持或破坏 dnsmasq 这些操作的。（当然，如果你真的认为这是有意义的，可以自己魔改也不难。）
