### ISSUE TITLE
希望远程服务器组可以选择是否开启prefer_ipv4/6

### ISSUE THREAD

**Issue by buzidjy** [sbwml/luci-app-mosdns#161]
如题，目前的内置配置是强制开启的。而且删除了config.yaml内- exec: prefer_ipv4后无作用，重启后会自动加上。不知为何我的openwrt使用config_custom.yaml无法启动。因为我有些PT站点DNS容易被污染因此选择远程DNS，而且ipv4无法直连，只能通过ipv6直连这样强制- exec: prefer_ipv4后无法解析到IPV6地址就没法用了。

**Comment by lengfwong** [comment]
如果能看懂配置还是custom，可以自定义各种场景。无法启动的原因，如果log,没内容或者在某一步插件停止，大多是拼写或者缩进不对。推荐用sublime编辑。

**Comment by sbwml** [comment]
你没法直接拷贝默认配置到自定义配置中使用。因为使用的数据文件会缺失。

发自我的iPhone

**Comment by sbwml** [comment]
https://github.com/sbwml/luci-app-mosdns/commit/fe07d20493a20c3a2977195d0b50e5e9c7ba62d4

**Comment by buzidjy** [comment]
> 你不能直接复制默认配置到自定义配置中使用。因为使用的数据文件会丢失。 开发自我的iPhone
> [……](#)
> 在 2023 年 11 月 6 日，23:52，buzidjy ***@***.***> 写道： ﻿如题，目前的内置配置是强制开启的。并且删除了 config.yaml 内- exec: Preferred_ipv4后无作用，重启后会自动加上。不知道为什么我的openwrt使用config_custom.yaml无法启动。因为我有些PT站点DNS很容易被污染所以选择远程DNS，而且ipv4无法直连，只能通过ipv6直连这样强制- exec: Preferred_ipv4后无法解析到IPV6地址就没法用了。 — 直接回复此邮件，在GitHub上查看，或取消订阅。您收到此消息是因为您订阅了该主题。

嗯，研究一下custom。

**Comment by qingtian110** [comment]
> [fe07d20](https://github.com/sbwml/luci-app-mosdns/commit/fe07d20493a20c3a2977195d0b50e5e9c7ba62d4)

。。。又是一个破坏性功能请求。

加这个选项在这里非常影响操作。原本基础设置，就纯dns 的设置，页面都不用下拉，加了这个选项进来，事情变得复杂了。

建议移除掉它，因为每个人的需求都不一样的，默认配置模式他应该是普普通通的 dns 客户端模式。那些需要奇奇怪怪需求的，那就去用自定义配置模式，不要去破坏掉默认配置模式的便捷。

![image](https://github.com/sbwml/luci-app-mosdns/assets/87856890/8571e236-a69d-4f36-8051-3ac1e54b94ad)

**Comment by qingtian110** [comment]
一人一个需求往里加的话，这个插件永远不会完善，也绝对会变得臃肿。。。

**Comment by buzidjy** [comment]
> 一人一个需求往里加的话，这个插件永远不会完善，也绝对会变得臃肿。。。

我觉得需要远程IPV6的应该是正常需求吧，之前的默认配置走远程双栈会完全屏蔽IPV6。如果除了添加DNS服务器的操作外都算臃肿的话，那应该把端口设置删除强制劫持53，日志等级强制info，自定义国内DNS强制开启，apple域名优化删除。界面可操作的内容仅仅添加上游。这样几乎无自定义功能的插件不知道算不算完善了！！

**Comment by buzidjy** [comment]
> [fe07d20](https://github.com/sbwml/luci-app-mosdns/commit/fe07d20493a20c3a2977195d0b50e5e9c7ba62d4)

感谢大佬的付出！昨天听取了[lengfwang](https://github.com/lengfwang)这位朋友的建议，研究了一整天mosdns的wiki大致了解了工作流程与语法，目前自定义配置已经可以正常运行。我是有一些皮毛的编程基础的，感觉对完全不懂代码的人来说想用自定义还是比较困难的。这个插件让mosdns变得很易用，普通人也可以轻松上手。祝愿此插件越来越好，再次感谢作者！
