### ISSUE TITLE
V5.3.1 数据库更新失败，提示“请检查网络状态

### ISSUE THREAD

**Issue by landyxin** [sbwml/luci-app-mosdns#162]
mosdns 版本
V5.3.1

操作系统
x86-64

Bug 描述和复现步骤
mosdns更新数据库失败，提示“检查网络状态”
但是网络环境没什么问题，可以翻墙，也可以正常上内网，什么原因？

![image](https://github.com/sbwml/luci-app-mosdns/assets/15067842/5c837831-1837-4317-9c44-47ee4611839e)
![image](https://github.com/sbwml/luci-app-mosdns/assets/15067842/dbf6c64e-e684-4ebd-ae75-4672ee6c5367)

**Comment by landyxin** [comment]
重新更新，界面有些变化，但是还是提示更新失败
<img width="836" alt="image" src="https://github.com/sbwml/luci-app-mosdns/assets/15067842/ab24bddb-4465-4e1b-a154-ac7f64141f04">

**Comment by landyxin** [comment]
openclash内核日志
<img width="1275" alt="image" src="https://github.com/sbwml/luci-app-mosdns/assets/15067842/faafdabf-45fe-4c89-9b0b-4fd2faef6245">

**Comment by Mrican** [comment]
https://github.com/sbwml/luci-app-mosdns/issues/158

**Comment by sbwml** [comment]
`/usr/share/mosdns/mosdns.sh geodata` 命令会告诉你失败的原因

**Comment by MIT-X** [comment]
> mosdns 版本 V5.3.1
> 
> 操作系统 x86-64
> 
> Bug 描述和复现步骤 mosdns更新数据库失败，提示“检查网络状态” 但是网络环境没什么问题，可以翻墙，也可以正常上内网，什么原因？
> 
> ![image](https://private-user-images.githubusercontent.com/15067842/281132470-5c837831-1837-4317-9c44-47ee4611839e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDA5MzUyMDAsIm5iZiI6MTcwMDkzNDkwMCwicGF0aCI6Ii8xNTA2Nzg0Mi8yODExMzI0NzAtNWM4Mzc4MzEtMTgzNy00MzE3LTljNDQtNDdlZTQ2MTE4MzllLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI1VDE3NTUwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM4M2E3MWEzYmVmYmM3ZTUxZDU5OWFhYmZkNzQyZTg5OWYwYWY4MTBlMzhhYTVhMTliNzExNzQ0YzY1OWVlOTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.MBZU156bEUPFkFt5Iu2KgG4KiIA2l0CaKql4skbpkb4) ![image](https://private-user-images.githubusercontent.com/15067842/281132516-dbf6c64e-e684-4ebd-ae75-4672ee6c5367.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDA5MzUyMDAsIm5iZiI6MTcwMDkzNDkwMCwicGF0aCI6Ii8xNTA2Nzg0Mi8yODExMzI1MTYtZGJmNmM2NGUtZTY4NC00ZWJkLWFlNzUtNDY3MmVlNmM1MzY3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI1VDE3NTUwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAwZTMzZTVmMDI0ZTEwYzg0ZTNkZmM0NDRhZWJhMWU4NjYzNjUwZWNjOGY1ODlmMjUxMzYwOTI0ZmFkM2RiMjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.b2NsWpd5Qt-0P3DzifCFeojgLuSgHDVAeBpyQiNri1I)

三方代理加速地址 蹦了！ 禁用代理加速，重启一次系统，就正常了

**Comment by 13311031900** [comment]
root@iStoreOS:~# /usr/share/mosdns/mosdns.sh geodata
Downloading https://github.com/Loyalsoldier/v2ray-rules-dat/https://github.com/Loyalsoldier/geoip/releases/latest/download/geoip-only-cn-private.dat
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     9    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
curl: (22) The requested URL returned error: 404

**Comment by 13311031900** [comment]
请问下这个下载的命令行如何修改下载地址

**Comment by 13311031900** [comment]
root@iStoreOS:~# /usr/share/mosdns/mosdns.sh geodata
Downloading https://gh-proxy.com/https://github.com/Loyalsoldier/geoip/releases/latest/download/geoip-only-cn-private.dat
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (35) OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to gh-proxy.com:443 
root@iStoreOS:~# /usr/share/mosdns/mosdns.sh geodata
Downloading https://ghps.cc/https://github.com/Loyalsoldier/geoip/releases/latest/download/geoip-only-cn-private.dat
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
curl: (35) OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to ghps.cc:443

**Comment by sbwml** [comment]
卸了吧    不维护了
