### ISSUE TITLE
无法通过后台修改/etc/mosdns/config.yaml

### ISSUE THREAD

**Issue by Alex-Joe-Lee** [sbwml/luci-app-mosdns#166]
ssh登录到后台修改config.yaml后，重启mosdns，config.yaml又变成跟前台一致了

**Comment by lengfwong** [comment]
config.yaml是通过luci页面配置生成的，如果想自定义配置，需要修改生成config_custom.yaml，并且在luci页面选择自定义配置

**Comment by sbwml** [comment]
楼上正解

**Comment by sbwml** [comment]
配置文件选择自定义，你可以直接编辑你自己的配置。但是配置文件的问题就不要在这里问（永远得不到答案）




发自我的iPhone
