### ISSUE TITLE
openwrt 本地无法解析国外域名

### ISSUE THREAD

**Issue by just-test-code** [sbwml/luci-app-mosdns#167]
运行环境是:adg 替换53端口,上游设置为modns
openwrt安装后无法解析国外域名

具体表现为 openwrt 无法解析国外IP,但是客户端windows却是正常的,就是安装modns的openwrt无法解析国外域名,国内域名都是正常

**Comment by just-test-code** [comment]
已解决,本地可能是DNS缓存, 查看日志发现上游tls://8.8.8.8 被阻断

**Comment by jingmian** [comment]
> 已解决,本地可能是DNS缓存, 查看日志发现上游tls://8.8.8.8 被阻断

后来你是怎么解决，我也存在这个问题
