### ISSUE TITLE
日志有错误信息提示无法写入缓存？

### ISSUE THREAD

**Issue by asnon** [sbwml/luci-app-mosdns#168]
![{4933CFBA-865A-4238-A352-6643DDF82D1A}](https://github.com/sbwml/luci-app-mosdns/assets/34601728/42662298-3f17-4bec-bd25-2275a170fd6a)
好像是个别网页会这样？请问有影响么？
最近版本感觉有时候个别国内支付或者头条等app会卡顿，5.1.x版本好像不会呢

**Comment by dwbii** [comment]
你试试 自定义国内dns
