### ISSUE TITLE
希望在UI界面增加本地DNS的设置，谢谢

### ISSUE THREAD

**Issue by xuesumin** [sbwml/luci-app-mosdns#17]
由于本地运营商存在干扰和污染，能否在默认配置UI界面上增加本地DNS设置的选项，谢谢！

**Comment by sbwml** [comment]
本地dns使用的是WAN口 dns，不想使用运营商dns的话   可以去wan口自定义dns地址 ，完后重启mosdns他就会变成你自定义后的dns地址了

**Comment by xuesumin** [comment]
明白了！谢谢！

**Comment by nantayo** [comment]
> 本地dns使用的是WAN口 dns，不想使用运营商dns的话 可以去wan口自定义dns地址 ，完后重启mosdns他就会变成你自定义后的dns地址了

借地问一下，我用单网口设备做的透明网桥，只有一个LAN口而没有WAN口，我看到内置配置是只用了一个119.29.29.29。这样除了用custom配置以外，还有办法加多本地DNS吗？

**Comment by sbwml** [comment]
> > 本地dns使用的是WAN口 dns，不想使用运营商dns的话 可以去wan口自定义dns地址 ，完后重启mosdns他就会变成你自定义后的dns地址了
> 
> 借地问一下，我用单网口设备做的透明网桥，只有一个LAN口而没有WAN口，我看到内置配置是只用了一个119.29.29.29。这样除了用custom配置以外，还有办法加多本地DNS吗？

https://github.com/sbwml/luci-app-mosdns/blob/master/luci-app-mosdns/root/usr/share/mosdns/mosdns.sh#L23

你可以改这个文件

**Comment by nantayo** [comment]
> > > 本地dns使用的是WAN口 dns，不想使用运营商dns的话 可以去wan口自定义dns地址 ，完后重启mosdns他就会变成你自定义后的dns地址了
> > 
> > 
> > 借地问一下，我用单网口设备做的透明网桥，只有一个LAN口而没有WAN口，我看到内置配置是只用了一个119.29.29.29。这样除了用custom配置以外，还有办法加多本地DNS吗？
> 
> https://github.com/sbwml/luci-app-mosdns/blob/master/luci-app-mosdns/root/usr/share/mosdns/mosdns.sh#L23
> 
> 你可以改这个文件

非常感谢，解决了
