### ISSUE TITLE
编译失败 go.1.2

### ISSUE THREAD

**Issue by vi-si** [sbwml/luci-app-mosdns#170]
Building targets
github.com/quic-go/quic-go/internal/qtls
# github.com/quic-go/quic-go/internal/qtls
../../../../../dl/go-mod-cache/github.com/quic-go/quic-go@v0.40.0/internal/qtls/go_oldversion.go:5:13: cannot use "The version of quic-go you're using can't be built using outdated Go versions. For more details, please see https://github.com/quic-go/quic-go/wiki/quic-go-and-Go-versions." (untyped string constant "The version of quic-go you're using can't be built using outdated Go...) as int value in variable declaration
note: module requires Go 1.20
github.com/IrineSistiana/mosdns/v5/pkg/utils
# github.com/IrineSistiana/mosdns/v5/pkg/utils
../../pkg/utils/strings.go:29:16: undefined: unsafe.String
../../pkg/utils/strings.go:29:30: undefined: unsafe.SliceData
note: module requires Go 1.20
github.com/IrineSistiana/mosdns/v5/pkg/upstream/bootstrap
# github.com/IrineSistiana/mosdns/v5/pkg/upstream/bootstrap
../../pkg/upstream/bootstrap/bootstrap.go:93:22: undefined: context.Cause
../../pkg/upstream/bootstrap/bootstrap.go:205:35: undefined: context.Cause
note: module requires Go 1.20

应该是GO 1.20出错

请问有用 https://github.com/hanwckf/immortalwrt-mt798x 编译成功的吗

**Comment by sbwml** [comment]
![image](https://github.com/sbwml/luci-app-mosdns/assets/16485166/75e8719c-1a3c-4d5a-8d02-4eb7064e2c2b)

**Comment by uvswifft** [comment]
其实吧，官方的openwrt22用的还是go1.19
