### ISSUE TITLE
更新广告规则和geo数据库问题

### ISSUE THREAD

**Issue by JIZHENQIANG** [sbwml/luci-app-mosdns#171]
**1.显示检查更新报错，但更新成功。**
描述：启用 DNS 广告过滤，但是只选添加默认geosite规则，不添加其他规则。检查更新报错，并且在tmp目录下会保留mktemp命令生成的临时目录。
疑似问题：mosdns.sh脚本的adlist_update方法判断问题，当只有geosite规则时has_update不会变化，所以不会删除创建的临时目录并导致返回结果错误，实际是更新正常的，但是/tmp会多出空目录。
**2.显示检查更新成功，但更新失败。**
描述：启用 DNS 广告过滤，选择多条规则。检查更新成功，rule/adlist目录被刷新，但文件大小变为0即没有任何规则。
疑似问题：curl命令如果遇到问题，如【curl: (60) SSL certificate problem: self signed certificate】不会影响执行，依然会修改has_update为1，导致返回结果正常，但并没有更新而且已有的规则会被空文件覆盖。
**_期望插件越来越好用！_**

**Comment by sbwml** [comment]
请提供一点点线索

```sh
sh -x /usr/share/mosdns/mosdns.sh geodata
```

**Comment by sbwml** [comment]
https://github.com/sbwml/luci-app-mosdns/commit/0e459f535d85fca21f14c924fd00056a402aea9d

**Comment by JIZHENQIANG** [comment]
+ adlist_update
+ uci -q get mosdns.config.adblock
+ '[' 1 '!=' 1 ]
+ uci -q get mosdns.config.ad_source
+ ad_source=geosite.dat
+ mktemp -d
+ AD_TMPDIR=/tmp/tmp.FMLkgP
+ mirror=
+ :
+ has_update=0
+ '[' geosite.dat '!=' geosite.dat ]
+ '[' 0 -ne 0 ]
+ '[' 0 -eq 1 ]
这是第一个问题的。

第二个问题无法复现，现在没有问题更新正常。
也许是raw.githubusercontent.com更新了证书信息，之前会有【self signed certificate】证书自签名的问题，这个问题是在openclash上发现的，openclash更新域名文件也会报错，现在也正常了

**Comment by JIZHENQIANG** [comment]
![image](https://github.com/sbwml/luci-app-mosdns/assets/49663620/aff00dd3-beb5-4906-b5ad-7ac32b50209a)
第一个问题将84行：rm -rf "$AD_TMPDIR"下移一行，即脱离代码块移动至else中貌似能解决问题
![image](https://github.com/sbwml/luci-app-mosdns/assets/49663620/5be58248-80a7-4320-a513-d8483b532d26)

**Comment by sbwml** [comment]
https://github.com/sbwml/luci-app-mosdns/commit/ed09f893acbe791b114e615bbb62d4006680b7d3
