### ISSUE TITLE
可以加入自定义数据库列表？

### ISSUE THREAD

**Issue by Potterli20** [sbwml/luci-app-mosdns#173]
可以加入自定义数据库列表？

**Comment by Potterli20** [comment]
也可不可以多加一个DNS 转发
专门的apple数据库列表用

**Comment by sbwml** [comment]
自定义配置 下这些实现起来非常简单。内置预设 没法做，因为 mosdns 存在无限种可能性，靠预设配置是不可能完成所有需求的。

至于数据库列表，自定义配置只需要定义你自己的列表文件绝对路径就可用。内置预设也同样能通过规则列表的黑、白、灰 以不冲突的方式去编辑你自己的列表。

发自我的iPhone

**Comment by Potterli20** [comment]
> 自定义配置 下这些实现起来非常简单。内置预设 没法做，因为 mosdns 存在无限种可能性，靠预设配置是不可能完成所有需求的。 至于数据库列表，自定义配置只需要定义你自己的列表文件绝对路径就可用。内置预设也同样能通过规则列表的黑、白、灰 以不冲突的方式去编辑你自己的列表。 发自我的iPhone
> […](#)
> 在 2023年11月19日，11:02，trli ***@***.***> 写道： ﻿ 也可不可以多加一个DNS 转发 专门的apple数据库列表用 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.

这样我看看如何玩
