### ISSUE TITLE
请教一下可以用openwrt官方的v2ray-geoip和v2ray-geosite吗？

### ISSUE THREAD

**Issue by dwbii** [sbwml/luci-app-mosdns#174]
请教一下可以用openwrt官方的v2ray-geoip和v2ray-geosite吗？
我看这大小有点区别，不知能不能用
![屏幕截图 2023-12-11 165650](https://github.com/sbwml/luci-app-mosdns/assets/18597768/f3685297-7d40-4834-ab4d-6090855bf4f9)

**Comment by sbwml** [comment]
随便

发自我的iPhone
