### ISSUE TITLE
5.3.1版本使用预设配置未配置114dns 配置文件却出现114dns问题

### ISSUE THREAD

**Issue by cutbuzz** [sbwml/luci-app-mosdns#175]
目前使用5.3.1版本，并配合oc使用。
配置中并未配置114dns，查看config配置文件出现114dns问题的请教，请问如何修改或删除这部分？（因为地区问题114巨慢无比）
或者说这配置是什么时候才会被用到？谢谢大佬解答
![image](https://github.com/sbwml/luci-app-mosdns/assets/84438684/a376f29f-330e-4f00-a583-b898b3080097)
配置：
![image](https://github.com/sbwml/luci-app-mosdns/assets/84438684/15e7ec0a-8c7d-40ec-825c-bf95d4533174)

**Comment by sbwml** [comment]
关闭 
![image](https://github.com/sbwml/luci-app-mosdns/assets/16485166/0f08c8b5-2145-4bc5-8ecb-9825c9b1d648)

**Comment by cutbuzz** [comment]
> 关闭 ![image](https://private-user-images.githubusercontent.com/16485166/290251210-0f08c8b5-2145-4bc5-8ecb-9825c9b1d648.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI0ODcyODIsIm5iZiI6MTcwMjQ4Njk4MiwicGF0aCI6Ii8xNjQ4NTE2Ni8yOTAyNTEyMTAtMGYwOGM4YjUtMjE0NS00YmM1LThlY2ItOTgyNWM5YjFkNjQ4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjEzVDE3MDMwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQzNmI3NTFjNDU1MWEzNDc4ZWQ5ZTRhMzkxYWMwMTdhMmU3YTU5ZGI4ZmYyYTdhMDkxMzBiYzNkMTUwNWVjMTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.CT0-pW1wSplpQb6NbTqqu3jVPso1KF3O5nWNM2sG-t0)

请问是否支持自定义修改这个功能所配置的dns，因为这功能确实挺好用的不想舍弃~
(并且关闭这个功能配置文件并没有变化~ 114依然存在~)

**Comment by sbwml** [comment]
关闭Apple 优化，配置里面的 114 dns 就永远不会被使用。

它没有自定义的必要，因为关闭Apple优化后国内dns设置完全取代它

发自我的iPhone

**Comment by cutbuzz** [comment]
> 关闭Apple 优化，配置里面的 114 dns 就永远不会被使用。 它没有自定义的必要，因为关闭Apple优化后国内dns设置完全取代它 发自我的iPhone
> […](#)
> 在 2023年12月14日，01:04，cutbuzz ***@***.***> 写道： ﻿ 关闭 请问是否支持自定义修改这个功能所配置的dns，因为这功能确实挺好用的不想舍弃~ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.

谢谢大佬解答，我的意思是可否在开启Apple优化的同时自定义Apple优化所使用的dns？

**Comment by sbwml** [comment]
不能，另外如果非要去改它，那么Apple 回退策略就毫无意义（等同功能不存在）

发自我的iPhone

**Comment by xiaofat1995** [comment]
那个首选IPv4的按钮是怎么添加上的啊？大佬
