### ISSUE TITLE
请问可不可以加一个缓存预加载的功能?

### ISSUE THREAD

**Issue by biggbuddy** [sbwml/luci-app-mosdns#177]
已经提供了本地缓存, 但这个缓存有可能会过期 , 与期等到过期后重新再请求新的ip然后再放到缓存中, 能不能主动去做这件事, 快过期的时候, 就主动去更新快过期的缓存, 不要等用户的请求过来, 这样可以保证用户常用的域名都可以从缓存中取到. 貌似隔壁smartDNS有类似的"缓存预加载"功能. [https://pymumu.github.io/smartdns/config/cache/](https://pymumu.github.io/smartdns/config/cache/  )

还是说有什么原因所以不加这个功能吗? 可否分享一下, 学习学习

**Comment by sbwml** [comment]
反馈错地方了   找上游

**Comment by biggbuddy** [comment]
答案是:  https://github.com/kkkgo/PaoPaoDNS
非常不错的镜像
