### ISSUE TITLE
启动失败

### ISSUE THREAD

**Issue by LQ2002** [sbwml/luci-app-mosdns#179]
使用自定义配置时就提示
starting shutdown sequences
![S40103-00350141_com android chrome](https://github.com/sbwml/luci-app-mosdns/assets/50812010/5331503b-10b3-4429-8eb5-dc65a9ef74bb)
使用预设就可以启动成功

**Comment by sbwml** [comment]
这难道还不能证明你的配置是错误的？

**Comment by LQ2002** [comment]
另一台软路由又可以运行

**Comment by sbwml** [comment]
那就检查你的服务   你的端口

**Comment by LQ2002** [comment]
好
