### ISSUE TITLE
新版无法运行

### ISSUE THREAD

**Issue by starxu1971** [sbwml/luci-app-mosdns#18]
更新至新版之后就跑不起来了，可执行文件换成旧版也不能，系统是大雕的源代码。

**Comment by sbwml** [comment]
大调源码是哪个

```shell
/etc/init.d/mosdns restart
/etc/init.d/mosdns stop
/usr/bin/mosdns start -c /etc/mosdns/config.yaml
```
执行这个看看显示什么？

**Comment by VwEl** [comment]
> 大调源码是哪个
> 
> ```shell
> /etc/init.d/mosdns restart
> /etc/init.d/mosdns stop
> /usr/bin/mosdns start -c /etc/mosdns/config.yaml
> ```
> 
> 执行这个看看显示什么？

Error: mosdns exited, failed to init plugin #11, failed to load data from provider geoip, proto: cannot parse invalid wire-format data
2022-10-12T13:37:54.499+0800    fatal   v4/main.go:48   mosdns exited, failed to init plugin #11, failed to load data from provider geoip, proto: cannot parse invalid wire-format data
