### ISSUE TITLE
passwall设置转发后导致功能失效

### ISSUE THREAD

**Issue by likaia** [sbwml/luci-app-mosdns#180]
我的前置条件：
* passwall 4.71-2
* luci-app-mosdns v5.3.0

passwall设置通过udp请求dns至127.0.0.1:5335
<img width="917" alt="image" src="https://github.com/sbwml/luci-app-mosdns/assets/35120858/346d5635-3412-4688-91ec-7c3ccb8f7bfa">

mosdns使用的内置预设。
<img width="785" alt="image" src="https://github.com/sbwml/luci-app-mosdns/assets/35120858/cda395a4-5e11-445b-ae12-690ea0f10991">

**Comment by likaia** [comment]
passwall的日志也都显示正确设置了

<img width="1160" alt="image" src="https://github.com/sbwml/luci-app-mosdns/assets/35120858/f4a59d9b-a291-42c1-bd88-6bfd761e07d3">

**Comment by likaia** [comment]
我看了下mosdns 的日志，报错。

```bash
2024-01-08 02:14:50	WARN	forward_remote	upstream error	{"uqid": 6887, "qname": "www.google.com.", "qclass": 1, "qtype": 1, "upstream": "tls://1.1.1.1", "error": "EOF"}
2024-01-08 02:14:50	WARN	lazy_cache	failed to update lazy cache	{"query": {"uqid": 6887, "client": "::ffff:127.0.0.1", "qname": "www.google.com.", "qtype": 1, "qclass": 1, "elapsed": "1.006012371s"}, "error": "all upstream servers failed"}
```

<img width="1483" alt="image" src="https://github.com/sbwml/luci-app-mosdns/assets/35120858/b449a492-d2e4-402e-8fc5-6736ca42023b">

**Comment by xhy0728** [comment]
我的也这样，编译了次  都一样。网上也找不到答案，弃用了。

**Comment by xhy0728** [comment]
一旦出现这警告  nslookup测试 就解析不出ip

**Comment by likaia** [comment]
> 我的也这样，编译了次 都一样。网上也找不到答案，弃用了。

我也放弃了，改用openclash了。可以正常使用了，但是openclash的日志出现了mosdns的中的dns ip地址。😂

**Comment by likaia** [comment]
> > 我的也这样，编译了次 都一样。网上也找不到答案，弃用了。
> 
> 我也放弃了，改用openclash了。可以正常使用了，但是openclash的日志出现了mosdns的中的dns ip地址。😂

现在能想到的方案就是在openclash的配置文件写规则，把dns的ip给他拦截掉。

**Comment by RavenCage** [comment]
我也用passwall和passwall2，用mosdns设置5335转发，一切正常没有任何问题。估计你的固件有问题。
![001](https://github.com/sbwml/luci-app-mosdns/assets/126802578/030b69fd-dd39-4e3d-b43a-7eedeebde9a6)

**Comment by sbwml** [comment]
解决方案：

1、ssh
```bash
opkg remove mosdns v2dat
rm -rf /etc/mosdns
```

2、go to https://github.com/pymumu/smartdns/releases/tag/Release43

**Comment by likaia** [comment]
> 解决方案：
> 
> 1、ssh
> 
> ```shell
> opkg remove mosdns v2dat
> rm -rf /etc/mosdns
> ```
> 
> 2、go to https://github.com/pymumu/smartdns/releases/tag/Release43

移除包的时候报错
```bash
root@iStoreOS:~# opkg remove mosdns v2dat
No packages removed.
Collected errors:
 * print_dependents_warning: Package mosdns is depended upon by packages:
 * print_dependents_warning: 	luci-app-mosdns
 * print_dependents_warning: These might cease to work if package mosdns is removed.

 * print_dependents_warning: Force removal of this package with --force-depends.
 * print_dependents_warning: Force removal of this package and its dependents
 * print_dependents_warning: with --force-removal-of-dependent-packages.
 * print_dependents_warning: Package v2dat is depended upon by packages:
 * print_dependents_warning: 	luci-app-mosdns
 * print_dependents_warning: These might cease to work if package v2dat is removed.

 * print_dependents_warning: Force removal of this package with --force-depends.
 * print_dependents_warning: Force removal of this package and its dependents
 * print_dependents_warning: with --force-removal-of-dependent-packages.
```

**Comment by likaia** [comment]
> > 解决方案：
> > 1、ssh
> > ```shell
> > opkg remove mosdns v2dat
> > rm -rf /etc/mosdns
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 2、go to https://github.com/pymumu/smartdns/releases/tag/Release43
> 
> 移除包的时候报错
> 
> ```shell
> root@iStoreOS:~# opkg remove mosdns v2dat
> No packages removed.
> Collected errors:
>  * print_dependents_warning: Package mosdns is depended upon by packages:
>  * print_dependents_warning: 	luci-app-mosdns
>  * print_dependents_warning: These might cease to work if package mosdns is removed.
> 
>  * print_dependents_warning: Force removal of this package with --force-depends.
>  * print_dependents_warning: Force removal of this package and its dependents
>  * print_dependents_warning: with --force-removal-of-dependent-packages.
>  * print_dependents_warning: Package v2dat is depended upon by packages:
>  * print_dependents_warning: 	luci-app-mosdns
>  * print_dependents_warning: These might cease to work if package v2dat is removed.
> 
>  * print_dependents_warning: Force removal of this package with --force-depends.
>  * print_dependents_warning: Force removal of this package and its dependents
>  * print_dependents_warning: with --force-removal-of-dependent-packages.
> ```

我怀疑问题出在mosdns的`DNS转发`上，我如果不勾选它的转发，启动passwall就是正常的，可以正常出墙。
<img width="1075" alt="image" src="https://github.com/sbwml/luci-app-mosdns/assets/35120858/c2ef817b-482e-418b-a7bc-d7be1e944135">

<img width="1242" alt="image" src="https://github.com/sbwml/luci-app-mosdns/assets/35120858/7902e348-442f-48fb-931e-1591a6b61d3e">

**Comment by sbwml** [comment]
luci-app-mosdns 插件的问题。
