### ISSUE TITLE
最新版的mosdns，是否每次重启都要更新数据库（geoip和geosite）？

### ISSUE THREAD

**Issue by wzy105** [sbwml/luci-app-mosdns#183]
用的内置设置

重启后，不手动更新数据库，分流会出问题，很多域名都走远程了。
是因为数据库都保存在tmp的缘故？

有没有办法解决呢？

**Comment by sbwml** [comment]
没有办法解决，只能卸载弃用。

因为 mosdns 内置预设启动流程为：

1、v2dat 解压 `/usr/share/v2ray/geoip.dat & geosite.dat` 所需类别到 `/var/mosdns/` 目录。
2、init.d 根据 luci 设置生成 `/etc/mosdns/config.yaml` 包含 `/var/mosdns/` 数据列表的临时配置文件。
3、mosdns 程序以 `/etc/mosdns/config.yaml` 配置启动服务。

整个过程下来重启或不重启都不影响 mosdns 启动流程的正常进行，所以没有办法解决这种不符合逻辑的问题。

只能卸载 luci-app-mosdns、mosdns、v2dat 或 任何对 `/usr/share/v2ray` 目录有纂改操作的插件。二选一，前者较为简单。

**Comment by wzy105** [comment]
> 没有办法解决，只能卸载弃用。
> 
> 因为 mosdns 内置预设启动流程为：
> 
> 1、v2dat 解压 `/usr/share/v2ray/geoip.dat & geosite.dat` 所需类别到 `/var/mosdns/` 目录。 2、init.d 根据 luci 设置生成 `/etc/mosdns/config.yaml` 包含 `/var/mosdns/` 数据列表的临时配置文件。 3、mosdns 程序以 `/etc/mosdns/config.yaml` 配置启动服务。
> 
> 整个过程下来重启或不重启都不影响 mosdns 启动流程的正常进行，所以没有办法解决这种不符合逻辑的问题。
> 
> 只能卸载 luci-app-mosdns、mosdns、v2dat 或 任何对 `/usr/share/v2ray` 目录有纂改操作的插件。二选一，前者较为简单。

好的,谢谢sb老师的解答，受益匪浅

**Comment by wzy105** [comment]
> 没有办法解决，只能卸载弃用。
> 
> 因为 mosdns 内置预设启动流程为：
> 
> 1、v2dat 解压 `/usr/share/v2ray/geoip.dat & geosite.dat` 所需类别到 `/var/mosdns/` 目录。 2、init.d 根据 luci 设置生成 `/etc/mosdns/config.yaml` 包含 `/var/mosdns/` 数据列表的临时配置文件。 3、mosdns 程序以 `/etc/mosdns/config.yaml` 配置启动服务。
> 
> 整个过程下来重启或不重启都不影响 mosdns 启动流程的正常进行，所以没有办法解决这种不符合逻辑的问题。
> 
> 只能卸载 luci-app-mosdns、mosdns、v2dat 或 任何对 `/usr/share/v2ray` 目录有纂改操作的插件。二选一，前者较为简单。

好的,感谢s老师的解答，受益匪浅
