### ISSUE TITLE
install.sh 里的mirror似乎失效了

### ISSUE THREAD

**Issue by Mrican** [sbwml/luci-app-mosdns#187]
https://raw.githubusercontent.com/sbwml/luci-app-mosdns/v5/install.sh 

里的

if [ ! $google_status = "204" ];then
		mirror="https://github.cooluc.com/"
	fi

似乎失效了

**Comment by sbwml** [comment]
https://github.com/sbwml/luci-app-mosdns/commit/169ae0510ce5acde11898a656b09c04883d31986

好了

**Comment by Mrican** [comment]
thx
