### ISSUE TITLE
能够添加一个支持ipv6解析的选项

### ISSUE THREAD

**Issue by z499738316** [sbwml/luci-app-mosdns#188]
默认是ipv4解析，能否添加一个ipv6，现在是通过自定义配置文件，但是自定义规则的话就不生效了，能否支持一下，并且还有个问题，我用adg设置mosdns为上游，第一次查询dns特别慢，设置114等就正常的，不知道是不是我设置的问题还是本身就有这个问题

**Comment by sbwml** [comment]
我不知道你说的哪个ipv6。比如访问哪个域名没有解析出来v6地址？

查询速度问题，你应该把mosdns 国内、国外的dns 都设置成 114 再去看。如果你还是认为它很慢就去mosdns 官方仓库给作者反馈。
