### ISSUE TITLE
不勾选“启用DNS转发”，每次应用都会把Dnsmasq的DNS转发清空

### ISSUE THREAD

**Issue by RongMoM** [sbwml/luci-app-mosdns#19]
我Dnsmasq的DNS转发是用别的服务，所以不勾选mosdns的“启用DNS转发”，但是这样每次mosdns启动或应用都会把我Dnsmasq里设置的DNS转发清空，导致每次启动就要去重新填写，不知道能不能修改一下呢

**Comment by sbwml** [comment]
以我目前的水平，可能没法实现你这个需求，因为这和正常使用mosdns做上游dns的场景上会和你这个需求存在冲突。

但是你可以在自己的路由器上改变它。

编辑路由器这个文件 `/etc/init.d/mosdns` 删除第 129、137  行，使 dns 重定向还原功能失效  达到你想要的效果。

![QQ图片20220919220901](https://user-images.githubusercontent.com/16485166/191037542-2c94bf2c-361b-4764-ba6d-4f0384c559b1.png)

**Comment by edmondfr** [comment]
感谢大佬这么好用的插件，正好也有这个需求，按这个方法作修改目前运行正常。
