### ISSUE TITLE
DNS广告拦截好像有点问题

### ISSUE THREAD

**Issue by AoThen** [sbwml/luci-app-mosdns#191]
![image](https://github.com/sbwml/luci-app-mosdns/assets/32790381/a9856393-dfc9-4303-8029-0564ff707c41)
使用Cats-Team/AdRules列表,
打开文件,找过几家国内域名测试,
cat "/etc/mosdns/rule/adlist/mosdns_adrules.txt" |grep ".qq.com"
比如
ad.qq.com
commdata.v.qq.com
bkcommdata.v.qq.com

在屏蔽列表里有,却能正常打开....是不是只能拦截国外的.因为测试其他的倒是正常

配置是mosdns开劫持,openclash不劫持,DNS只填mosdns地址

**Comment by sbwml** [comment]
QQ 全系在白名单  https://github.com/sbwml/luci-app-mosdns/blob/v5/luci-app-mosdns/root/etc/mosdns/rule/whitelist.txt#L7

**Comment by sbwml** [comment]
白名单移除qq。com 会得到预期效果（正确使用到 MosDNS 的情况下）
![image](https://github.com/sbwml/luci-app-mosdns/assets/16485166/232d088a-1a0a-4fa7-800b-c4563acaec84)

**Comment by AoThen** [comment]
好的，十分感谢🫡
