### ISSUE TITLE
有需求低于1.20go版本的mosdns版本么

### ISSUE THREAD

**Issue by lmxslpc** [sbwml/luci-app-mosdns#192]
有低于1.20go版本的mosdns版本么

**Comment by sbwml** [comment]
没法兼容更老的 golang 版本，主要是 quic 库的缘故，没法把依赖版本降级。


如果是比较老的openwrt 源码建议参考readme 的操作升级golang

**Comment by lmxslpc** [comment]
我编译istoreos的源码 主要是他的很多包需要1.20以下的版本 也是quic 库的缘故 ,Thx anyway
