### ISSUE TITLE
关于安装问题

### ISSUE THREAD

**Issue by bncolin** [sbwml/luci-app-mosdns#194]
有个安装方面的问题不懂问一下
别的软件我知道可以从Releases下载打包好的ipk安装，大佬的这个有个安装脚本，我不懂命令，查询过大意应该是第一部分是拉取最新软件列表，第二部分是根据架构从软件源下载对应的ipk安装(如果没理解错的话)。
其中作者有句话“需要 golang 1.20.x 或最新版本（openwrt-21.02 及旧版本需要）”我的路由是21.02版本，a53架构，golang版本多少不知道，我应该用哪种安装方式，还是说2种其实都一样？

**Comment by sbwml** [comment]
安装curl、执行脚本。

善用浏览器翻译，避免看一些无关内容。
