### ISSUE TITLE
添加自定义广告规则本地文件后bootloop

### ISSUE THREAD

**Issue by Yuko1997** [sbwml/luci-app-mosdns#195]
添加本地文件路径，保存并应用，然后插件开始循环重启，日志一直在重复刷新load，看不出别的报错
![20240222162218](https://github.com/sbwml/luci-app-mosdns/assets/135049518/52a376c1-e81e-4d8e-9490-89c152bba92c)
[mosdns.log](https://github.com/sbwml/luci-app-mosdns/files/14370996/mosdns.log)
[config.yaml.json](https://github.com/sbwml/luci-app-mosdns/files/14371002/config.yaml.json)
视频[https://krakenfiles.com/view/ad1J34OOsw/file.html](url)

**Comment by sbwml** [comment]
luci 停止mosdns    用命令行启动看错误信息  /usr/bin/mosdns start -c /etc/mosdns/config.yaml

**Comment by Yuko1997** [comment]
> luci 停止mosdns 用命令行启动看错误信息 /usr/bin/mosdns start -c /etc/mosdns/config.yaml

没有什么信息，也没有发生循环，但是经测试所有广告过滤规则都失效了，包括自带的和本地文件
![20240222200022](https://github.com/sbwml/luci-app-mosdns/assets/135049518/f1b8ee2e-2318-49e8-bf80-decca00ff30b)
[mosdns.log](https://github.com/sbwml/luci-app-mosdns/files/14373585/mosdns.log)

**Comment by sbwml** [comment]
命令   netstat -tuln | grep 5335

看看 mosdns 监听端口有和现有程序冲突没

**Comment by sbwml** [comment]
还有个就是     你是添加了本地文件的ad 拦截列表后出现的无法启动？

**Comment by sbwml** [comment]
> 还有个就是 你是添加了本地文件的ad 拦截列表后出现的无法启动？

如果是这样的话，大可能性是你用的规则列表不是 mosdns 支持的规则格式。

**Comment by Yuko1997** [comment]
> 还有个就是 你是添加了本地文件的ad 拦截列表后出现的无法启动？

是这样的，删除了本地文件路径就一切正常，端口没有冲突
格式是纯域名列表，应该没错
![20240223001117](https://github.com/sbwml/luci-app-mosdns/assets/135049518/3f3023ab-e979-45a4-acfd-267f301e9c5c)

**Comment by sbwml** [comment]
把你的列表上传一份，有空我试试

**Comment by Yuko1997** [comment]
> 把你的列表上传一份，有空我试试

[domain.txt](https://github.com/sbwml/luci-app-mosdns/files/14376774/domain.txt)

**Comment by sbwml** [comment]
修复 https://github.com/sbwml/luci-app-mosdns/commit/0da873fbb9cee37c5264f1ca3f01eb6f11a657da
