### ISSUE TITLE
【新功能】请加一个配置项优化IPv6的分流

### ISSUE THREAD

**Issue by BI7PRK** [sbwml/luci-app-mosdns#196]
使用了分流代理时，本地开启IPv6网络环境下，会有以下情况，IPv4流量走了vps，但IPv6流量还是国内地址。
```
http://test-ipv6.com

- 你的公网 IPv4 地址是 [***VPS IP***]
- 你的公网 IPv6 地址是  [***国内IPv6地址***]
- 你已接入 IPv6，因此我们增加了一个标签页，显示你能否访问其他 IPv6 网站。[更多信息]
- 你已经有 IPv6 地址了，但你的浏览器不太愿意用，这一点比较令人担心。 [更多信息]
- 你的 DNS 服务器（可能由运营商提供）已经接入 IPv6 互联网了。
```
当关闭本地的IPv6时，流量成功导向vps，这时也显示了vps也有IPv6。那么是否加个选项， `forward_remote` 时，丢弃AAAA的解析。这样是否就能达到了期望呢？

**Comment by sbwml** [comment]
当你访问非ip协议检测网站时，访问国外网站 mosdns 会自动丢弃 ipv6 只保留 ipv4，只需要打开 “远程 DNS 首选 IPv4”  设置项。

**Comment by BI7PRK** [comment]
感谢大佬的回复，今夜又探索了一番，还是达不到预期。
+ nslookup 还是返回 IPv6

![图片](https://github.com/sbwml/luci-app-mosdns/assets/24989210/2433c49c-898c-4936-99a5-5e8527f23c38)

**Comment by sbwml** [comment]
就按你这个截图 raw.githubusercontent.com 的 DNS 应答来说，你应该好好设置下远程 DNS 地址

1、要么使用无污染 DNS
2、要么用你知道的任何办法让远程 DNS 地址走代理

你这是被污染，而不是v不v6的事情

发自我的iPhone

**Comment by BI7PRK** [comment]
经过大佬的提点，重置了整个系统。全新配置一遍。似乎已达到了期望结果
```CMD
# nslookup raw.githubusercontent.com
服务器:  UnKnown
Address:  240e:****:****:8710::1

非权威应答:
名称:    raw.githubusercontent.com
Addresses:  185.199.108.133
          185.199.109.133
          185.199.110.133
          185.199.111.133
```
