### ISSUE TITLE
运行成功之后,有没有什么方法验证是运行了呢?

### ISSUE THREAD

**Issue by mtvktvcn** [sbwml/luci-app-mosdns#20]
运行成功之后,有没有什么方法验证是运行了呢?
比如SMARTDNS 只返回一条解析
这个插件应该如何验证.

**Comment by sbwml** [comment]
我不知道。或许可能通过查看debug日志或自定义一条规则来判断mosdns有没有工作

**Comment by mtvktvcn** [comment]
感谢兄弟回复.
