### ISSUE TITLE
不知道是新PW 4.75的问题，还是和MOSDNS有冲突。

### ISSUE THREAD

**Issue by iamyangyiok** [sbwml/luci-app-mosdns#200]
不知道是新PW 4.75的问题，还是和MOSDNS有冲突。 开了MOSDNS后。只要重启路由器 ，PW内的节点列表全是红的超时，在PW保存应用一下，就绿了有PING延迟。再用着时不时 ，就打不开了，DNS远程解析失败。现在整迷茫了，找不到问题点。

**Comment by iamyangyiok** [comment]
看大佬近来也碰上一样的问题没，XRAY+TCP方式，都是最新版本。

**Comment by iamyangyiok** [comment]
PW 4.75     XRAY 1.88  MOSDNS 5.3.1

**Comment by sbwml** [comment]
是 mosdns luci 的问题，需要更换smartdns 进行修复。

发自我的iPhone

**Comment by iamyangyiok** [comment]
> 是 mosdns luci 的问题，需要更换smartdns 进行修复。 发自我的iPhone
> […](#)
> 在 2024年3月1日，19:34，iamyangyiok ***@***.***> 写道： ﻿ 看大佬近来也碰上一样的问题没，XRAY+TCP方式，都是最新版本。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.

好的，我还是退回到PW 4.71，等你更新
