### ISSUE TITLE
新版编译后，还是和PW有不兼容的问题。

### ISSUE THREAD

**Issue by iamyangyiok** [sbwml/luci-app-mosdns#202]
新版MOSDNS LUCI编译后，还是和PW有不兼容的问题。过一下，远程DNS就无法解析了。已降回PW 4.73-3

**Comment by sbwml** [comment]
我不是说了吗    是这个mosdns luci 的问题   要解决它    装smartdns 就解决了

**Comment by iamyangyiok** [comment]
> 我不是说了吗 是这个mosdns luci 的问题 要解决它 装smartdns 就解决了

就是说ＰＷ 不能再直接套 MOSDNS 了吗，改用SMARTDNS？

**Comment by sbwml** [comment]
#184
