### ISSUE TITLE
兆能M2刷的Nwrt2.13 (QSDK 12.1)，MOSDNS总是未运行

### ISSUE THREAD

**Issue by trunksjiang78** [sbwml/luci-app-mosdns#203]
固件自带的Mosdns5.3.1，运行后就未运行，卸载了安装了其他版本，同样不成功

**Comment by sbwml** [comment]
https://github.com/sbwml/luci-app-mosdns/issues/73

这个 luci 只支持 openwrt 

发自我的iPhone
