### ISSUE TITLE
和编译xray 1.88需要的go版本冲突吗？

### ISSUE THREAD

**Issue by mygithub1981** [sbwml/luci-app-mosdns#204]
编译xray1.88需要的是go 1.22版本，可以编译mosdns吗？按照你提供的解决编译Lean的openwrt时xray1.88出错的方式，编译mosdns老是报错。

**Comment by sbwml** [comment]
这里的 mosdns 支持 1.20 或以上的 golang 版本编译。首选你得确保你的 openwrt 环境下只有来自这里的 mosdns 源码。算了，这种东西你自己也确定不了的   建议不要编译它

**Comment by mygithub1981** [comment]
> 这里的 mosdns 支持 1.20 或以上的 golang 版本编译。首选你得确保你的 openwrt 环境下只有来自这里的 mosdns 源码。算了，这种东西你自己也确定不了的 建议不要编译它

# drop mosdns and v2ray-geodata packages that come with the source
find ./ | grep Makefile | grep v2ray-geodata | xargs rm -f
find ./ | grep Makefile | grep mosdns | xargs rm -f

git clone https://github.com/sbwml/luci-app-mosdns -b v5 package/mosdns
git clone https://github.com/sbwml/v2ray-geodata package/v2ray-geodata
这样可以吗？清除lean里面的。

**Comment by sbwml** [comment]
我觉得可以

从 Windows 版邮件发送

发件人: mygithub1981
发送时间: 2024年3月8日 10:32
收件人: sbwml/luci-app-mosdns
抄送: Bard; State change
主题: Re: [sbwml/luci-app-mosdns] 和编译xray 1.88需要的go版本冲突吗？ (Issue #204)

这里的 mosdns 支持 1.20 或以上的 golang 版本编译。首选你得确保你的 openwrt 环境下只有来自这里的 mosdns 源码。算了，这种东西你自己也确定不了的 建议不要编译它
drop mosdns and v2ray-geodata packages that come with the source
find ./ | grep Makefile | grep v2ray-geodata | xargs rm -f
find ./ | grep Makefile | grep mosdns | xargs rm -f
git clone https://github.com/sbwml/luci-app-mosdns -b v5 package/mosdns
git clone https://github.com/sbwml/v2ray-geodata package/v2ray-geodata
这样可以吗？清除lean里面的。
