### ISSUE TITLE
编译报错：v2dat 

### ISSUE THREAD

**Issue by woni928** [sbwml/luci-app-mosdns#206]
2024-0313 21:34 目前为止。n1云编译报错，之前是v2ray报错，修复了后，现在变成了v2dat报错，被这问题折腾三天了，没有解决，请求大佬帮忙看看，谢谢！
添加了这些东西还是报错：没招了！
# 更新 golang 1.22 版本
rm -rf feeds/packages/net/{xray*,v2ray*,v2ray*,sing*}
rm -rf feeds/packages/lang/golang
git clone https://github.com/sbwml/packages_lang_golang -b 22.x feeds/packages/lang/golang

find ./ | grep Makefile | grep v2ray-geodata | xargs rm -f
find ./ | grep Makefile | grep mosdns | xargs rm -f

git clone https://github.com/sbwml/luci-app-mosdns -b v5 package/mosdns
git clone https://github.com/sbwml/v2ray-geodata package/v2ray-geodata

![v2dat](https://github.com/sbwml/luci-app-mosdns/assets/28220733/56147c29-cd9b-4cf5-93cc-77eb00e9ddb3)

**Comment by sbwml** [comment]
这里 v2dat 不存在这个问题。你出现问题的 v2dat 包不来自这个仓库。

**Comment by woni928** [comment]
> 这里 v2dat 不存在这个问题。你出现问题的 v2dat 包不来自这个仓库。

S佬，那应该怎么解决，请指教。

**Comment by sbwml** [comment]
下载 ipk 文件来安装

**Comment by qingtian110** [comment]
远离包合集仓库，使用openwrt 源码   才是正道，第三方的op 源码。如果他们的feeds 加上了某些包，那你就永远编译不了这个包的最新版。

也就是说即使通过某些手段编译成功了，也是一个带有bug 的版本。因为他们的源码N年 同步更新一次


另外特别要远离 包合集仓库 这种毒瘤

如果非要去堕落，去使用毒瘤源码，那就按照 readme 写的做，把 v2dat 也删掉在重新拉取 sbwml/luci-app-mosdns

```bash
# drop mosdns and v2ray-geodata packages that come with the source
find ./ | grep Makefile | grep v2ray-geodata | xargs rm -f
find ./ | grep Makefile | grep mosdns | xargs rm -f
find ./ | grep Makefile | grep v2dat | xargs rm -f

git clone https://github.com/sbwml/luci-app-mosdns -b v5 package/mosdns
git clone https://github.com/sbwml/v2ray-geodata package/v2ray-geodata
make menuconfig # choose LUCI -> Applications -> luci-app-mosdns
make package/mosdns/luci-app-mosdns/compile V=s
```

**Comment by FunnyFly-ZW** [comment]
> 远离包合集仓库，使用openwrt 源码 才是正道，第三方的op 源码。如果他们的feeds 加上了某些包，那你就永远编译不了这个包的最新版。
> 
> 也就是说即使通过某些手段编译成功了，也是一个带有bug 的版本。因为他们的源码N年 同步更新一次
> 
> 另外特别要远离 包合集仓库 这种毒瘤
> 
> 如果非要去堕落，去使用毒瘤源码，那就按照 readme 写的做，把 v2dat 也删掉在重新拉取 sbwml/luci-app-mosdns
> 
> ```shell
> # drop mosdns and v2ray-geodata packages that come with the source
> find ./ | grep Makefile | grep v2ray-geodata | xargs rm -f
> find ./ | grep Makefile | grep mosdns | xargs rm -f
> find ./ | grep Makefile | grep v2dat | xargs rm -f
> 
> git clone https://github.com/sbwml/luci-app-mosdns -b v5 package/mosdns
> git clone https://github.com/sbwml/v2ray-geodata package/v2ray-geodata
> make menuconfig # choose LUCI -> Applications -> luci-app-mosdns
> make package/mosdns/luci-app-mosdns/compile V=s
> ```

感谢，遇到同样的问题，总算解决了

**Comment by woni928** [comment]
我是这样解决的
sed -i 's#GO_PKG_TARGET_VARS.*# #g' feeds/packages/utils/v2dat/Makefile

**Comment by zow2023** [comment]
> 远离包合集仓库，使用openwrt 源码 才是正道，第三方的op 源码。如果他们的feeds 加上了某些包，那你就永远编译不了这个包的最新版。
> 
> 也就是说即使通过某些手段编译成功了，也是一个带有bug 的版本。因为他们的源码N年 同步更新一次
> 
> 另外特别要远离 包合集仓库 这种毒瘤
> 
> 如果非要去堕落，去使用毒瘤源码，那就按照 readme 写的做，把 v2dat 也删掉在重新拉取 sbwml/luci-app-mosdns
> 
> ```shell
> # drop mosdns and v2ray-geodata packages that come with the source
> find ./ | grep Makefile | grep v2ray-geodata | xargs rm -f
> find ./ | grep Makefile | grep mosdns | xargs rm -f
> find ./ | grep Makefile | grep v2dat | xargs rm -f
> 
> git clone https://github.com/sbwml/luci-app-mosdns -b v5 package/mosdns
> git clone https://github.com/sbwml/v2ray-geodata package/v2ray-geodata
> make menuconfig # choose LUCI -> Applications -> luci-app-mosdns
> make package/mosdns/luci-app-mosdns/compile V=s
> `感谢回复 我用你的思路解决了 问题
