### ISSUE TITLE
为啥编译出来的没有最大连接数？

### ISSUE THREAD

**Issue by mygithub1981** [sbwml/luci-app-mosdns#207]
内核6.6的，编译出来没有最大连接数，咋回事？

**Comment by sbwml** [comment]
不懂就问    最大连接数是什么

发自我的iPhone

**Comment by mygithub1981** [comment]
> 不懂就问    最大连接数是什么
> 
> 发自我的iPhone
> 
> > 在 2024年3月15日，12:03，mygithub1981 ***@***.***> 写道：
> > 
> > ﻿
> > 内核6.6的，编译出来没有最大连接数，咋回事？
> > 
> > —
> > Reply to this email directly, view it on GitHub, or unsubscribe.
> > You are receiving this because you are subscribed to this thread.
> 

![IMG_20240320_105254.png](https://github.com/sbwml/luci-app-mosdns/assets/151316180/f9bcdc0c-c6b9-46de-9a22-dca726212698)

就是这个，我用l的源编译出来的5.31就有这个，用你的就没有这个。

**Comment by sbwml** [comment]
这是老版本的选项，v5.3.0 核心起，这个数值已经被移除，不需要人为设定
