### ISSUE TITLE
重启设备出现错误好久外网不能用

### ISSUE THREAD

**Issue by mcusee** [sbwml/luci-app-mosdns#212]
<img width="1287" alt="截屏2024-03-29 22 48 40" src="https://github.com/sbwml/luci-app-mosdns/assets/49904620/29cf0cf0-278a-46af-9c32-a97beb6dff36">

**Comment by sbwml** [comment]
8.8.8.8 不通，盲猜你本机科学插件未完成启动

另外多问一句，你是自定义配置文件吗？
