### ISSUE TITLE
更新luci-app-mosdns_1.5.19后显示未运行

### ISSUE THREAD

**Issue by bydxsoft** [sbwml/luci-app-mosdns#213]
更新luci-app-mosdns_1.5.19后重启显示未运行。重新安装luci-app-mosdns_1.5.18正常  x86的

**Comment by sbwml** [comment]
更新后，打开mosdns 页面点击以下保存应用就好了。因为配置差异

**Comment by bydxsoft** [comment]
谢谢大佬，好了，以前习惯性更新后未保存应用，直接重启了
