### ISSUE TITLE
安装语言包时出错

### ISSUE THREAD

**Issue by dwbii** [sbwml/luci-app-mosdns#214]
安装语言包时出错，但可以使用，luci-i18n-mosdns-zh-cn_git-23.319.54348-e79a991_all.ipk
![屏幕截图 2024-04-03 151105](https://github.com/sbwml/luci-app-mosdns/assets/18597768/58998f5c-a41d-4f90-af4c-bd716685f1ce)

**Comment by sbwml** [comment]
这种错误可以无视，实际已经安装
