### ISSUE TITLE
大佬~~我用自定义yaml配置启动时候无法生成geosite_apple.txt

### ISSUE THREAD

**Issue by DFP86** [sbwml/luci-app-mosdns#216]
如果用webui方式设置，是可以自动生成的。我在学习的过程中尝试自己修改yaml，结果发现启动时候无法自动生成geosite_apple.txt，而且会删掉这个文件。

系统的日志文件：
Error: failed to init plugin #2 geosite_apple, failed to init plugin: failed to load file #0 /var/mosdns/geosite_apple.txt, open /var/mosdns/geosite_apple.txt: no such file or directory

FATAL   failed to init plugin #2 geosite_apple, failed to init plugin: failed to load file #0 /var/mosdns/geosite_apple.txt, open /var/mosdns/geosite_apple.txt: no such file or directory

我去看看init.d文件

update：找到了 sh执行文件里手动加上 - f apple，好像行了，现在是另外的报错，我再看看~~

update2：我的yaml文件有地方写错了，仔细排查后，就ok了~~谢谢大佬~~~

**Comment by sbwml** [comment]
老六  我真的服了，还改脚本。

![image](https://github.com/sbwml/luci-app-mosdns/assets/16485166/12e64dd2-6021-4987-b29e-c146c487fa5c)

你看不到的咩。

**Comment by DFP86** [comment]
> 老六 我真的服了，还改脚本。
> 
> ![image](https://private-user-images.githubusercontent.com/16485166/322308926-12e64dd2-6021-4987-b29e-c146c487fa5c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMxNDUyMzgsIm5iZiI6MTcxMzE0NDkzOCwicGF0aCI6Ii8xNjQ4NTE2Ni8zMjIzMDg5MjYtMTJlNjRkZDItNjAyMS00OTg3LWIyOWUtYzE0NmM0ODdmYTVjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE1VDAxMzUzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM3NmM3MDcwZWRkM2NiMDlkN2I1M2VmYTUxYmU0YzY5MWU3MzFhNWNhNjRlMmExMDcxZjk4MWE4YTY0NjE0YWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.GJNBfHAby8QfBvAS03I53OFDFWDLsLGIYRwduX7LOhU)
> 
> 你看不到的咩。

啊。。。我以为这个是导出备份用的。。。sorry[捂脸]  谢谢您
