### ISSUE TITLE
更新数据库 - github代理 会给 「非github地址」 也加上代理

### ISSUE THREAD

**Issue by xlighting2017** [sbwml/luci-app-mosdns#217]
step to reproduce

1.  基本设置 -- 高级选项 -- 广告过滤规则来源， 添加 自定义地址，例如 `https://small.oisd.nl/domainswild2`；
2. 在 更新数据库 -- github代理 处， 配置代理；
3.  此时更新数据库， 会发现 「自定义地址」 也被加上了 代理，导致下载失败；

expect result

只对「github地址」，添加代理，跳过 「非github地址」

**Comment by sbwml** [comment]
修复 https://github.com/sbwml/luci-app-mosdns/commit/97867eae9df8201c1408000e7160749f76d60bcb

**Comment by xlighting2017** [comment]
Confirm fixed
