### ISSUE TITLE
关于ipv6使用

### ISSUE THREAD

**Issue by yumaoss** [sbwml/luci-app-mosdns#218]
您好，我有一台只有ipv6的日本vps
![mosdns](https://github.com/sbwml/luci-app-mosdns/assets/58129947/85c756c3-0cd1-4e93-a3cf-18043e3e7c41)
openwrt开启ipv6，
openclash 开启ipv6支持
只选上nameserver 127.0.0.1:5335，其他不选
ipv4与ipv6的节点都可以使用
请问要不要在远程dns中添加ipv6dns，我添加上启动不起来
不添加的话，走的是国内还是国外dns？该如何检查

**Comment by sbwml** [comment]
DNS 纯 v4或6 均能同时解析双栈地址
