### ISSUE TITLE
无法运行 mosdns

### ISSUE THREAD

**Issue by xy-241** [sbwml/luci-app-mosdns#219]
经过排查，无法启动mosdns的原因是缺失 `geosite_cn.txt`, `geoip_cn.txt` 和 `geosite_geolocation-!cn.txt` 这三个文件。尝试手动创建这三个文件，但在启动`luci-app-mosdns`时会自动消失, 从而mosdns启动失败。

**Comment by sbwml** [comment]
等我学会算命时再答复你

**Comment by yukari190** [comment]
> 等我学会算命时再答复你

你好，请问一下v5.3.1里面的v2dat_2022-12-15-47b8ee51-1_mipsel_24kc.ipk好像有问题，我这边日志显示Error relocating /usr/bin/v2dat: __nanosleep_time64: symbol not found；然后我看了下文件大小是2.47 MB，而其他的版本集里面的都是2.43 MB，我重新安装了其他版本里面的日志就不报错了，但是还是MosDNS 未运行状态；直接运行的话显示Error relocating /usr/bin/mosdns: __nanosleep_time64: symbol not found。

=================================================

目前降级到了v5.3.0可以正常使用，就是更新数据库里没有代理服务器，更新不了了

**Comment by tujj99** [comment]
遇到相同的问题，5.3.1版本，如果不更新数据库，luci-mosdns是无法启动的，这个逻辑不太合理

**Comment by fancyjohnnyz** [comment]
你如果装了Transmission的话默认的API监听端口和Transmission面板的9091是冲突的, 换个端口就可以 也建议作者换个监听端口, 大部分的openwrt用户都装了Transmission
