### ISSUE TITLE
开机后mosdns需要重新启动

### ISSUE THREAD

**Issue by Heartforever702** [sbwml/luci-app-mosdns#221]
安装后无法启动，修改vim /etc/init.d/mosdns中的start 55至start 99可解决
启动openwrt后mosdns需要重新启动才能发挥作用，且日志中标明有错误
![mosdns反馈2](https://github.com/sbwml/luci-app-mosdns/assets/74862250/acb0f4d9-c58e-4471-9d58-89ac87a6cc2a)

**Comment by sbwml** [comment]
openwrt 未复现该问题。

我非算命先生，如果你要反馈问题，你必须携带有效信息。#73

**Comment by Antecer** [comment]
> 安装后无法启动，修改vim /etc/init.d/mosdns中的start 55至start 99可解决 启动openwrt后mosdns需要重新启动才能发挥作用，且日志中标明有错误 ![mosdns反馈2](https://private-user-images.githubusercontent.com/74862250/329509606-acb0f4d9-c58e-4471-9d58-89ac87a6cc2a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY5NjI3MDYsIm5iZiI6MTcxNjk2MjQwNiwicGF0aCI6Ii83NDg2MjI1MC8zMjk1MDk2MDYtYWNiMGY0ZDktYzU4ZS00NDcxLTlkNTgtODlhYzg3YTZjYzJhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI5VDA2MDAwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMzNzNjOTBjZDQ2MzNhZDRkMmUwNDRjMDY1ZGQxNzNmYTY5MTVmY2I0YzM3Y2RlMjNkMzhhNTVjMzUzOTc0NjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.LEvwQZ9ocUHuKcOU1ZuFlfb3bFiP_el3XfUCiGbUfDU)

这个日志内容并没有说MosDNS未启动的原因，而且这4条内容都是INFO而不是ERROR，不知道为嘛会被分类到daemon.err
我这里也有这样的日志信息，但是MosDNS是正常启动并能正确使用的。
