### ISSUE TITLE
安装后在服务里找不到mosdns

### ISSUE THREAD

**Issue by lylcwj** [sbwml/luci-app-mosdns#222]
主机名称	OpenWrt
型号	Xiaomi Redmi Router AX6000 (OpenWrt U-Boot layout)
架构	ARMv8 Processor rev 4
目标平台	mediatek/filogic
固件版本	OpenWrt 23.05.3 r23809-234f1a2efa / LuCI openwrt-23.05 branch git-24.086.45142-09d5a38

安装记录如下：
sh ./install.sh

Checking available space  ...

Checking platform  ...

Update opkg sources ...
Downloading https://downloads.openwrt.org/releases/23.05.3/targets/mediatek/filogic/packages/Packages.gz
Updated list of available packages in /var/opkg-lists/openwrt_core
Downloading https://downloads.openwrt.org/releases/23.05.3/targets/mediatek/filogic/packages/Packages.sig
Signature check passed.
Downloading https://downloads.openwrt.org/releases/23.05.3/packages/aarch64_cortex-a53/base/Packages.gz
Updated list of available packages in /var/opkg-lists/openwrt_base
Downloading https://downloads.openwrt.org/releases/23.05.3/packages/aarch64_cortex-a53/base/Packages.sig
Signature check passed.
Downloading https://downloads.openwrt.org/releases/23.05.3/packages/aarch64_cortex-a53/luci/Packages.gz
Updated list of available packages in /var/opkg-lists/openwrt_luci
Downloading https://downloads.openwrt.org/releases/23.05.3/packages/aarch64_cortex-a53/luci/Packages.sig
Signature check passed.
Downloading https://downloads.openwrt.org/releases/23.05.3/packages/aarch64_cortex-a53/packages/Packages.gz
Updated list of available packages in /var/opkg-lists/openwrt_packages
Downloading https://downloads.openwrt.org/releases/23.05.3/packages/aarch64_cortex-a53/packages/Packages.sig
Signature check passed.
Downloading https://downloads.openwrt.org/releases/23.05.3/packages/aarch64_cortex-a53/routing/Packages.gz
Updated list of available packages in /var/opkg-lists/openwrt_routing
Downloading https://downloads.openwrt.org/releases/23.05.3/packages/aarch64_cortex-a53/routing/Packages.sig
Signature check passed.
Downloading https://downloads.openwrt.org/releases/23.05.3/packages/aarch64_cortex-a53/telephony/Packages.gz
Updated list of available packages in /var/opkg-lists/openwrt_telephony
Downloading https://downloads.openwrt.org/releases/23.05.3/packages/aarch64_cortex-a53/telephony/Packages.sig
Signature check passed.
Package luci-compat (git-24.086.45108-51aee90) installed in root is up to date.

Download Packages ...

Download https://github.com/sbwml/luci-app-mosdns/releases/download/v5.3.1/mosdns_5.3.1-1_aarch64_cortex-a53.ipk ...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 5790k  100 5790k    0     0  1815k      0  0:00:03  0:00:03 --:--:-- 1885k
Download https://github.com/sbwml/luci-app-mosdns/releases/download/v5.3.1/v2dat_2022-12-15-47b8ee51-1_aarch64_cortex-a53.ipk ...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 2630k  100 2630k    0     0   919k      0  0:00:02  0:00:02 --:--:--  919k
Download https://github.com/sbwml/luci-app-mosdns/releases/download/v5.3.1/luci-app-mosdns_1.5.20_all.ipk ...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 76552  100 76552    0     0  49364      0  0:00:01  0:00:01 --:--:-- 49388
Download https://github.com/sbwml/luci-app-mosdns/releases/download/v5.3.1/luci-i18n-mosdns-zh-cn_git-23.319.54348-e79a991_all.ipk ...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  4665  100  4665    0     0   3897      0  0:00:01  0:00:01 --:--:--  3897
Download https://github.com/sbwml/luci-app-mosdns/releases/download/v5.3.1/v2ray-geoip_2024-02-26_all.ipk ...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 35441  100 35441    0     0  28959      0  0:00:01  0:00:01 --:--:-- 28978
Download https://github.com/sbwml/luci-app-mosdns/releases/download/v5.3.1/v2ray-geosite_2024-02-26_all.ipk ...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 1811k  100 1811k    0     0   696k      0  0:00:02  0:00:02 --:--:--  696k

Install Packages ...

Not downgrading package v2ray-geoip on root from 202404250042-1 to 2024-02-26.
Not downgrading package v2ray-geosite on root from 20240426060244-1 to 2024-02-26.
Package v2dat (2022-12-15-47b8ee51-1) installed in root is up to date.
Package mosdns (5.3.1-1) installed in root is up to date.
Package luci-app-mosdns (1.5.20) installed in root is up to date.
Package luci-i18n-mosdns-zh-cn (git-23.319.54348-e79a991) installed in root is up to date.
Done!

先是手动上传安装包，安装后没有，就用脚本安装了一遍，安装过程正常，可是开机系统日志里找不到mosdns的启动记录，在菜单栏服务里也没有找到mosdns

路由器重启了两遍，还是找不到

**Comment by sbwml** [comment]
有没有试过浏览器无痕模式

发自我的iPhone

**Comment by lylcwj** [comment]
> 有没有试过浏览器无痕模式 发自我的iPhone
> […](#)
> 在 2024年5月15日，21：33，lylcwj ***@***.***> 写道： 主机名称 OpenWrt 型号 Xiaomi Redmi Router AX6000 （OpenWrt U-Boot layout） 架构 ARMv8 Processor rev 4 目标平台 MediaTek/Filogic 固件版本 OpenWrt 23.05.3 r23809-234f1a2efa / LuCI openwrt-23.05 branch git-24.086.45142-09d5a38 安装记录如下： sh ./install.sh 正在检查可用空间... 检查平台... 更新 opkg 源... 下载 https://downloads.openwrt.org/releases/23.05.3/targets/mediatek/filogic/packages/Packages.gz 更新的 /var/opkg-lists/openwrt_core 中的可用软件包列表 下载 https://downloads.openwrt.org/releases/23.05.3/targets/mediatek/filogic/packages/Packages.sig 签名检查通过。 下载 https://downloads.openwrt.org/releases/23.05.3/packages/aarch64_cortex-a53/base/Packages.gz 更新了 /var/opkg-lists/openwrt_base 中的可用软件包列表 下载 https://downloads.openwrt.org/releases/23.05.3/packages/aarch64_cortex-a53/base/Packages.sig 签名检查通过。 下载 https://downloads.openwrt.org/releases/23.05.3/packages/aarch64_cortex-a53/luci/Packages.gz 更新了 /var/opkg-lists/openwrt_luci 中的可用软件包列表 下载 https://downloads.openwrt.org/releases/23.05.3/packages/aarch64_cortex-a53/luci/Packages.sig 签名检查通过。 下载 https://downloads.openwrt.org/releases/23.05.3/packages/aarch64_cortex-a53/packages/Packages.gz 更新的可用软件包列表 /var/opkg-lists/openwrt_packages 下载 https://downloads.openwrt.org/releases/23.05.3/packages/aarch64_cortex-a53/packages/Packages.sig 签名检查通过。 下载 https://downloads.openwrt.org/releases/23.05.3/packages/aarch64_cortex-a53/routing/Packages.gz 更新了 /var/opkg-lists/openwrt_routing 中的可用软件包列表 下载 https://downloads.openwrt.org/releases/23.05.3/packages/aarch64_cortex-a53/routing/Packages.sig 签名检查通过。 下载 https://downloads.openwrt.org/releases/23.05.3/packages/aarch64_cortex-a53/telephony/Packages.gz 更新了 /var/opkg-lists/openwrt_telephony 中的可用软件包列表 下载 https://downloads.openwrt.org/releases/23.05.3/packages/aarch64_cortex-a53/telephony/Packages.sig 签名检查通过。 root中安装的luci-compat （git-24.086.45108-51aee90）软件包是最新的。 下载软件包... 下载 https://github.com/sbwml/luci-app-mosdns/releases/download/v5.3.1/mosdns_5.3.1-1_aarch64_cortex-a53.ipk ... % 总计 % 接收 % Xferd 平均速度 时间 时间 时间 当前 dload upload 总花费的左速度 100 5790k 100 5790k 0 0 1815k 0 0：00：03 0：00：03 --：--：-- 1885k 下载 https://github.com/sbwml/luci-app-mosdns/releases/download/v5.3.1/v2dat_2022-12-15-47b8ee51-1_aarch64_cortex-a53.ipk ... % 总计 % 接收 % Xferd 平均速度 时间 时间 时间 当前 dload upload 总花费的左速度 100 2630k 100 2630k 0 0 919k 0 0：00：02 0：00：02 --：--：-- 919k 下载 https://github.com/sbwml/luci-app-mosdns/releases/download/v5.3.1/luci-app-mosdns_1.5.20_all.ipk ... % 总计 % 接收 % Xferd 平均速度 时间 时间 时间 当前 dload upload 总花费的左速度 100 76552 100 76552 0 0 49364 0 0:00:01 0:00:01 --:--:-- 49388 下载 https://github.com/sbwml/luci-app-mosdns/releases/download/v5.3.1/luci-i18n-mosdns-zh-cn_git-23.319.54348-e79a991_all.ipk... % 总计 % 接收 % Xferd 平均速度 时间 时间 时间 当前 dload upload 总花费的左速度 100 4665 100 4665 0 0 3897 0 0:00:01 0:00:01 --:--:-- 3897 下载 https://github.com/sbwml/luci-app-mosdns/releases/download/v5.3.1/v2ray-geoip_2024-02-26_all.ipk ... % 总计 % 接收 % Xferd 平均速度 时间 时间 时间 当前 dload upload 总花费的左速度 100 35441 100 35441 0 0 28959 0 0:00:01 0:00:01 --:--:-- 28978 下载 https://github.com/sbwml/luci-app-mosdns/releases/download/v5.3.1/v2ray-geosite_2024-02-26_all.ipk ... % 总计 % 接收 % Xferd 平均速度 时间 时间 时间 当前 dload upload 总花费的左速度 100 1811k 100 1811k 0 0 696k 0 0：00：02 0：00：02 --：--：-- 696k 安装软件包... 不将 root 上的 v2ray-geoip 包从 202404250042-1 降级到 2024-02-26。 不会将 root 上的 v2ray-geosite 包从 20240426060244-1 降级到 2024-02-26。 root 中安装的软件包 v2dat （2022-12-15-47b8ee51-1） 是最新的。 安装在 root 中的软件包 mosdns （5.3.1-1） 是最新的。 安装在 root 中的软件包 luci-app-mosdns （1.5.20） 是最新的。 安装在 root 中的软件包 luci-i18n-mosdns-zh-cn （git-23.319.54348-e79a991） 是最新的。 做！ 先是手动上传安装包，安装后没有，就用脚本安装了一遍，安装过程正常，可是开机系统日志里找不到mosdns的启动记录，在菜单栏服务里也没有找到mosdns — 直接回复此电子邮件，在 GitHub 上查看或取消订阅。 您收到此消息是因为您订阅了此线程。

试过无痕模式，还是找不到

**Comment by lylcwj** [comment]
> 

> 有没有试过浏览器无痕模式 发自我的iPhone
> […](#)
>
试过无痕模式，还是找不到

**Comment by lylcwj** [comment]
这俩文件我的路由器在安装脚本执行完也没有啊，但是安装的时候没有报错啊，会不会因为开了ipv6？
/etc/config/mosdns
 /etc/mosdns

**Comment by sbwml** [comment]
那就不知道了

发自我的iPhone

**Comment by sbwml** [comment]
你根据置顶问题说的做，把那三个文件以格式化的方式发出来

发自我的iPhone

**Comment by FuCheng-G** [comment]
同问，+1

**Comment by cyberen2008** [comment]
i enter this problem when i use installing the service

**Comment by TenviLi** [comment]
+1
