### ISSUE TITLE
部分网站无法解析，该如何更新数据库

### ISSUE THREAD

**Issue by facebook20146** [sbwml/luci-app-mosdns#225]
比如此类网站，https://pan.qlam.cc/，是公众号博主自己搭建的网盘，用手机流量访问可以，但是用路由器(使用mosdns)就无法打开，显示连接超时
如何把这类小网站加到数据库，让mosdns直接按国内网站解析

**Comment by sbwml** [comment]
规则列表有一个白名单，你把域名写上去的就强制走国内的DNs。 


发自我的 Apple Watch

**Comment by facebook20146** [comment]
> 规则列表有一个白名单，你把域名写上去的就强制走国内的DNs。 发自我的 Apple Watch

有没有途径向geosite提交网站，帮助geosite完善😃

**Comment by huanzhiyi** [comment]
> 规则列表有一个白名单，你把域名写上去的就强制走国内的DNs。 发自我的 Apple Watch

添加规则列表时，修改添加提示  “没有待应用的更改”  不过 规则列表上的框确实是添加新的规则了。如在白名单下 添加一个keyword:bfengbf  但是实际上没有想要的效果。 请问这是什么问题？
