### ISSUE TITLE
访问国外网站能否不屏蔽ipv6?

### ISSUE THREAD

**Issue by Pacio** [sbwml/luci-app-mosdns#226]
目前线路环境还是优先走ipv6科学效果最好，默认配置直接屏蔽了ipv6 这样我无论passwall 怎么设置 通过ip111.cn检测的都是只走v4

**Comment by sbwml** [comment]
远程 DNS 首选 IPv4

远程 / 流媒体 DNS 解析双栈地址时首选 IPv4，目标仅 IPv6 时不受影响

发自我的iPhone

**Comment by Pacio** [comment]
> 远程 DNS 首选 IPv4 远程 / 流媒体 DNS 解析双栈地址时首选 IPv4，目标仅 IPv6 时不受影响 发自我的iPhone
> […](#)
> 在 2024年7月1日，22:17，Pacio ***@***.***> 写道： ﻿ 目前线路环境还是优先走ipv6科学效果最好，默认配置直接屏蔽了ipv6 这样我无论passwall 怎么设置 通过ip111.cn检测的都是只走v4 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.

这个没用，勾选或者不勾选~都是只走v4

**Comment by sbwml** [comment]
那直接说明你要的效果和 mosdns 无关。mosdns dns 只能帮你实现默认响应、IPv4 优先，至于到底使用的 v4 或 v6 这是客户端决定的事情。

你得明白 MosDNS 到底是做什么的，它可能并不是你需要使用东西。#184
