### ISSUE TITLE
可以单独删除某条dns解析吗

### ISSUE THREAD

**Issue by z499738316** [sbwml/luci-app-mosdns#227]
是这样的，我有个梯子是用的别人的，用的域名解析ip一直在变，但是mosdns又因为有缓存，所以一直是旧的ip，清空缓存又会清空全部，能不能单独清空一条dns解析啊

**Comment by sbwml** [comment]
不能。

你可以把这些域名添加到 ddns 规则列表中，它就不会被缓存。

发自我的iPhone
