### ISSUE TITLE
编译的，固件， 能不能加个ddns-go softether，

### ISSUE THREAD

**Issue by darkrain88** [sbwml/luci-app-mosdns#230]
谢谢。 么有没办法联系， 就这么提issue了。

另外 北大的源， 现在只有https://mirrors.pku.edu.cn/openwrt/releases/23.05.3  没有 23.05.4

**Comment by sbwml** [comment]
这是 mosdns luci，和固件编译无关

**Comment by darkrain88** [comment]
> 这是 mosdns luci，和固件编译无关

谢谢， 已经在学习怎么定制了
