### ISSUE TITLE
安装脚本无法对中国地区加速

### ISSUE THREAD

**Issue by newton-miku** [sbwml/luci-app-mosdns#232]
RT,安装脚本中有请求ip.cooluc.com，判断地区是否是中国，但目前仅返回502

因此，建议尝试更换为大厂的地址api，如b站的[API](https://api.live.bilibili.com/ip_service/v1/ip_service/get_ip_addr)，检查该api中的data中的country是否为中国即可

**Comment by sbwml** [comment]
谢告知

**Comment by newton-miku** [comment]
不用谢，BTW，上文提到的换用b站IP信息的API已提交PR，您可以审阅一下
