### ISSUE TITLE
即使DNS 缓存大小设置为0，但是还是会缓存的问题

### ISSUE THREAD

**Issue by Depressboy** [sbwml/luci-app-mosdns#234]
在设置中将DNS 缓存大小设置为0，乐观缓存 TTL也设置为0，但是在查询时发现还是会缓存DNS。

重新启动后首次查询需要约1秒的时间，smart设置的ipset能查询到ip记录，清理ipset列表后再次查询dns，迅速应答，ipset无记录

点击刷新缓存后重新查询，ipset再次出现记录

查看插件自动配置的配置文件，可否在不配置缓存时将lazy_cache相关插件删除呢？

**Comment by sbwml** [comment]
https://github.com/sbwml/luci-app-mosdns/commit/c31e112465cb564180f04871bc6694a22ad11fa5

**Comment by Depressboy** [comment]
大佬响应迅速啊，赞一个

**Comment by Depressboy** [comment]
自己编译没通过，只能等大佬发布了

**Comment by sbwml** [comment]
ipk 文件随 mosdns 版本更新发布，而mosdns 上游已经停止维护，这里基本不会更新 ipk 安装包了

发自我的iPhone

**Comment by Depressboy** [comment]
好吧，那只能自己编译了，多谢大佬
