### ISSUE TITLE
CF优选ip功能可否增加域名支持？

### ISSUE THREAD

**Issue by drzazi** [sbwml/luci-app-mosdns#235]
> 添加了，至于会不会用，怎么用。自行研究。
> 
> ![1](https://private-user-images.githubusercontent.com/16485166/268921696-e19b30fb-f445-40c8-a19f-08a34b11af08.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIyMjM3MTAsIm5iZiI6MTcyMjIyMzQxMCwicGF0aCI6Ii8xNjQ4NTE2Ni8yNjg5MjE2OTYtZTE5YjMwZmItZjQ0NS00MGM4LWExOWYtMDhhMzRiMTFhZjA4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI5VDAzMjMzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFjZWU4MWRjZGI3ODVlYmQ1NzZhMDE3OGIxOGRhM2EyZDhhZGE4MGM5MjgxYzM3M2E4NDc2MjQ2OGM4YWIzN2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.EwWbS8YloqFq2A6_p3Pm40NryBgj8YIa54y7oyr8spw)

你好， @sbwml
可否增加域名支持？现在只能手动加ip。
如果可以填写域名，配合https://hub.docker.com/r/lee1080/cfstddns 就可以实现自动更新ip。

_Originally posted by @drzazi in https://github.com/sbwml/luci-app-mosdns/issues/121#issuecomment-2255112901_

**Comment by sbwml** [comment]
不考虑，这种操作实现去来会很脏，并且这已经脱离 DNS 层面应该做的事情。

单你可以使用 openwrt 的自动化 + mosdns 核心去完成这件事情。

发自我的iPhone
