### ISSUE TITLE
新版本mosdns加入openwrt中一起编译时，出现问题

### ISSUE THREAD

**Issue by NEARWN** [sbwml/luci-app-mosdns#237]
新版本mosdns加入openwrt中一起编译时，出现问题，会缺少luci-i18n-mosdns-zh-cn语言包，并且在图形主界面服务中不显示MOSDNS，V5-LUA版本正常

**Comment by sbwml** [comment]
它只适合使用 luci2 的 OpenWrt 或 衍生版本（openwrt、xwrt、immortalwrt、istoreos 等），但绝对不能是 lede。

发自我的iPhone

**Comment by ywt114** [comment]
> 它只适合使用 luci2 的 OpenWrt 或 衍生版本（openwrt、xwrt、immortalwrt、istoreos 等），但绝对不能是 lede。 发自我的iPhone
> […](#)
> 在 2024年8月6日，11:53，NEARWN ***@***.***> 写道： ﻿ 新版本mosdns加入openwrt中一起编译时，出现问题，会缺少luci-i18n-mosdns-zh-cn语言包，并且在图形主界面服务中不显示MOSDNS，V5-LUA版本正常 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.

那意思基于lean的就不在能使用咯？只能使用v5-lua分支咯？

**Comment by sbwml** [comment]
openwrt-18.06 以下使用 v5-lua 分支

发自我的iPhone

**Comment by Mrican** [comment]
上游mosdns v5.3.3 更新依赖以及更新至 go1.23

虽然没有新功能，也期待大佬同步更新

**Comment by lengfwong** [comment]
> 上游mosdns v5.3.3 更新依赖以及更新至 go1.23
> 
> 虽然没有新功能，也期待大佬同步更新

可以自己修改一下Makefile 文件，编译下就可以了，我昨晚把sbwml大佬的改了下已运行，转过头看luci也更新了。

**Comment by Mrican** [comment]
> > 上游mosdns v5.3.3 更新依赖以及更新至 go1.23
> > 虽然没有新功能，也期待大佬同步更新
> 
> 可以自己修改一下Makefile 文件，编译下就可以了，我昨晚把sbwml大佬的改了下已运行，转过头看luci也更新了。

不会编译。。。
今晚回家再安装，也不知道mt3000 v4.6.3，是否支持Luci2，官方论坛几乎是个摆设，没什么回应的

**Comment by tcscat** [comment]
> > 上游mosdns v5.3.3 更新依赖以及更新至 go1.23
> > 虽然没有新功能，也期待大佬同步更新
> 
> 可以自己修改一下Makefile 文件，编译下就可以了，我昨晚把sbwml大佬的改了下已运行，转过头看luci也更新了。

请问如何编译

**Comment by lengfwong** [comment]
> > > 上游mosdns v5.3.3 更新依赖以及更新至 go1.23
> > > 虽然没有新功能，也期待大佬同步更新
> > 
> > 
> > 可以自己修改一下Makefile 文件，编译下就可以了，我昨晚把sbwml大佬的改了下已运行，转过头看luci也更新了。
> 
> 请问如何编译

OpenWrt编译，网上一搜一大堆。
