### ISSUE TITLE
最新版本5.3.3安装后，openwrt界面没有mosdns，mosdns无效

### ISSUE THREAD

**Issue by Jasonzhang2023** [sbwml/luci-app-mosdns#238]
首先感谢大佬这么快更新了5.3.3，最近几次大佬一更新我这边就下载.ipk到本地更新。

我用的是esir openwrt高大全: OpenWrt R23.7.7 GDQ V2[2023] Compiled by eSir / LuCI Master (git-23.198.59743-991daf5)

本次不更新luci 1.6.0，使用上一版本的ipk（luci-app-mosdns_1.5.16_all.ipk），直接安装mosdns_5.3.3-1_x86_64.ipk，程序是可以顺利运行。

但是我更新luci-app-mosdns_1.6.0_all.ipk后报错，openwrt客户界面无mosdns，htop中也没mosdns的进程，具体安装情况如下：

root@Happy-OpenWrt:/usr/share/temp# opkg install luci-app-mosdns_1.6.0_all.ipk
Upgrading luci-app-mosdns on root from 1.5.16 to 1.6.0...
Removing obsolete file /usr/lib/lua/luci/view/mosdns/mosdns_status.htm.
Removing obsolete file /usr/lib/lua/luci/model/cbi/mosdns/update.lua.
Removing obsolete file /www/luci-static/resources/mosdns/lib/codemirror.js.
Removing obsolete file /www/luci-static/resources/mosdns/lib/codemirror.css.
Removing obsolete file /www/luci-static/resources/mosdns/addon/fold/foldgutter.js.
Removing obsolete file /usr/share/mosdns/default.yaml.
Removing obsolete file /www/luci-static/resources/mosdns/theme/dracula.css.
Removing obsolete file /www/luci-static/resources/mosdns/mode/yaml/yaml.js.
Removing obsolete file /usr/lib/lua/luci/view/mosdns/mosdns_flush_cache.htm.
Removing obsolete file /www/luci-static/resources/mosdns/addon/fold/foldgutter.css.
Removing obsolete file /usr/lib/lua/luci/view/mosdns/mosdns_log.htm.
Removing obsolete file /usr/lib/lua/luci/view/mosdns/mosdns_geo_update.htm.
Removing obsolete file /usr/lib/lua/luci/view/mosdns/mosdns_editor.htm.
Removing obsolete file /usr/lib/lua/luci/model/cbi/mosdns/basic.lua.
Removing obsolete file /www/luci-static/resources/mosdns/addon/fold/indent-fold.js.
Removing obsolete file /usr/lib/lua/luci/model/cbi/mosdns/rule_list.lua.
Removing obsolete file /usr/lib/lua/luci/controller/mosdns.lua.
Removing obsolete file /usr/lib/lua/luci/model/cbi/mosdns/log.lua.
Removing obsolete file /www/luci-static/resources/mosdns/addon/fold/foldcode.js.
Configuring luci-app-mosdns.
Collected errors:
 * resolve_conffiles: Existing conffile /etc/config/mosdns is different from the conffile in the new package. The new conffile will be placed at /etc/config/mosdns-opkg.
 * resolve_conffiles: Existing conffile /etc/mosdns/rule/greylist.txt is different from the conffile in the new package. The new conffile will be placed at /etc/mosdns/rule/greylist.txt-opkg.
 * resolve_conffiles: Existing conffile /etc/mosdns/rule/hosts.txt is different from the conffile in the new package. The new conffile will be placed at /etc/mosdns/rule/hosts.txt-opkg.
 * resolve_conffiles: Existing conffile /etc/mosdns/rule/whitelist.txt is different from the conffile in the new package. The new conffile will be placed at /etc/mosdns/rule/whitelist.txt-opkg.

小白不知道哪里出了问题，暂时先强制把luci降级到1.5.16使用着。
等待大佬后续解答。

**Comment by sbwml** [comment]
我没听说过有名字叫“高大全”的 OpenWrt

现在的 luci 只适用于 luci2

发自我的iPhone

**Comment by Jasonzhang2023** [comment]
> 我没听说过有名字叫“高大全”的 OpenWrt 现在的 luci 只适用于 luci2 发自我的iPhone
> […](#)
> 在 2024年8月15日，14:52，Jasonzhang2023 ***@***.***> 写道： ﻿ 首先感谢大佬这么快更新了5.3.3，最近几次大佬一更新我这边就下载.ipk到本地更新。 我用的是esir openwrt高大全: OpenWrt R23.7.7 GDQ V2[2023] Compiled by eSir / LuCI Master (git-23.198.59743-991daf5) 本次不更新luci 1.6.0，使用上一版本的ipk（luci-app-mosdns_1.5.16_all.ipk），直接安装mosdns_5.3.3-1_x86_64.ipk，程序是可以顺利运行。 但是我更新luci-app-mosdns_1.6.0_all.ipk后报错，openwrt客户界面无mosdns，htop中也没mosdns的进程，具体安装情况如下： ***@***.***:/usr/share/temp# opkg install luci-app-mosdns_1.6.0_all.ipk Upgrading luci-app-mosdns on root from 1.5.16 to 1.6.0... Removing obsolete file /usr/lib/lua/luci/view/mosdns/mosdns_status.htm. Removing obsolete file /usr/lib/lua/luci/model/cbi/mosdns/update.lua. Removing obsolete file /www/luci-static/resources/mosdns/lib/codemirror.js. Removing obsolete file /www/luci-static/resources/mosdns/lib/codemirror.css. Removing obsolete file /www/luci-static/resources/mosdns/addon/fold/foldgutter.js. Removing obsolete file /usr/share/mosdns/default.yaml. Removing obsolete file /www/luci-static/resources/mosdns/theme/dracula.css. Removing obsolete file /www/luci-static/resources/mosdns/mode/yaml/yaml.js. Removing obsolete file /usr/lib/lua/luci/view/mosdns/mosdns_flush_cache.htm. Removing obsolete file /www/luci-static/resources/mosdns/addon/fold/foldgutter.css. Removing obsolete file /usr/lib/lua/luci/view/mosdns/mosdns_log.htm. Removing obsolete file /usr/lib/lua/luci/view/mosdns/mosdns_geo_update.htm. Removing obsolete file /usr/lib/lua/luci/view/mosdns/mosdns_editor.htm. Removing obsolete file /usr/lib/lua/luci/model/cbi/mosdns/basic.lua. Removing obsolete file /www/luci-static/resources/mosdns/addon/fold/indent-fold.js. Removing obsolete file /usr/lib/lua/luci/model/cbi/mosdns/rule_list.lua. Removing obsolete file /usr/lib/lua/luci/controller/mosdns.lua. Removing obsolete file /usr/lib/lua/luci/model/cbi/mosdns/log.lua. Removing obsolete file /www/luci-static/resources/mosdns/addon/fold/foldcode.js. Configuring luci-app-mosdns. Collected errors: resolve_conffiles: Existing conffile /etc/config/mosdns is different from the conffile in the new package. The new conffile will be placed at /etc/config/mosdns-opkg. resolve_conffiles: Existing conffile /etc/mosdns/rule/greylist.txt is different from the conffile in the new package. The new conffile will be placed at /etc/mosdns/rule/greylist.txt-opkg. resolve_conffiles: Existing conffile /etc/mosdns/rule/hosts.txt is different from the conffile in the new package. The new conffile will be placed at /etc/mosdns/rule/hosts.txt-opkg. resolve_conffiles: Existing conffile /etc/mosdns/rule/whitelist.txt is different from the conffile in the new package. The new conffile will be placed at /etc/mosdns/rule/whitelist.txt-opkg. 小白不知道哪里出了问题，暂时先强制把luci降级到1.5.16使用着。 等待大佬后续解答。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.

大佬，是这个: https://t.me/s/esirplayground?before=115

用大佬的luci 1.5.16是ok的，但1.6安装了好几次都不行，比较神奇

**Comment by Mrican** [comment]
> > 我没听说过有名字叫“高大全”的 OpenWrt 现在的 luci 只适用于 luci2 发自我的iPhone
> > […](#)
> > 在 2024年8月15日，14:52，Jasonzhang2023 _**@**_._**> 写道： ﻿ 首先感谢大佬这么快更新了5.3.3，最近几次大佬一更新我这边就下载.ipk到本地更新。 我用的是esir openwrt高大全: OpenWrt R23.7.7 GDQ V2[2023] Compiled by eSir / LuCI Master (git-23.198.59743-991daf5) 本次不更新luci 1.6.0，使用上一版本的ipk（luci-app-mosdns_1.5.16_all.ipk），直接安装mosdns_5.3.3-1_x86_64.ipk，程序是可以顺利运行。 但是我更新luci-app-mosdns_1.6.0_all.ipk后报错，openwrt客户界面无mosdns，htop中也没mosdns的进程，具体安装情况如下： _**@**_.**_:/usr/share/temp# opkg install luci-app-mosdns_1.6.0_all.ipk Upgrading luci-app-mosdns on root from 1.5.16 to 1.6.0... Removing obsolete file /usr/lib/lua/luci/view/mosdns/mosdns_status.htm. Removing obsolete file /usr/lib/lua/luci/model/cbi/mosdns/update.lua. Removing obsolete file /www/luci-static/resources/mosdns/lib/codemirror.js. Removing obsolete file /www/luci-static/resources/mosdns/lib/codemirror.css. Removing obsolete file /www/luci-static/resources/mosdns/addon/fold/foldgutter.js. Removing obsolete file /usr/share/mosdns/default.yaml. Removing obsolete file /www/luci-static/resources/mosdns/theme/dracula.css. Removing obsolete file /www/luci-static/resources/mosdns/mode/yaml/yaml.js. Removing obsolete file /usr/lib/lua/luci/view/mosdns/mosdns_flush_cache.htm. Removing obsolete file /www/luci-static/resources/mosdns/addon/fold/foldgutter.css. Removing obsolete file /usr/lib/lua/luci/view/mosdns/mosdns_log.htm. Removing obsolete file /usr/lib/lua/luci/view/mosdns/mosdns_geo_update.htm. Removing obsolete file /usr/lib/lua/luci/view/mosdns/mosdns_editor.htm. Removing obsolete file /usr/lib/lua/luci/model/cbi/mosdns/basic.lua. Removing obsolete file /www/luci-static/resources/mosdns/addon/fold/indent-fold.js. Removing obsolete file /usr/lib/lua/luci/model/cbi/mosdns/rule_list.lua. Removing obsolete file /usr/lib/lua/luci/controller/mosdns.lua. Removing obsolete file /usr/lib/lua/luci/model/cbi/mosdns/log.lua. Removing obsolete file /www/luci-static/resources/mosdns/addon/fold/foldcode.js. Configuring luci-app-mosdns. Collected errors: resolve_conffiles: Existing conffile /etc/config/mosdns is different from the conffile in the new package. The new conffile will be placed at /etc/config/mosdns-opkg. resolve_conffiles: Existing conffile /etc/mosdns/rule/greylist.txt is different from the conffile in the new package. The new conffile will be placed at /etc/mosdns/rule/greylist.txt-opkg. resolve_conffiles: Existing conffile /etc/mosdns/rule/hosts.txt is different from the conffile in the new package. The new conffile will be placed at /etc/mosdns/rule/hosts.txt-opkg. resolve_conffiles: Existing conffile /etc/mosdns/rule/whitelist.txt is different from the conffile in the new package. The new conffile will be placed at /etc/mosdns/rule/whitelist.txt-opkg. 小白不知道哪里出了问题，暂时先强制把luci降级到1.5.16使用着。 等待大佬后续解答。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.
> 
> 大佬，是这个: https://t.me/s/esirplayground?before=115
> 
> 用大佬的luci 1.5.16是ok的，但1.6安装了好几次都不行，比较神奇

大佬已说：“现在的 luci 只适用于 luci2。”  

问题在于你的openwrt是否支持luci2

**Comment by Jasonzhang2023** [comment]
> > > 我没听说过有名字叫“高大全”的 OpenWrt 现在的 luci 只适用于 luci2 发自我的iPhone
> > > […](#)
> > > 在 2024年8月15日，14:52，Jasonzhang2023 _**@**_._**> 写道： ﻿ 首先感谢大佬这么快更新了5.3.3，最近几次大佬一更新我这边就下载.ipk到本地更新。 我用的是esir openwrt高大全: OpenWrt R23.7.7 GDQ V2[2023] Compiled by eSir / LuCI Master (git-23.198.59743-991daf5) 本次不更新luci 1.6.0，使用上一版本的ipk（luci-app-mosdns_1.5.16_all.ipk），直接安装mosdns_5.3.3-1_x86_64.ipk，程序是可以顺利运行。 但是我更新luci-app-mosdns_1.6.0_all.ipk后报错，openwrt客户界面无mosdns，htop中也没mosdns的进程，具体安装情况如下： _**@**_.**_:/usr/share/temp# opkg install luci-app-mosdns_1.6.0_all.ipk Upgrading luci-app-mosdns on root from 1.5.16 to 1.6.0... Removing obsolete file /usr/lib/lua/luci/view/mosdns/mosdns_status.htm. Removing obsolete file /usr/lib/lua/luci/model/cbi/mosdns/update.lua. Removing obsolete file /www/luci-static/resources/mosdns/lib/codemirror.js. Removing obsolete file /www/luci-static/resources/mosdns/lib/codemirror.css. Removing obsolete file /www/luci-static/resources/mosdns/addon/fold/foldgutter.js. Removing obsolete file /usr/share/mosdns/default.yaml. Removing obsolete file /www/luci-static/resources/mosdns/theme/dracula.css. Removing obsolete file /www/luci-static/resources/mosdns/mode/yaml/yaml.js. Removing obsolete file /usr/lib/lua/luci/view/mosdns/mosdns_flush_cache.htm. Removing obsolete file /www/luci-static/resources/mosdns/addon/fold/foldgutter.css. Removing obsolete file /usr/lib/lua/luci/view/mosdns/mosdns_log.htm. Removing obsolete file /usr/lib/lua/luci/view/mosdns/mosdns_geo_update.htm. Removing obsolete file /usr/lib/lua/luci/view/mosdns/mosdns_editor.htm. Removing obsolete file /usr/lib/lua/luci/model/cbi/mosdns/basic.lua. Removing obsolete file /www/luci-static/resources/mosdns/addon/fold/indent-fold.js. Removing obsolete file /usr/lib/lua/luci/model/cbi/mosdns/rule_list.lua. Removing obsolete file /usr/lib/lua/luci/controller/mosdns.lua. Removing obsolete file /usr/lib/lua/luci/model/cbi/mosdns/log.lua. Removing obsolete file /www/luci-static/resources/mosdns/addon/fold/foldcode.js. Configuring luci-app-mosdns. Collected errors: resolve_conffiles: Existing conffile /etc/config/mosdns is different from the conffile in the new package. The new conffile will be placed at /etc/config/mosdns-opkg. resolve_conffiles: Existing conffile /etc/mosdns/rule/greylist.txt is different from the conffile in the new package. The new conffile will be placed at /etc/mosdns/rule/greylist.txt-opkg. resolve_conffiles: Existing conffile /etc/mosdns/rule/hosts.txt is different from the conffile in the new package. The new conffile will be placed at /etc/mosdns/rule/hosts.txt-opkg. resolve_conffiles: Existing conffile /etc/mosdns/rule/whitelist.txt is different from the conffile in the new package. The new conffile will be placed at /etc/mosdns/rule/whitelist.txt-opkg. 小白不知道哪里出了问题，暂时先强制把luci降级到1.5.16使用着。 等待大佬后续解答。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.
> > 
> > 
> > 大佬，是这个: https://t.me/s/esirplayground?before=115
> > 用大佬的luci 1.5.16是ok的，但1.6安装了好几次都不行，比较神奇
> 
> 大佬已说：“现在的 luci 只适用于 luci2。”
> 
> 问题在于你的openwrt是否支持luci2

请教一下，如何看openwrt是否支持luci2？
感谢大佬们！

**Comment by Mrican** [comment]
> 我没听说过有名字叫“高大全”的 OpenWrt 现在的 luci 只适用于 luci2 发自我的iPhone
> […](#)
> 在 2024年8月15日，14:52，Jasonzhang2023 ***@***.***> 写道： ﻿ 首先感谢大佬这么快更新了5.3.3，最近几次大佬一更新我这边就下载.ipk到本地更新。 我用的是esir openwrt高大全: OpenWrt R23.7.7 GDQ V2[2023] Compiled by eSir / LuCI Master (git-23.198.59743-991daf5) 本次不更新luci 1.6.0，使用上一版本的ipk（luci-app-mosdns_1.5.16_all.ipk），直接安装mosdns_5.3.3-1_x86_64.ipk，程序是可以顺利运行。 但是我更新luci-app-mosdns_1.6.0_all.ipk后报错，openwrt客户界面无mosdns，htop中也没mosdns的进程，具体安装情况如下： ***@***.***:/usr/share/temp# opkg install luci-app-mosdns_1.6.0_all.ipk Upgrading luci-app-mosdns on root from 1.5.16 to 1.6.0... Removing obsolete file /usr/lib/lua/luci/view/mosdns/mosdns_status.htm. Removing obsolete file /usr/lib/lua/luci/model/cbi/mosdns/update.lua. Removing obsolete file /www/luci-static/resources/mosdns/lib/codemirror.js. Removing obsolete file /www/luci-static/resources/mosdns/lib/codemirror.css. Removing obsolete file /www/luci-static/resources/mosdns/addon/fold/foldgutter.js. Removing obsolete file /usr/share/mosdns/default.yaml. Removing obsolete file /www/luci-static/resources/mosdns/theme/dracula.css. Removing obsolete file /www/luci-static/resources/mosdns/mode/yaml/yaml.js. Removing obsolete file /usr/lib/lua/luci/view/mosdns/mosdns_flush_cache.htm. Removing obsolete file /www/luci-static/resources/mosdns/addon/fold/foldgutter.css. Removing obsolete file /usr/lib/lua/luci/view/mosdns/mosdns_log.htm. Removing obsolete file /usr/lib/lua/luci/view/mosdns/mosdns_geo_update.htm. Removing obsolete file /usr/lib/lua/luci/view/mosdns/mosdns_editor.htm. Removing obsolete file /usr/lib/lua/luci/model/cbi/mosdns/basic.lua. Removing obsolete file /www/luci-static/resources/mosdns/addon/fold/indent-fold.js. Removing obsolete file /usr/lib/lua/luci/model/cbi/mosdns/rule_list.lua. Removing obsolete file /usr/lib/lua/luci/controller/mosdns.lua. Removing obsolete file /usr/lib/lua/luci/model/cbi/mosdns/log.lua. Removing obsolete file /www/luci-static/resources/mosdns/addon/fold/foldcode.js. Configuring luci-app-mosdns. Collected errors: resolve_conffiles: Existing conffile /etc/config/mosdns is different from the conffile in the new package. The new conffile will be placed at /etc/config/mosdns-opkg. resolve_conffiles: Existing conffile /etc/mosdns/rule/greylist.txt is different from the conffile in the new package. The new conffile will be placed at /etc/mosdns/rule/greylist.txt-opkg. resolve_conffiles: Existing conffile /etc/mosdns/rule/hosts.txt is different from the conffile in the new package. The new conffile will be placed at /etc/mosdns/rule/hosts.txt-opkg. resolve_conffiles: Existing conffile /etc/mosdns/rule/whitelist.txt is different from the conffile in the new package. The new conffile will be placed at /etc/mosdns/rule/whitelist.txt-opkg. 小白不知道哪里出了问题，暂时先强制把luci降级到1.5.16使用着。 等待大佬后续解答。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.

大佬，请问，可以安装些什么包，让openwrt支持Luci2？

**Comment by sbwml** [comment]
只能换固件。OpenWrt 21.02 以上的固件都是 LuCI2。

或者使用 mosdns 旧版本（lua）。

发自我的iPhone

**Comment by Jasonzhang2023** [comment]
那我就先用1.5.16，搭配5.3.3，运行流畅

**Comment by sbwml** [comment]
本来就没有必要更新。甚至我打算回退使用 v4 版本。重做 luci

**Comment by Jasonzhang2023** [comment]
> 本来就没有必要更新。甚至我打算回退使用 v4 版本。重做 luci

大佬说什么我都觉得是正确的！

**Comment by E78870** [comment]
同样的问题，可能真是这个问题，我使用的固件是基于19.07

**Comment by sbwml** [comment]
> 同样的问题，可能真是这个问题，我使用的固件是基于19.07

OpenWrt 19.07

![image](https://github.com/user-attachments/assets/218ffb1f-89d8-4b0e-8ee6-3c593e56a3f8)
![image](https://github.com/user-attachments/assets/c2d9c8d9-47ec-4eeb-8fe4-e35df3eae77c)

**Comment by sbwml** [comment]
这里最大的问题是你们说的 OpenWrt 和 我理解的 OpenWrt 是两种东西。

我理解的 OpenWrt：
https://github.com/openwrt/openwrt
https://openwrt.org/


你们理解的 OpenWrt：
https://github.com/这个大佬
https://github.com/那个大神
https://www.right.com.cn/

**Comment by E78870** [comment]
没法子，官方没有ipq6000的包，arm这些不像x86更新那么快。
WEB界面里提示为“OpenWrt R23.11.20 / LuCI 2023 branch (git-23.324.43812-6035f88)“，SSH欢迎界面和安装脚本提示19.07，我都是把版本检查注释了才装上的。现在只能直接改配置文件来用了，就当luci不存在。

**Comment by E78870** [comment]
> 这里最大的问题是你们说的 OpenWrt 和 我理解的 OpenWrt 是两种东西。
> 
> 我理解的 OpenWrt： https://github.com/openwrt/openwrt https://openwrt.org/
> 
> 你们理解的 OpenWrt： [https://github.com/这个大佬](https://github.com/%E8%BF%99%E4%B8%AA%E5%A4%A7%E4%BD%AC) [https://github.com/那个大神](https://github.com/%E9%82%A3%E4%B8%AA%E5%A4%A7%E7%A5%9E) https://www.right.com.cn/

没法子，官方没有ipq6000的包，arm这些不像x86更新那么快。
WEB界面里提示为“OpenWrt R23.11.20 / LuCI 2023 branch (git-23.324.43812-6035f88)“，SSH欢迎界面和安装脚本提示19.07，我都是把版本检查注释了才装上的。现在只能直接改配置文件来用了，就当luci不存在。

**Comment by sbwml** [comment]
> 是把版本检查注释了才装上的。现在只能直接改配置文件来用了，就当luci不存在。

还是那句，这里最大的问题是你们说的 OpenWrt 和 我理解的 OpenWrt 是两种东西。

不清楚自己路由器的版本的情况下，安装脚本它是知道的，它会告诉你，你这个是不受支持的版本。那么你强行去安装    自然不可能会工作。

但是你依然可以选择旧版本来安装，它将会继续正常地工作在 LUA 环境中。不过怎么去安装旧版本，这也是挺难的，还是不推荐。


---------

所以推荐 404 佬的 luci：https://github.com/QiuSimons/openwrt-mos

404 这个 luci app 是 lua语言，同时支持一件应用 mosdns 到其它科学插件，推荐等级 5⭐
