### ISSUE TITLE
跟进时代的步伐，感谢重写新版 LuCI，符合 OpenWrt 开发路程，但有改进的地方！

### ISSUE THREAD

**Issue by qingtian110** [sbwml/luci-app-mosdns#239]
新版 LuCI 比原来的旧版本（LUA）自定义配置编辑器少了个高亮代码的显示。

因为 YAML 的代码递进非常的严格，多一个或少一个空格都会影响配置的可用性，有代码高亮的支持可以清晰看到代码格式是否标准。

这是一个很实用的东西，希望能重新添加到新的 LuCI 中，或以扩展包的形式提供支持，这样用户就可以自行选择是否需要代码高亮了。

-------

新版本：
![image](https://github.com/user-attachments/assets/3ca206fc-5351-4441-9ab9-dd7cf80d4221)

旧版本：
![image](https://github.com/user-attachments/assets/e9e39ed9-fda1-42a1-8ca8-60210501065b)

**Comment by Rain113113** [comment]
f大的openwrt  直接没有UI了  程序是运行起的

**Comment by qingtian110** [comment]
> f大的openwrt  直接没有UI了  程序是运行起的

那是因为你用的固件luci源码太旧了。luci1 是五六年前的了

**Comment by kdatamr** [comment]
安装后 服务里看不到菜单

**Comment by lixinlkmn2004** [comment]
您好，我想问一下怎样通过ssh安装v5.3.1的旧版本呢，我的openwrt版本低通过ssh命令安装不了了，麻烦您啦

**Comment by qingtian110** [comment]
> 您好，我想问一下怎样通过ssh安装v5.3.1的旧版本呢，我的openwrt版本低通过ssh命令安装不了了，麻烦您啦

不是有 ipk 安装包吗  https://github.com/sbwml/luci-app-mosdns/releases/tag/v5.3.1

**Comment by lixinlkmn2004** [comment]
> > 您好，我想问一下怎样通过ssh安装v5.3.1的旧版本呢，我的openwrt版本低通过ssh命令安装不了了，麻烦您啦
> 
> 不是有 ipk 安装包吗 https://github.com/sbwml/luci-app-mosdns/releases/tag/v5.3.1

安装的时候报错，装不上，用ssh命令就可以，可能是我安装的方法不对吧，难道是安装顺序吗？您可以提供一下ipk安装的正确方法吗？我的设备是一台红米ax6s，谢谢您啦，辛苦了

**Comment by qingtian110** [comment]
顺序

1、v2dat
2、v2ray-geoip
3、v2ray-geosite
3、mosdns
4、luci-app-mosdns

如果这个顺序安装不出来，那就是你下载错了架构，如果连自己的设备是什么架构都不知道，那就白搭，不用装它了，因为你将会永远安装不上。

**Comment by lixinlkmn2004** [comment]
> 顺序
> 
> 1、v2dat 2、v2ray-geoip 3、v2ray-geosite 3、mosdns 4、luci-app-mosdns
> 
> 如果这个顺序安装不出来，那就是你下载错了架构，如果连自己的设备是什么架构都不知道，那就白搭，不用装它了，因为你将会永远安装不上。

感谢您的解答，我已经安装好了，再次感谢您的帮助。

**Comment by sbwml** [comment]
这个难度系数有点高，待我研究研究

**Comment by sbwml** [comment]
https://github.com/sbwml/luci-app-mosdns/commit/a0f7f2a583e23289f495e2a2465abbddb9c6633a

![QQ_1724088707141](https://github.com/user-attachments/assets/709d2d3c-df0f-47ff-b135-16d39179b666)

**Comment by yyysuo** [comment]
> 这个难度系数有点高，待我研究研究

大佬，发现您对mosdns做了3个补丁，能介绍一下吗。
https://github.com/sbwml/luci-app-mosdns/tree/v5/mosdns/patches

**Comment by sbwml** [comment]
> > 这个难度系数有点高，待我研究研究
> 
> 大佬，发现您对mosdns做了3个补丁，能介绍一下吗。 https://github.com/sbwml/luci-app-mosdns/tree/v5/mosdns/patches

没有参考价值，是个可有可无的存在。仅仅是为了配合这里的 luci app

**Comment by qiangweijian** [comment]
> > 顺序
> > 1、v2dat 2、v2ray-geoip 3、v2ray-geosite 3、mosdns 4、luci-app-mosdns
> > 如果这个顺序安装不出来，那就是你下载错了架构，如果连自己的设备是什么架构都不知道，那就白搭，不用装了，因为你将永远安装不上。
> 
> 感谢您的解答，我已经安装好了，再次感谢您的帮助。

请问下是咋装上的呀同样的问题
