### ISSUE TITLE
更新版本后无法启动Mosdns

### ISSUE THREAD

**Issue by fonlan** [sbwml/luci-app-mosdns#24]
系统日志有如下打印：
`Tue Oct 25 16:01:55 2022 daemon.err procd: Got unexpected signal 1`

错误发生在/usr/share/mosdns/mosdns.sh，疑似configuration里缺少adlist_update字段导致

**Comment by sbwml** [comment]
修改一下这个文件 `/etc/config/mosdns`
```
config mosdns 'mosdns'
```
改成
```
config mosdns 'config'
```

为了满足日后更新做的变化，配置文件重命名了，而这个配置文件更新mosdns 他不会被更新

**Comment by fonlan** [comment]
测试有效，多谢

**Comment by sbwml** [comment]
很好
