### ISSUE TITLE
遇到一个很奇怪的现象用mosdns默认配置+passwall 隔一段时间会断网,是光网断网

### ISSUE THREAD

**Issue by hy817120** [sbwml/luci-app-mosdns#240]
我并没有做什么更改,光猫断网当时没有截图,家里人等着上网,就重启了 不过第一时间看的信息是
光猫上所有的连接状态都是未连接, 包括iptv 和电话,都是全部未连接
这种情况,上个月也出现过一次, 这次是前几天才重新配置了mosdns+passwall
光猫当时也重启了, 也就是说间隔时间也就那么几天时间.
当时远程dns服务器是添加的自定义, cloudlfare doh  dns  和google doh
bootstrap 服务器选的是内置的 cloudflare的dns

![1](https://github.com/user-attachments/assets/c2a535f6-3f90-4c42-8364-505415c5cc84)
![2](https://github.com/user-attachments/assets/b41f9941-33fc-4446-870d-9462ce1800d9)
![3](https://github.com/user-attachments/assets/5355ec3a-ebbc-4d24-9105-31b90c140426)

**Comment by hy817120** [comment]
不是很清楚光猫直接全部断网的原因, 但是感觉可能跟mosdns +passwall的设置有关,
我的mosdns  如果日志跳到信息栏.过不了多久就会出现很多的报错,但并不影响使用. 
这种光猫断网这是出现第二次,   以前从未出现过, 
我在想是否是太多的dns错误,导致运营商风控进而全部断网,?

**Comment by sbwml** [comment]
以你描述的情况，mosdns & passwall 导致的可能性极低。即使你没有使用 mosdns & passwall，断开链接的现象还是会出现。

**Comment by liangjian199** [comment]
最好单用dnsmasq
