### ISSUE TITLE
安装luci1.6.3版和1.6.4版，在服务菜单下找不到mosdns

### ISSUE THREAD

**Issue by szhhq** [sbwml/luci-app-mosdns#242]
如题。倒是不影响mosdns的运行。

**Comment by sbwml** [comment]
新版本luci 不支持 openwrt 18.06，最低要求的版本是 openwrt-21.02，对于 openwrt-18.06 可以使用旧版本 https://github.com/sbwml/luci-app-mosdns/releases/tag/v5.3.1

**Comment by szhhq** [comment]
固件版本 OpenWrt R2024.04.08 / LuCI Master (git-24.096.15376-b029f06)
内核版本 5.15.164-flippy-91+o
这个不能支持新版本么？

**Comment by sbwml** [comment]
你这个就是op18.06

发自我的iPhone

**Comment by lengfwong** [comment]
不一定是18.06,他用的似乎是coolsnowwolf/lede的source，这个源修改了一些系统软件，可能没有luci2，我之前用这个源编译就发现只能选fw3,不能用fw4,后来改了官方的源。

**Comment by sbwml** [comment]
> 不一定是18.06,他用的似乎是coolsnowwolf/lede的source，这个源修改了一些系统软件，可能没有luci2，我之前用这个源编译就发现只能选fw3,不能用fw4,后来改了官方的源。

目前任何使用纯 LUA 的 LuCI，都是 based 18.06 luci。

自 openwrt-19.x 起才支持 luci2（JS）

**Comment by lengfwong** [comment]
> 固件版本 OpenWrt R2024.04.08 / LuCI Master (git-24.096.15376-b029f06) 内核版本 5.15.164-flippy-91+o 这个不能支持新版本么？

这个固件似乎是从coolsnowwolf/lede编译来的，这个跟官方的比起来缺了些插件：
这个是coolsnowwolf源的界面：
![image](https://github.com/user-attachments/assets/b5cc4c8f-6034-4b06-afd9-c9fca7887463)
下面这个是官方git.openwrt.org源的界面：
![image](https://github.com/user-attachments/assets/dd172f7c-42a6-4567-a790-d3906191f064)

**Comment by szhhq** [comment]
两位大神讨论的内容已经超出了我能理解的范围了。
我刷的固件是这个 https://t.me/openwrt_flippy/5134 ，然后用内置的晶晨宝盒更新固件和内核到现在用的版本。目前的版本应该是停止维护了，有几个月更新不到新版本了。因为我也没有新的需求，所有也没有去刷高版本的固件，只有时候更新一下常用的软件。你们有时间、精力的话可以研究一下。

**Comment by sbwml** [comment]
> 你们有时间、精力的话可以研究一下。

没啥好研究的，最新版安装上没显示菜单 = luci1，即 openwrt-18.06 的luci，这类固件都不再支持使用。

你也可以直接理解成 这里的  luci-app-mosdns  更新就是为了不再支持旧版固件界面。

但是不管 1.6 还是  1.5   实际上他们的实现的东西是完全一致。有关 luci 方面问题不再回答
