### ISSUE TITLE
反馈一个情况：luci 1.6.4 自定义配置保存不起效

### ISSUE THREAD

**Issue by Mrican** [sbwml/luci-app-mosdns#243]
luci 1.6.4 自定义配置保存不起效，修改可以，点保存还是原来的。luci 1.6.0 和 luci 1.6.3没有这问题。

我是用winscp找到 /etc/mosdns/config_custom.yaml  修改保存的，不影响使用，只是不方便。

改hosts是可以保存的。

另外luci 1.6.3 和 luci 1.6.4 的代码均没有高亮，我一般是从在本地的编辑器直接复制过去。

系统是openwrt 21.02

**Comment by sbwml** [comment]
了解，调整下延时加载codemirror 的事情。晚点吧

发自我的iPhone

**Comment by sbwml** [comment]
你把这个文件内容覆盖到 `/www/luci-static/resources/view/mosdns/basic.js`，看看能不能解决

[basic.js.txt](https://github.com/user-attachments/files/16735254/basic.js.txt)

**Comment by Mrican** [comment]
> 你把这个文件内容覆盖到 `/www/luci-static/resources/view/mosdns/basic.js`，看看能不能解决
> 
> [basic.js.txt](https://github.com/user-attachments/files/16735254/basic.js.txt)

OK了，两个问题都解决了

**Comment by sbwml** [comment]
我有个事情想咨询一下，你使用的 OpenWrt 有没有使用 `luci-theme-argon` 主题？如果有，能截图看一下你的 mosdns 自定义配置代码高亮样式是否有受主题样式的影响而出现异常？（比如行距、编辑框大小，字体大小、整体变形等）

![image](https://github.com/user-attachments/assets/b27c86d8-ee3f-4798-bd20-aa883c0b788e)

**Comment by Mrican** [comment]
![Screenshot 2024-08-24 at 19-58-24 GL-MT3000 -- LuCI --- GL-MT3000 - 软件包 - LuCI](https://github.com/user-attachments/assets/f25e0a76-8586-4e06-b91a-759309e34fb5)

我一般默认主题

![Screenshot 2024-08-24 at 20-05-40 GL-MT3000 - 基本设置 - LuCI](https://github.com/user-attachments/assets/ee6bc892-e65d-4c60-b71b-eaaed922071e)
