### ISSUE TITLE
更新新版luci后，使用内置预设的情况下黑名单无法保存

### ISSUE THREAD

**Issue by INoRi-YoRha** [sbwml/luci-app-mosdns#244]
内核版本6.6.41，23.0.5.4分支

从1.6.0版本开始每个更新都试过了，1.6.5更新后也不行，更新后之前保存好的黑名单会消失，再次修改编辑，会提示 无法保存内容：XHR request aborted by browser

试过完全卸载重新安装也不行，依然无法保存，同样会会提示 无法保存内容：XHR request aborted by browser

**Comment by sbwml** [comment]
测试正常保存并工作，你可以尝试下刷新浏览器缓存，或无痕模式测试下

![image](https://github.com/user-attachments/assets/0756a6ff-2dcb-4ab6-938d-9a3dd84ba0fe)
![image](https://github.com/user-attachments/assets/be3ae330-5f22-4864-83af-67032bce622a)
![image](https://github.com/user-attachments/assets/392ff774-0e1b-45c8-83b3-2440050e1b7f)

**Comment by INoRi-YoRha** [comment]
无痕模式，清除缓存，用winscp登录直接改txt文件，都不行，黑名单那里就是空白，什么都不显示，如果编辑就会提示无法保存XHR request aborted by browser
这看来是我个人情况，我先用着旧版的吧，等下次编译的时候再试试新版
