### ISSUE TITLE
V5.3.3在线安装，LuCI报错

### ISSUE THREAD

**Issue by WukongMaster** [sbwml/luci-app-mosdns#246]
V5.3.3在线安装报错如下：
OpenWrt LuCI version is not supports.
Minimum OpenWrt Version: openwrt-21.02 or latest

版本：OpenWrt R24.8.1 / LuCI Master (git-24.182.36151-66d29de)
内核：6.6.46

V5.3.1和以前版本，一键安装都没问题呢，5.3.3是什么原因才报错呢，LuCI明明大于21.02了。

**Comment by sbwml** [comment]
不支持 lede （openwrt-18.06）

**Comment by WukongMaster** [comment]
> 不支持 lede （openwrt-18.06）

我是最新的24.8版本，不是18.06哈

**Comment by sbwml** [comment]
我没法跟你解释些什么。简单举例吧，我在6年前 fork 了 openwrt-18.06 延用至今，我把版本号定义成  24.09，那么它到底还是 18.06  还是被我改后的 24.09 呢？

**Comment by Jio0oiJ** [comment]
问下5.3.1可以用18.06吗,设备只有lean的18.06支持，无奈只能用这个

**Comment by sbwml** [comment]
> 问下5.3.1可以用18.06吗,设备只有lean的18.06支持，无奈只能用这个

可以，也只能用这个版本或更老的版本
