### ISSUE TITLE
请问，这个跟404佬的mosdns有啥区别呢？

### ISSUE THREAD

**Issue by jiaoting** [sbwml/luci-app-mosdns#247]
404佬 mosdns：https://github.com/QiuSimons/openwrt-mos
我看了一下，好像差不多，请问有什么区别吗？

**Comment by sbwml** [comment]
404 佬的要更好用，支持科学工具一键设置 mosdns，并兼容旧版 OpenWrt LuCI。

推荐指数：⭐⭐⭐⭐⭐

**Comment by lengfwong** [comment]
> 404 佬的要更好用，支持科学工具一键设置 mosdns，并兼容旧版 OpenWrt LuCI。
> 
> 推荐指数：⭐⭐⭐⭐⭐

谦虚了，我之前试用过一次404的，忘了是什么原因回来的，就一直用你的自定义配置，甚至把mosdns的启动文件里cron注释掉了，自己在OP Schedule 加的每隔一天更新一次。

**Comment by jiaoting** [comment]
用了，发现还是你的好用。。。。哈哈哈哈



在 2024-09-05 00:20:47，"lengfwong" ***@***.***> 写道：

404 佬的要更好用，支持科学工具一键设置 mosdns，并兼容旧版 OpenWrt LuCI。

推荐指数：⭐⭐⭐⭐⭐

谦虚了，我之前使用过一次404的，忘了是什么原因回来的，就一直用你的自定义配置，甚至把mosdns的启动文件里cron注释掉了，自己在OP Schedule 加的每隔一天更新一次。

**Comment by jiaoting** [comment]
而且，404已经好久没更新了



在 2024-09-05 00:20:47，"lengfwong" ***@***.***> 写道：

404 佬的要更好用，支持科学工具一键设置 mosdns，并兼容旧版 OpenWrt LuCI。

推荐指数：⭐⭐⭐⭐⭐

谦虚了，我之前使用过一次404的，忘了是什么原因回来的，就一直用你的自定义配置，甚至把mosdns的启动文件里cron注释掉了，自己在OP Schedule 加的每隔一天更新一次。
