### ISSUE TITLE
能否增加自定义geo更新地址

### ISSUE THREAD

**Issue by jiaoting** [sbwml/luci-app-mosdns#248]
我使用了https://github.com/Loyalsoldier/v2ray-rules-dat作为passwall的geo数据源，这里面单独增加了几个分类：

> 新增类别（方便有特殊需求的用户使用）：
> geoip:cloudflare
> geoip:cloudfront
> geoip:facebook
> geoip:fastly
> geoip:google
> geoip:netflix
> geoip:telegram
> geoip:twitter

但是用mosdns更新geo后，会提示无法找到这几个分类，我猜测应该是更新数据源不一样，mosdns的自带数据源没有这个分类，想问问能否增加自定义geo数据源的功能呢？感谢

**Comment by sbwml** [comment]
Add in https://github.com/sbwml/luci-app-mosdns/commit/49e5a0dfb00dbdc7f5b60aad56575d9e5f76789f
