### ISSUE TITLE
数据库更新失败

### ISSUE THREAD

**Issue by YnSen** [sbwml/luci-app-mosdns#25]
openwrt主路由模式，能正常访问国内和外网（国外），但是openwrt中更新数据库失败，显示更新失败，请检查网络状态
mosdns为最上层dns解析，没有勾选启用 DNS 转发
adguardhome使用mosdns的5335的端口，使用adguardhome是为了看dns解析日志
openclash的dns使用adguardhome的553端口，并启用本地 DNS 劫持
openwrt网络下的DHCP/DNS未勾选DNS 重定向
![图片_7](https://user-images.githubusercontent.com/65432445/198755530-ba495493-9e79-4b87-abf8-c42abb01c788.Png)
![图片_8](https://user-images.githubusercontent.com/65432445/198755664-1a4751e8-0577-4b5c-8048-4b1816ae09c8.Png)
![图片_9](https://user-images.githubusercontent.com/65432445/198755732-0083b451-3fc7-4094-a70c-b2c1d9153716.Png)
![图片_9](https://user-i
![图片_11](https://user-images.githubusercontent.com/65432445/198757153-4bf89bc2-56d7-4045-92ad-822ddfdaf3ce.Png)
mages.githubuserc
![图片_12](https://user-images.githubusercontent.com/65432445/198757229-b90bf39d-cc5d-43cd-873a-319ae95d37b0.Png)
ontent.com/65432445
![图片_13](https://user-images.githubusercontent.com/65432445/198757427-bdd489ad-6577-4d9a-b751-61bff9a99a68.Png)
/198756778-1f2b8
![图片_14](https://user-images.githubusercontent.com/65432445/198757998-4bd15a68-5f91-4b76-9cf9-fabcc0651966.Png)
c6d-e441-4a7e-8cfc-0a5678430d47.Png)
![图片_15](https://user-images.githubusercontent.com/65432445/198758047-3bae34e7-e7fa-4a4c-831a-9577d9e617f6.Png)

**Comment by sbwml** [comment]
### 很长，很复杂，作为小白表示看不懂

能不能更新数据库取决于mosdns 所在的网络有没有正常下载这两个文件（即使无法下载，我也完全帮不上你）

当系统网络能访问 http://www.google.com/generate_204 的情况下，数据库会使用这两个地址

https://github.com/Loyalsoldier/v2ray-rules-dat/releases/latest/download/geoip.dat
https://github.com/Loyalsoldier/v2ray-rules-dat/releases/latest/download/geosite.dat

否则使用

https://github.cooluc.com/https://github.com/Loyalsoldier/v2ray-rules-dat/releases/latest/download/geoip.dat
https://github.cooluc.com/https://github.com/Loyalsoldier/v2ray-rules-dat/releases/latest/download/geosite.dat


数据库更新所做的操作   https://github.com/sbwml/luci-app-mosdns/blob/master/luci-app-mosdns/root/usr/share/mosdns/mosdns.sh#L54

**Comment by YnSen** [comment]
> ### 很长，很复杂，作为小白表示看不懂
> 能不能更新数据库取决于mosdns 所在的网络有没有正常下载这两个文件（即使无法下载，我也完全帮不上你）
> 
> 当系统网络能访问 http://www.google.com/generate_204 的情况下，数据库会使用这两个地址
> 
> https://github.com/Loyalsoldier/v2ray-rules-dat/releases/latest/download/geoip.dat https://github.com/Loyalsoldier/v2ray-rules-dat/releases/latest/download/geosite.dat
> 
> 否则使用
> 
> https://github.cooluc.com/https://github.com/Loyalsoldier/v2ray-rules-dat/releases/latest/download/geoip.dat https://github.cooluc.com/https://github.com/Loyalsoldier/v2ray-rules-dat/releases/latest/download/geosite.dat
> 
> 数据库更新所做的操作 https://github.com/sbwml/luci-app-mosdns/blob/master/luci-app-mosdns/root/usr/share/mosdns/mosdns.sh#L54
感谢大佬回复，本来想tg群里问的，但发现没找到你，我是看了/usr/share/mosdns/mosdns.sh才知道github.cooluc.com和那个
https://github.com/Loyalsoldier/v2ray-rules-dat/releases/latest/download/geoip.dat https://github.com/Loyalsoldier/v2ray-rules-dat/releases链接的，试了一下，开代理显示更新失败，但是不开代理就一直显示正在更新(按钮一直灰色)，可能是我dns有问题吧，

root@ImmortalWrt:~# nslookup baidu.com
Server:         127.0.0.1
Address:        127.0.0.1#53

Name:      baidu.com
Address 1: 39.156.66.10
Address 2: 110.242.68.66
*** Can't find baidu.com: No answer

**Comment by YnSen** [comment]
刷了新固件编译进去的mosdns，上边是手动安装的(依赖齐全)，
为了测试我先删除geoip.dat和geosite.dat
很奇怪，不知道为啥显示更新失败实际更新成功了
![图片_18](https://user-images.githubusercontent.com/65432445/198816423-150cbf9f-32e2-4a32-8bc0-b61429dee7c1.Png)
![图片_19](https://user-images.githubusercontent.com/65432445/198816472-6a8241e2-0441-4125-878a-ee1b8b3a9532.Png)
![图片_20](https://user-images.githubusercontent.com/65432445/198816475-6c72f3ca-55e8-4fa0-9c5d-206947583f4d.Png)

**Comment by edmondfr** [comment]
同样的问题。手动更新，提示更新失败。查看文件变动时间，实际上已经更新成功。另外还有一个小问题就是日志的时间显示不正确，晚了8小时。

**Comment by YnSen** [comment]
> 对于openwrt mosdns 日志时区不对的问题 可以参考以前我在mosdns 回复过的 issues [https://github.com/IrineSistiana/mosdns/issues/438#issuecomment-1192506130，这并不是什么错误，按openwrt](https://github.com/IrineSistiana/mosdns/issues/438#issuecomment-1192506130%EF%BC%8C%E8%BF%99%E5%B9%B6%E4%B8%8D%E6%98%AF%E4%BB%80%E4%B9%88%E9%94%99%E8%AF%AF%EF%BC%8C%E6%8C%89openwrt) 的轻量化来看的话，我也不会让mosdns luci 去捆绑这方面的包
> 
> 至于数据库更新失败，我这边测试了很多遍确实没能复现 ![1](https://user-images.githubusercontent.com/16485166/198861734-6e7dad27-ae8c-4047-a524-c0e7a818fa97.png)
> 
> 至于为什么会显示 “更新失败” ，文件却有被成功更新，我猜测是文件下载时间超出openwrt luci 的默认超时时间，更新操作没有正确返回 0 的退出值。具体是什么原因，目前无法正确判断，你们能提供的信息太少了
> 
> 我需要知道的一些事情：
> 
> * 手动更新操作前，是否弃用了dns 广告拦截（如果有，关闭它是否能正常更新
> * 通过终端命令更新执行的结果（附上终端所有内容
>   ```shell
>   /usr/share/mosdns/mosdns.sh geodata; echo $?
>   ```

用的immortalwrt的21.02.3分支编译的固件
安装zoneinfo-asia后，在luci界面更新还是显示失败

执行结果：👇
root@ImmortalWrt:~# /usr/share/mosdns/mosdns.sh geodata; echo $?
Downloading https://github.cooluc.com/https://github.com/Loyalsoldier/v2ray-rules-dat/releases/latest/download/geoip.dat
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   117  100   117    0     0    217      0 --:--:-- --:--:-- --:--:--   217
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   123  100   123    0     0    112      0  0:00:01  0:00:01 --:--:--   112
100 9771k  100 9771k    0     0  2963k      0  0:00:03  0:00:03 --:--:-- 6817k
Downloading https://github.cooluc.com/https://github.com/Loyalsoldier/v2ray-rules-dat/releases/latest/download/geosite.dat
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   119  100   119    0     0    244      0 --:--:-- --:--:-- --:--:--   244
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   125  100   125    0     0    114      0  0:00:01  0:00:01 --:--:--   114
100 4978k  100 4978k    0     0  1892k      0  0:00:02  0:00:02 --:--:-- 5843k
grep: /tmp/tmp.CIcdLk/geoip.dat: binary file matches
1

![图片_21](https://user-images.githubusercontent.com/65432445/198862922-702b8610-da46-4a4a-a131-5d481719f790.Png)

**Comment by sbwml** [comment]
行，我知道问题在哪了

**Comment by YnSen** [comment]
> 行，我知道问题在哪了

大佬用你更新的那个mosdns.sh脚本后，luci界面的日志什么都不显示了，点击检查并更新直接显示更新失败，请检查网络状态

执行上面那个命令的结果👇
root@ImmortalWrt:~# /usr/share/mosdns/mosdns.sh geodata; echo $?
/usr/share/mosdns/mosdns.sh: line 85: syntax error: unterminated quoted string
2

**Comment by sbwml** [comment]
下载最后一次提交的，最开始修改的时候多了个错误字符

**Comment by sbwml** [comment]
有些事情发生得太尴尬了，你可能需要下载这个commit的文件去替换掉

https://github.com/sbwml/luci-app-mosdns/blob/6384f745ecbac507b44722ef0a7ef8fdacc008fc/luci-app-mosdns/root/usr/share/mosdns/mosdns.sh

**Comment by YnSen** [comment]
> 有些事情发生得太尴尬了，你可能需要下载这个commit的文件去替换掉
> 
> https://github.com/sbwml/luci-app-mosdns/blob/6384f745ecbac507b44722ef0a7ef8fdacc008fc/luci-app-mosdns/root/usr/share/mosdns/mosdns.sh

好的我重新拉源码编译

**Comment by sbwml** [comment]
不用编译的啊。。。直接换掉路由器上的这个文件 就好了

**Comment by YnSen** [comment]
> 不用编译的啊。。。直接换掉路由器上的这个文件 就好了

我编译时的包忘改了
git clone https://github.com/sbwml/v2ray-geodata package/geodata
然后immoralwrt里也有v2ray-geodata
我直接复制到feeds/package/net下，就存在两个geodata，不知道会不会影响插件，所以我改了重新编译下

**Comment by sbwml** [comment]
如果你要让固件默认能使用mosdns ，你只能使用这个库  https://github.com/sbwml/v2ray-geodata

**Comment by YnSen** [comment]
> 如果你要让固件默认能使用mosdns ，你只能使用这个库 https://github.com/sbwml/v2ray-geodata

所以我现在把immortalwrt里feeds/packages/net下的那个v2ray-geodata删掉了，现在只放了你的v2ray-geodata
