### ISSUE TITLE
提个bug，开启mosdns后，出现推特照片无法显示

### ISSUE THREAD

**Issue by jiaoting** [sbwml/luci-app-mosdns#250]
用passwall自带的chinadns-ng就没问题，挺奇怪的，日志里面也没有显示

**Comment by qingtian110** [comment]
假的。要么就是有什么规则误拦截

![image](https://github.com/user-attachments/assets/8172acb9-9322-4bfb-b376-2f30fd03e172)
![image](https://github.com/user-attachments/assets/1d54556f-15d5-4c32-b8e5-f5e4c30cedf4)
