### ISSUE TITLE
自定义nameserver在部分终端上无法使用

### ISSUE THREAD

**Issue by strayedstar** [sbwml/luci-app-mosdns#251]
在安卓/iOS设备上,只能填入nameserver,无法提交,因为离开输入框以后输入法就会退出

**Comment by sbwml** [comment]
这是你需要解决的问题，不是我需要解决的问题。

虽然我没有安卓，也没有iOS，但是我猜测输入法应该都有回车按钮

**Comment by strayedstar** [comment]
因为输入法的回车是提交,提交以后就会离开输入框,就无法使用回车去进一步应用...... ---- 回复的原邮件 ---- 发件人 ***@***.***> 日期 2024年09月06日 20:58 收件人 ***@***.***> 抄送至 ***@***.***>***@***.***> 主题 Re: [sbwml/luci-app-mosdns] 自定义nameserver在部分终端上无法使用 (Issue #251) 这是你需要解决的问题，不是我需要解决的问题。 虽然我没有安卓，也没有iOS，但是我猜测输入法应该都有回车按钮 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by sbwml** [comment]
![RPReplay_Final1725627792 00_00_00-00_00_30](https://github.com/user-attachments/assets/820c7905-d14c-4869-9b68-cfca3fa9bc4e)

**Comment by strayedstar** [comment]
Uploading Screenrecorder-2024-09-06-21-12-01-318.mp4…

**Comment by strayedstar** [comment]
https://github.com/user-attachments/assets/bd2bccef-83d5-47d3-85cc-a72e70c9b878
