### ISSUE TITLE
dns优先级问题

### ISSUE THREAD

**Issue by mq00fc** [sbwml/luci-app-mosdns#256]
随着IPV6的普及，是否可以考虑增加优先ipv6的选择？无论是远程还是国内，谢谢

**Comment by sbwml** [comment]
你本地支持 IPv6，并且访问站点也支持 IPv6，你会发现浏览器其实默认就是优先使用 IPv6 地址进行访问。

所以在 mosdns 做 prefer 基本没有意义。

**Comment by mq00fc** [comment]
> 你本地支持 IPv6，并且访问站点也支持 IPv6，你会发现浏览器其实默认就是优先使用 IPv6 地址进行访问。
> 
> 所以在 mosdns 做 prefer 基本没有意义。

那看来是我调整了优先级了原因，不好意思感谢您的回复
