### ISSUE TITLE
下载宝安装mosdns做dns服务器无法解析域名

### ISSUE THREAD

**Issue by daivinding** [sbwml/luci-app-mosdns#259]
下载宝刷的ImmortalWrt 23.05.3 r27917-81a1f98d5b / LuCI openwrt-23.05 branch git-24.092.44091-d24c2e3
用脚本命令安装的mosdns，关闭了防火墙、dnsmasq。
主路由器负责网管，下载宝只做DNS解析，能运行，但是无法解析地址这个是啥原因？？

**Comment by sbwml** [comment]
它需要依赖 dnsmasq 服务来工作。如果不使用 dnsmasq，你可以尝试把 mosdns 的监听端口改成 53，并且取消 DNS 转发 选项。

如果问题没有得到改善，我也没有其它法子了。

**Comment by daivinding** [comment]
我再试一下把。我把dnsmasq直接disable了，把mosdns直接开53。

**Comment by daivinding** [comment]
搞定了。还是需要开dnsmasq的。53——dnsmasq——5335——moddns。
之前，disable了dnsmasq。53——mosdns，直接无法解析。广告源也是用的你家的。直接一体化了。

**Comment by sbwml** [comment]
牛逼，你是唯一一个自己解决问题的人。
