### ISSUE TITLE
[Feature request] Cloudflare自选IP能否添加白名单功能

### ISSUE THREAD

**Issue by rumianoesa** [sbwml/luci-app-mosdns#260]
Cloudflare自选IP能否添加白名单功能，让不想使用自选IP的域名使用原本的解析结果，例如证书签署域名acme-v02.api.letsencrypt.org
尝试了将acme-v02.api.letsencrypt.org加入白名单和hosts都没有效果，Cloudflare自选IP优先级更高

目前采用的临时解决办法是在openwrt的/etc/config/dhcp添加
list server '/acme-v02.api.letsencrypt.org/223.5.5.5'
指定一条比mosdns优先级更高的转发
但是mosdns插件启动时会覆盖这条设置

**Comment by sbwml** [comment]
https://github.com/sbwml/luci-app-mosdns/commit/ab4c2a07879f05c242bd89f49e7b8369f1a1f9ef 该提交之后，**Cloudflare 自选 IP** 会排除规则列表 **白名单、灰名单、流媒体** 中的域名。把不希望被 自选IP 覆盖的域名可以添加到这三个列表其中之一，它会正常使用对应的上游 DNS 进行解析。
