### ISSUE TITLE
[Feature request]能否将bootstrap dns也支持自定义

### ISSUE THREAD

**Issue by KyonCN** [sbwml/luci-app-mosdns#262]
如题，因为校园网内的基于udp的dns请求都会被拦截并且不会返回任何结果，所以只能使用自动分配的内网dns来作为bootstrap dns。
虽然通过自定义配置能够实现，如果现在的界面上能够支持就更好了。非常感谢作者。

**Comment by tycn888** [comment]
国内dns 和国外dns要是可以分开设置bootstrap dns就好了

**Comment by sbwml** [comment]
> 如题，因为校园网内的基于udp的dns请求都会被拦截并且不会返回任何结果，所以只能使用自动分配的内网dns来作为bootstrap dns。 虽然通过自定义配置能够实现，如果现在的界面上能够支持就更好了。非常感谢作者。

自定义 bootstrap dns https://github.com/sbwml/luci-app-mosdns/commit/6e229e44667154b6c5539cb861e189614c878ee0

**Comment by sbwml** [comment]
> 国内dns 和国外dns要是可以分开设置bootstrap dns就好了

自定义配置上它很容易实现，"预设配置" 它是固定的，它适用于常规 DNS 接管使用。如果把大家的需求都往预设配置上加，那它将变得非常复杂。

luci-app-mosdns 这个 luci 初衷是为了给家里的路由器使用 TLS 协议的 DNS 在 OpenWrt 上。一年多前我对它的满意度是 10分，直至后面不知道它从哪里被人知晓，被要求的东西越来越多，现在给这个东西打分  顶多只有2分，因为它已经变成完全不是我想要东西。

**Comment by Mrican** [comment]
做一个自用版本
