### ISSUE TITLE
是否可以将 805606d 合并进 v5-lua 分支？

### ISSUE THREAD

**Issue by akaet** [sbwml/luci-app-mosdns#268]
大佬你好，https://github.com/sbwml/luci-app-mosdns/commit/805606d13743d6bfd9f6faeaec40a5ec544fe51d 是否可以将这个提交合并到 v5-lua 分支呢？

**Comment by lengfwong** [comment]
把patches文件夹下载到v5-lua 分支的目录编译即可。

**Comment by sbwml** [comment]
![image](https://github.com/user-attachments/assets/a19e8733-2d2b-481f-9db6-b9c7182cd14a)



lua 分支已经 EOL 了。

**Comment by akaet** [comment]
> 把patches文件夹下载到v5-lua 分支的目录编译即可。

好的，感谢。

**Comment by akaet** [comment]
> ![image](https://private-user-images.githubusercontent.com/16485166/376028520-a19e8733-2d2b-481f-9db6-b9c7182cd14a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg4MzQ1MjYsIm5iZiI6MTcyODgzNDIyNiwicGF0aCI6Ii8xNjQ4NTE2Ni8zNzYwMjg1MjAtYTE5ZTg3MzMtMmQyYi00ODFmLTlkYjYtYjljNzE4MmNkMTRhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDEzVDE1NDM0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBmYWViYTliY2E4ZWE2MmQxMDE2MTAxZjg2YzAyYmI1NDMzOWFlNGU3OGQwM2JkOTg2ZDlmZDdjYjI3YzcwNDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.CUP4MQy5K9zZMPwhUxeh-FfmmbGkIwyFDfbH0gnota0)
> 
> lua 分支已经 EOL 了。

明白了，谢谢大佬。
