### ISSUE TITLE
luci界面是不是可能根据代理自动转为英文界面？

### ISSUE THREAD

**Issue by wangsmile** [sbwml/luci-app-mosdns#269]
能否有个选项，自己选择界面语言啊，我现在代理是香港，但是luci总是自动为英文界面。只有远程DDNSto进来，会成为中文界面。

**Comment by sbwml** [comment]
luci 语言并不是由某一个插件设置，你要强制中文就自己去系统设置成中文，而不是自动

**Comment by wangsmile** [comment]
我是在openwrt路由器里安装，请问这个去系统设置成中文在哪里呢？
