### ISSUE TITLE
安装错误 提示 Error! OpenWrt "gdq-test" version is not supported.

### ISSUE THREAD

**Issue by Daohuai0913** [sbwml/luci-app-mosdns#27]
root@OpenWrt:~# sh -c "$(curl -sS https://raw.githubusercontent.com/sbwml/luci-app-mosdns/master/install.sh)"

Checking available space  ...

Checking platform  ...

Error! OpenWrt "gdq-test" version is not supported.
使用的是n4500的软路由 x86的 网上有没案例 求助

**Comment by sbwml** [comment]
这个安装脚本是针对官方openwrt 发布版。如果是第三方的源码、或固件，我建议直接 https://github.com/sbwml/luci-app-mosdns/releases 下载对应架构的ipk 文件安装。

**Comment by Daohuai0913** [comment]
> 这个安装脚本是针对官方openwrt 发布版。如果是第三方的源码、或固件，我建议直接 https://github.com/sbwml/luci-app-mosdns/releases 下载对应架构的ipk 文件安装。

可是老哥 我不知道下载哪几个啊 我都下载了一遍 安装却有问题

**Comment by sbwml** [comment]
你不是说你是x86 吗，那就下载x86 。至于luci ，你是什么op版本  就下载哪个luci。19或以上的版本下载 luci-app-mosdns_1.4.2_all.ipk。18 的版本就下载  openwrt-18.06_luci-i18n-mosdns-zh-cn_1.4.2-2_all.ipk

这些都刻意重命名过的了   应该很好区分

**Comment by Daohuai0913** [comment]
> 你不是说你是x86 吗，那就下载x86 。至于luci ，你是什么op版本 就下载哪个luci。19或以上的版本下载 luci-app-mosdns_1.4.2_all.ipk。18 的版本就下载 openwrt-18.06_luci-i18n-mosdns-zh-cn_1.4.2-2_all.ipk
> 
> 这些都刻意重命名过的了 应该很好区分

Multiple packages (libgcc1 and libgcc1) providing same name marked HOLD or PREFER. Using latest. Unknown package 'luci-app-mosdns'.
安装luci-app-mosdns_1.4.2_all.ipk的时候提示这个 是依赖不全吗?

**Comment by Daohuai0913** [comment]
luci-app-mosdns_1.4.2_all.ipk
mosdns_4.5.3-1_x86_64.ipk
就下载了这两个 是不是还差东西啊 老哥

**Comment by Daohuai0913** [comment]
> 能冒昧的问一下。你的op版本和 你安装的方式吗
这是首页写的固件版本
OpenWrt R22.8.2 GDQ SUMMER[2022] Compiled by eSir / LuCI Master (git-22.200.61437-0c3c82f)
然后安装的话我是使用 系统-文件传输-上传软件包 然后在下面点击安装 我之前安装adguardhome也是这样装的


<br class="Apple-interchange-newline">
</body>
</html>

**Comment by zixiang5288** [comment]
用10月25日4.5.2的mosdns_1.4.2_all.ipk可以安装，今天的我也安装不了，提示依赖问题

**Comment by Daohuai0913** [comment]
openwrt-18.06_luci-i18n-mosdns-zh-cn_1.4.2-2_all.ipk 
我看到这个单独的ipk 这个有用嘛?

**Comment by sbwml** [comment]
> > 用10月25日4.5.2的mosdns_1.4.2_all.ipk可以安装，今天的我也安装不了，提示依赖问题
> 
> [openwrt/luci@673f382](https://github.com/openwrt/luci/commit/673f38246ac3548caefec41183e3dd7477d9f6f6) openwrt 上游分离了 luci-lua-runtime ，现在已经退回2102 sdk 构建 [3011cd5](https://github.com/sbwml/luci-app-mosdns/commit/3011cd5cb53ad937276849797b6a7aa9490634ef)

我虚拟机上测试了 ，今天编译的确实无法安装，现在已经重新编译，你等个20来分钟再用脚本安装试试

**Comment by zixiang5288** [comment]
感谢更新

> openwrt-18.06_luci-i18n-mosdns-zh-cn_1.4.2-2_all.ipk 我看到这个单独的ipk 这个有用嘛?

大佬更新了，着急就先用上个离线的版本，x86基本都是基于lea编译的，我就用的mosdns_1.4.2_all.ipk，luci-i18n-mosdns-zh-cn_git-22.286.16040-d9c1f1c_all.ipk

**Comment by Daohuai0913** [comment]
感谢两位 主要是我的mosdns 就重新安装开关了一下就不能运行了 就打算重新安装 就遇到这问题

**Comment by zixiang5288** [comment]
dns先交回Dnsmasq ，等大佬的编译完再装

**Comment by qingtian110** [comment]
难怪我装不上，晚上看到更新了新版本，去更新，结果装不上，以为自己把路由器玩炸了，恢复出厂了一下，还是装不上。

还好恢复出厂前有备份，不然白恢复了🤣

**Comment by qingtian110** [comment]
![1](https://user-images.githubusercontent.com/87856890/199514320-bc731382-e1cf-496f-9b6c-ea09ecc1bffe.png)

最新编译出来的可以安装了  兄弟们

**Comment by Daohuai0913** [comment]
> ![1](https://user-images.githubusercontent.com/87856890/199514320-bc731382-e1cf-496f-9b6c-ea09ecc1bffe.png)
> 
> 最新编译出来的可以安装了 兄弟们
![image](https://user-images.githubusercontent.com/31792646/199514772-f97c0958-7517-49f2-b56a-c815052baf67.png)
为啥我还是这样

**Comment by zixiang5288** [comment]
> 难怪我装不上，晚上看到更新了新版本，去更新，结果装不上，以为自己把路由器玩炸了，恢复出厂了一下，还是装不上。
> 
> 还好恢复出厂前有备份，不然白恢复了🤣

我也是一顿操作，恢复了还没备份

**Comment by sbwml** [comment]
> > ![image](https://user-images.githubusercontent.com/31792646/199514772-f97c0958-7517-49f2-b56a-c815052baf67.png)
> > 为啥我还是这样

你在终端执行  `cat /etc/openwrt_release` 截图出来看看

**Comment by Daohuai0913** [comment]
> > > ![image](https://user-images.githubusercontent.com/31792646/199514772-f97c0958-7517-49f2-b56a-c815052baf67.png)
> > > 为啥我还是这样
> 
> 你在终端执行 `cat /etc/openwrt_release` 截图出来看看

我已经手动安装成功了 但是 mosdns还是不会运行

**Comment by zixiang5288** [comment]
> > > > ![image](https://user-images.githubusercontent.com/31792646/199514772-f97c0958-7517-49f2-b56a-c815052baf67.png)
> > > > 为啥我还是这样
> > 
> > 
> > 你在终端执行 `cat /etc/openwrt_release` 截图出来看看
> 
> 我已经手动安装成功了 但是 mosdns还是不会运行

内置配置不能运行？如果用的自定义不运行就是配置不兼容新版，需要重配置

**Comment by Daohuai0913** [comment]
> 你在luci 页面上关闭mosdns
> 
> 在终端手动运行显示什么错误
> 
> `/usr/bin/mosdns start -c /etc/mosdns/config.yaml`

Error: failed to read config file, open /etc/mosdns/config.yaml: no such file or directory
2022-11-02T22:42:35.290+0800    fatal   failed to read config file, open /etc/mosdns/config.yaml: no such file or directory
好家伙 竟然显示 没有文件

**Comment by Daohuai0913** [comment]
> 你在luci 页面上关闭mosdns
> 
> 在终端手动运行显示什么错误
> 
> `/usr/bin/mosdns start -c /etc/mosdns/config.yaml`

![image](https://user-images.githubusercontent.com/31792646/199520295-5a300f24-8f95-41a9-843e-b557e5b3a272.png)
我手动打开看了下只有这两个

**Comment by sbwml** [comment]
那你在luci 上启用mosdns    但是不要勾选重定向dns，再去终端手动执行启动命令看看

**Comment by sbwml** [comment]
这个问题终结了。你使用的是 404 提供的mosdns 。你需要前往  https://github.com/QiuSimons/openwrt-mos 咨询

**Comment by Daohuai0913** [comment]
> :

但是大哥我用你的ipk啊

**Comment by sbwml** [comment]
性质不一样的了。实际上你根本没有安装上 sbwml/luci-app-mosdns 下载的ipk，因为你的固件存在 404 的版本，冲突缘故，sbwml/luci-app-mosdns这里的你根本无法安装上。你要去404 大佬那里获得更多信息

**Comment by qingtian110** [comment]
你直接卸载固件自带的mosdns ，重新安装这里下载的不就好了。

404 版本的功能比较少，部分功能也是从这里的版本pr过去的

**Comment by Daohuai0913** [comment]
> 你直接卸载固件自带的mosdns ，重新安装这里下载的不就好了。
> 
> 404 版本的功能比较少，部分功能也是从这里的版本pr过去的

我就是卸载了 但是好像没卸载干净一样

**Comment by qingtian110** [comment]
你这样操作

**Comment by Daohuai0913** [comment]
> 你这样操作

我在系统-软件包 里面搜索mosdns 我把搜出来的点了卸载

**Comment by qingtian110** [comment]
打开软件包。过滤mosdns  关键词，如果有就全部卸载

然后终端上清理掉残留文件
```shell
rm -rf /etc/mosdns /etc/config/mosdns
```

然后你再下载ipk去安装   就没事了

**Comment by qingtian110** [comment]
404 的配置和 这里的版本  是不一样的  有残留配置是运行不起来的

**Comment by Daohuai0913** [comment]
> 404 的配置和 这里的版本 是不一样的 有残留配置是运行不起来的

好的 我试一下
