### ISSUE TITLE
V5版本与ssrplus出现冲突

### ISSUE THREAD

**Issue by NEARWN** [sbwml/luci-app-mosdns#271]
使用lede最新23源码，V5版本与ssrplus出现冲突，删除网络接口WAN6后正常，在lede 18旧版本源码中与v5lua版本没有发现此问题

**Comment by sbwml** [comment]
有没有 lede x86 （vm虚拟机能跑的）现成固件，含 ssrp 插件的

**Comment by NEARWN** [comment]
https://www.123865.com/s/9AW0Vv-d0lJH

**Comment by sbwml** [comment]
![image](https://github.com/user-attachments/assets/7e2f6e69-a298-4c0e-94a9-ec5aa59fd4fb)

我没有这个网盘，下载不了

**Comment by NEARWN** [comment]
https://github.com/NEARWN/openwrtaction/actions/runs/11470199710

**Comment by sbwml** [comment]
我没有理解你所说的冲突是什么意思。 https://github.com/NEARWN/openwrtaction/actions/runs/11470199710 固件，mosdns 工作正常

![image](https://github.com/user-attachments/assets/3c074708-8d9e-41d6-b808-efdd87bbf18a)
![image](https://github.com/user-attachments/assets/3efeb7a5-746f-4906-9930-93b714a4e71b)
![image](https://github.com/user-attachments/assets/362834fb-33cc-430d-8bbf-af09de409551)

**Comment by NEARWN** [comment]
好的，我再试试
