### ISSUE TITLE
GeoIP解包报错

### ISSUE THREAD

**Issue by YnSen** [sbwml/luci-app-mosdns#273]
使用的全量更新的数据库，GeoIP解包报错，日志如下：

2024-10-27 13:03:36	FATAL	failed to unpack geoip	{"error": "cannot find entry cloudflare"}
github.com/urlesistiana/v2dat/cmd/unpack.newGeoIPCmd.func1
	github.com/urlesistiana/v2dat/cmd/unpack/geoip.go:25
github.com/spf13/cobra.(*Command).execute
	github.com/spf13/cobra@v1.6.1/command.go:920
github.com/spf13/cobra.(*Command).ExecuteC
	github.com/spf13/cobra@v1.6.1/command.go:1044
github.com/spf13/cobra.(*Command).Execute
	github.com/spf13/cobra@v1.6.1/command.go:968
main.main
	github.com/urlesistiana/v2dat/main.go:9
runtime.main
	runtime/proc.go:271

![Quicker_20241027_131025](https://github.com/user-attachments/assets/9c6d513c-c150-4738-a9c5-650ed1c28858)

![Quicker_20241027_131126](https://github.com/user-attachments/assets/cc696b15-d223-4392-b079-e6e2aa0268c7)

![Quicker_20241027_130529](https://github.com/user-attachments/assets/cc951881-cb06-4e9f-8a3e-41fcfa8f6c9c)

![Quicker_20241027_130458](https://github.com/user-attachments/assets/1073c515-5c15-40ad-9aca-ec5c6f7887ad)

![Quicker_20241027_131324](https://github.com/user-attachments/assets/2728db3f-db33-4de5-926a-fb10d52f3c61)

**Comment by sbwml** [comment]
全量的 geoip 有十多兆大小。你截图上只有 300k，很显然它下载的并不是完整版 geoip。mosdns luci 页面的 geoip 类型是在 **保存并应用** 后才会生效。

**Comment by YnSen** [comment]
> 全量的 geoip 有十多兆大小。你截图上只有 300k，很显然它下载的并不是完整版 geoip。mosdns luci 页面的 geoip 类型是在 **保存并应用** 后才会生效。

还是大佬厉害能看到问题，我都没注意这个大小不对。。。但是插件安装好，在更新数据库这个选项卡默认就是全量的，我都没动过，一直都以为没问题，原来还要重新保存应用一下。。。
