### ISSUE TITLE
imm主线编译package install遇到了这个问题

### ISSUE THREAD

**Issue by m0eak** [sbwml/luci-app-mosdns#278]
ERROR: luci-app-mosdns-1.6.6-r1: trying to overwrite etc/init.d/mosdns owned by mosdns-5.3.3-r1.

**Comment by sbwml** [comment]
如果你需要从源码构建它，那么你要先移除 imm feeds 提供的  mosdns 包之后从这里拉取。否则就是你遇到的问题。因为 imm 的  mosdns 包它本身支持无 luci 运行，即包含了  init.d 启动脚本。

这里的 mosdns 包是纯二进制文件，它的 init.d 位于  luci app mosdns
