### ISSUE TITLE
固件版本	OpenWrt R21.6.22 内核版本5.10.46 无法安装

### ISSUE THREAD

**Issue by ilafz** [sbwml/luci-app-mosdns#28]
x86可以安装吗 
运行install.sh提示Error! OpenWrt "snapshot" version is not supported.

**Comment by sbwml** [comment]
x86 可以装，下载ipk文件安装 ：geoip.ipk、geosite.ipk、mosdns-x86-64.apk   、luci-app-mosdns.ipk   下载这四个ipk文件，并按照这个顺序装

安装ipk 文件前需要 opkg update 刷新openwrt软件源
