### ISSUE TITLE
上游更新了，不过没发布release

### ISSUE THREAD

**Issue by 4thanks** [sbwml/luci-app-mosdns#282]
rt
更新了依赖，修复2个bug

**Comment by Mrican** [comment]
luci-app-mosdns 也来一波

**Comment by sbwml** [comment]
如何更新

发自我的iPhone

**Comment by sbwml** [comment]
只有两个上游的时候  有可能会使用同一个   这个问题已经在patch 中修复

发自我的iPhone

**Comment by zheshifandian** [comment]
https://github.com/zheshifandian/luci-app-mosdns/commit/f681736357a21ce02e391bf81f31468b17752438

**Comment by sbwml** [comment]
这就叫专业
