### ISSUE TITLE
ttl怎么配置呢

### ISSUE THREAD

**Issue by ilafz** [sbwml/luci-app-mosdns#29]
我在x86安装了官方版本 只有1.2的luci文件 安装完成之后和作者你的界面不同 我想配置ttl怎么办呢

**Comment by sbwml** [comment]
[mosdns](https://github.com/IrineSistiana/mosdns) 作者也提供luci了吗？

但是不管怎么安装的，配置文件的编写都可以看 wiki https://irine-sistiana.gitbook.io/mosdns-wiki/
