### ISSUE TITLE
按照官方文档配置了 内设模式可以运行 但是自定义配置写进去 反复运行中未运行

### ISSUE THREAD

**Issue by ilafz** [sbwml/luci-app-mosdns#30]
# 日志设置
log:
  level:                   debug
  file:                    /tmp/mosdns.txt

# 数据源设置
data_providers:
  - tag:                   geosite
    file:                  "/usr/share/v2ray/geosite.dat"
    auto_reload:           true

  - tag:                   geoip
    file:                  "/usr/share/v2ray/geoip.dat"
    auto_reload:           true

  - tag:                   adlist
    file:                  "./rule/serverlist.txt"
    auto_reload:           true

  - tag:                   whitelist
    file:                  "./rule/whitelist.txt"
    auto_reload:           true

  - tag:                   hosts
    file:                  "./rule/hosts.txt"
    auto_reload:           true

  - tag:                   blocklist
    file:                  "./rule/blocklist.txt"
    auto_reload:           true
 
  - tag:                   redirect
    file:                  "./rule/redirect.txt"
    auto_reload:           true

# 插件
plugins:
  - tag:                   "query_is_whitelist_domain"
    type:                  query_matcher
    args:
      domain:
            - "provider:whitelist"

  - tag:                   "query_is_blocklist_domain"
    type:                  query_matcher
    args:
      domain:
            - "provider:blocklist"

  - tag:                   "query_is_local_domain"
    type:                  query_matcher
    args:
      domain:
        - "provider:geosite:cn"

  - tag:                   "query_is_non_local_domain"
    type:                  query_matcher
    args:
      domain:
        - "provider:geosite:geolocation-!cn"

  - tag:                   "query_is_qtype65"
    type:                  query_matcher
    args:
      qtype:               [65]

  - tag:                   "query_is_ad_domain"
    type:                  query_matcher
    args:
      domain:
        - "provider:adlist"

  - tag:                   "response_has_local_ip"
    type:                  response_matcher
    args:
      ip:
        - "provider:geoip:cn"

  - tag:                   "query_is_hosts_domain"
    type:                  hosts
    args:
      hosts:
           - "provider:hosts"

  - tag:                   "query_is_redirect_domain"
    type:                  redirect
    args:
      rule:
          - "provider:redirect"

  - tag:                   "reverse"
    type:                  "reverse_lookup"
    args:
      size:                65535
      ttl:                 1800
      handle_ptr:          true 

  - tag:                   "lazy_cache"
    type:                  cache
    args:
      size:                104857600
      lazy_cache_ttl:      259200
      lazy_cache_reply_ttl: 5
      cache_everything: ture

  - tag:                   "forward_local"
    type:                  fast_forward
    args:
      upstream:
        - addr:            127.0.0.1:31
        - addr:            127.0.0.1:31

  - tag:                   "forward_remote"
    type:                  fast_forward
    args:
      upstream:
        - addr:            127.0.0.1:41
          enable_pipeline: true
        - addr:            127.0.0.1:41
          enable_pipeline: true

  - tag: "ttl 1"
type: "ttl"
args:
  minimal_ttl: 0  # 最小TTL。如果非零，小于这个数的应答的TTL会被修改成这个值。
  maximum_ttl: 0 # 最大TTL。如果非零，大于这个数的应答的TTL会被修改成这个值。

  - tag:                   main_sequence
    type:                  sequence
    args:
      exec:
        - _misc_optm
        - reverse
        - lazy_cache
        - query_is_hosts_domain
        - query_is_redirect_domain
        - _no_ecs
        - if:              "query_is_whitelist_domain"
          exec:
            - forward_local
            - _return
        - if:              "query_is_blocklist_domain || query_is_ad_domain || query_is_qtype65"
          exec:
            - _new_nxdomain_response
            - _return
        - if:              "query_is_local_domain"
          exec:
            - forward_local
            - _return
        - if:              "query_is_non_local_domain"
          exec:
            - _prefer_ipv4
            - forward_remote
            - _return
        - primary:
            - forward_local
            - if:          "(! response_has_local_ip) && [_response_valid_answer]"
              exec:
                - _drop_response
          secondary:
            - _prefer_ipv4
            - forward_remote
          fast_fallback:   150
          always_standby:  true

# 服务器设置
servers:
  - exec:                  main_sequence
    listeners:
      - protocol:          udp
        addr:              127.0.0.1:5335
      - protocol:          tcp
        addr:              127.0.0.1:5335

**Comment by ilafz** [comment]
我是sb cache_everything: true  写成了ture 已经解决了

**Comment by sbwml** [comment]
你是真不应该买了羊头  过来狗肉铺问
