### ISSUE TITLE
360v6 qsdk 固件启动不起来

### ISSUE THREAD

**Issue by mjyhj** [sbwml/luci-app-mosdns#31]
geoip.dat
geosite.dat
均已下载，使用预设值的配置启动不了，把端口更换了也不行。
直接执行service mosdns start 提示
![QQ图片20221116182242](https://user-images.githubusercontent.com/22577418/202155116-71cdbb00-5442-4a18-baa2-aef93fa27783.png)

然后测试不用LUCI启动
把/etc/init.d/mosdns删除后
执行mosdns service install -d /etc/mosdns -c config.yaml
再运行一次，此时提示Running，但是只能运行几秒，马上就变回stop
![1](https://user-images.githubusercontent.com/22577418/202155729-f6c73d32-279e-4a2b-9af0-a4e566cff73d.png)

最后替换成这里的[config.yaml](https://github.com/pmkol/easymosdns/blob/main/config.yaml)就可以正常运行。

**Comment by sbwml** [comment]
固件这种东西很多很杂，我只能确认openwrt 是可以跑，也就是这个东西  https://github.com/openwrt

**Comment by qingtian110** [comment]
看你输入的这些东西 ，好像不是这里下载的mosdns 一样，感觉挺奇怪的？你是下载ipk安装的还是编译进去的？如果是编译进去的 。用的openwrt 源码是不是已经包含了一个mosdns了，然后这里的源码根本没被编译。。
