### ISSUE TITLE
数据库更新失败问题

### ISSUE THREAD

**Issue by Atomseek** [sbwml/luci-app-mosdns#32]
手动点击数据库更新按钮，显示失败。我查看之前的issues，输入/usr/share/mosdns/mosdns.sh geodata; echo $?测试

Downloading https://github.com/Loyalsoldier/v2ray-rules-dat/releases/latest/download/geoip.dat
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
100 9516k  100 9516k    0     0  1660k      0  0:00:05  0:00:05 --:--:-- 3038k
Downloading https://github.com/Loyalsoldier/v2ray-rules-dat/releases/latest/download/geosite.dat
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
100 5029k  100 5029k    0     0  1624k      0  0:00:03  0:00:03 --:--:-- 3183k
sh: geosite.dat: unknown operand
sh: ^https://raw.githubusercontent.com: unknown operand
Downloading 
curl: (3) Error
1

我定位到是广告过滤列表更新出问题，导致显示更新失败，实际上geo数据库已经更新成功了。
我手动修改/usr/share/mosdns/mosdns.sh中的
elif [ "$1" == "geodata" ]; then
	geodat_update && adlist_update

为：
elif [ "$1" == "geodata" ]; then
	geodat_update

即可，因为我不需要广告拦截服务

**Comment by sbwml** [comment]
有什么方法可以远程看一下你的openwrt 吗？我发现很多人的openwrt 好像和我自己用的都不一样
