### ISSUE TITLE
openwrt for R5S

### ISSUE THREAD

**Issue by gswangmd-gssi** [sbwml/luci-app-mosdns#33]
编译成功后，luci无法启动。

**Comment by sbwml** [comment]
要盲猜原因，其实挺难的

**Comment by JAM2199562** [comment]
> 要盲猜原因，其实挺难的

我大约猜到了

**Comment by gswangmd-gssi** [comment]
啥原因呢？

**Comment by sbwml** [comment]
你应该提供一点东西，而不是让人去猜想问题原因。功力低微，靠猜我是猜不到了。

但是我可以推荐一个在openwrt 上更加稳定的mosdns ：来自我偶像404大佬  https://github.com/QiuSimons/openwrt-mos

**Comment by gswangmd-gssi** [comment]
谢谢，这里的不行，我就在用https://github.com/QiuSimons/openwrt-mos
![image](https://user-images.githubusercontent.com/59297839/204117155-6fc726d9-ed9f-4109-bc4a-eed01b6b8d4b.png)

**Comment by sbwml** [comment]
这就已经很完美
