### ISSUE TITLE
自定义配置模式下第三方去广告选项

### ISSUE THREAD

**Issue by edmondfr** [sbwml/luci-app-mosdns#34]
从默认配置切换到自定义配置模式后，第三方去广告列表的adlist文件被清空，无法使用，只能用geosite的。
能否在自定义配置luci界面中，增加选择开关去广告和三方列表，并在开启的情况下可更新。感谢。

**Comment by sbwml** [comment]
默认 和 自定义 事实上是两个完全不同的模式。自定义配置应该与默认配置使用的文件分开，而且luci 根本无法干预自定义配置文件的操作。如果你单纯是为了使用某个广告列表并希望它在自定义配置文件上实现自动更新，你可以通过openwrt 自带的定时任务来实现

**Comment by edmondfr** [comment]
本想偷个懒，只能这样了。谢谢。
