### ISSUE TITLE
R69S在Lean的固件下安装报错

### ISSUE THREAD

**Issue by BlueDolphin9527** [sbwml/luci-app-mosdns#38]
彻视的R69S，N4500，X86-64，使用Lean大神的固件，安装的时候报错，这要怎么解决啊？
<img width="584" alt="openwrt-mosdns报错" src="https://user-images.githubusercontent.com/62049321/207782247-e74841e8-0507-4557-9862-35e9cdc1d153.png">

**Comment by sbwml** [comment]
缺少依赖了  你需要安装   luci-compat
