### ISSUE TITLE
如何证明我现在的DNS解析来自mosdns，而不是其他？

### ISSUE THREAD

**Issue by wenpo1975** [sbwml/luci-app-mosdns#39]
[root@OpenWrt:03:36 PM ~] # nslookup taobao.com
Server:         127.0.0.1
Address:        127.0.0.1:53

Non-authoritative answer:
Name:   taobao.com
Address: 140.205.94.189
Name:   taobao.com
Address: 140.205.220.96

Non-authoritative answer:

[root@OpenWrt:03:36 PM ~] # nslookup taobao.com
Server:         127.0.0.1
Address:        127.0.0.1:53

Non-authoritative answer:
Name:   taobao.com
Address: 140.205.220.96
Name:   taobao.com
Address: 140.205.94.189

Non-authoritative answer:

[root@OpenWrt:03:37 PM ~] # nslookup taobao.com
Server:         127.0.0.1
Address:        127.0.0.1:53

Non-authoritative answer:
Name:   taobao.com
Address: 140.205.94.189
Name:   taobao.com
Address: 140.205.220.96

Non-authoritative answer:

如上；
无论我如何调整端口，调转发，回答的DNS主机名都是Server:         127.0.0.1     Address:        127.0.0.1:53
虽然luci上显示的是 “MosDNS 运行中”，但我没办法从回答中确认他是否在参与解析
我没有启用 “将 Dnsmasq 域名解析请求转发到 MosDNS 服务器” ,而是关闭了dnsmasq dns相关的设置后，
直接在DHCP/DNS里面转发到127.0.0.1#5335
请问在哪里能加上类似smartdns上的 “服务器名称” ？
![image](https://user-images.githubusercontent.com/24839804/207802173-bd12a5ec-571a-4e18-9aa5-1e3f639b14ff.png)

这样，他在nslookup回复里面 就变成 Server:         smartdns

谢谢

**Comment by sbwml** [comment]
mosdns 它没有设置服务器名称的功能，你可以给mosdns开发者给反馈下支持

至于怎么确认mosdns 有没有工作，打开日志“调试” 等级，日志里面能看见解析操作、缓存命中等信息，那就说明它在工作了
