### ISSUE TITLE
可以考虑加个CDN源嘛？

### ISSUE THREAD

**Issue by wenpo1975** [sbwml/luci-app-mosdns#41]
https://github.com/pmkol/easymosdns/tree/rules

加个CDN源、CDN规格就完美了。

**Comment by sbwml** [comment]
没懂你的意思

**Comment by zixiang5288** [comment]
现在已经足够强大了，该有的都有了

**Comment by wwng2333** [comment]
[gh-proxy.com](https://gh-proxy.com/) 请
