### ISSUE TITLE
执行 sh -c "$(curl -ksS https://raw.githubusercontent.com/sbwml/luci-app-mosdns/master/install.sh)"报错

### ISSUE THREAD

**Issue by OXERIS** [sbwml/luci-app-mosdns#43]
root@OpenWrt:~# sh -c "$(curl -ksS https://raw.githubusercontent.com/sbwml/luci-app-mosdns/master/install.sh)"
sh: can't open h1: no such file

**Comment by sbwml** [comment]
这个安装方式不是固定的，你可以把脚本下载回来后执行，比如：
```bash
wget https://raw.githubusercontent.com/sbwml/luci-app-mosdns/master/install.sh

sh install.sh

```

如果因网络问题不能正常 下载到，你还可以直接下载ipk文件来安装  https://github.com/sbwml/luci-app-mosdns/releases/tag/v4.5.3

![image](https://user-images.githubusercontent.com/16485166/213845411-63f71a4c-156c-41de-8b1c-5ed7cd4900b0.png)

**Comment by OXERIS** [comment]
> 

啊，新年快乐！！

**Comment by iislong** [comment]
我用
```
opkg install /tmp/**.ipk
```
命令安装好，在软件包也看到了，怎么在服务里找不到mosdns?

**Comment by iislong** [comment]
> 我用
> ```
> opkg install /tmp/**.ipk
> ```
> 命令安装好，在软件包也看到了，怎么在服务里找不到mosdns?

已解决，未安装luci支持（看别人的攻略）
![Screenshot_2023-02-15-21-06-36-056_mark.via.gp.png](https://user-images.githubusercontent.com/2937252/219035639-dfe2abee-bbc5-425d-9ee3-2aaccad7af50.png)
