### ISSUE TITLE
支持 mosdns v5.0.0

### ISSUE THREAD

**Issue by piloer** [sbwml/luci-app-mosdns#44]

**Comment by sbwml** [comment]
目前暂不考虑，我认为的两点原因

一、它不再兼容 v2ray-geodata，这个数据库几乎是国内openwrt 玩家的刚需，若要v5 重新去复用它，需要把解包工具内置进来，在mosdns 需要时 dump 出明文文本去读取。这一切看起来似乎都合情合理，但是它可能不适合openwrt了，而是**openwrt 软路由**设备。

二、v5 彻底推翻以前 v3/v4 的配置编写方式，若要实现v5的配置支持，肯定不是直接套用现有的luci 去做，太麻烦了


要我说 v3 是最舒服的一个版本 
![image](https://user-images.githubusercontent.com/16485166/216056295-ce8de632-063f-4982-bc4f-a8ab35b838c6.png)

**Comment by Pacio** [comment]
隔壁支持v5了，不知道用的什么方法解决你这两个问题

**Comment by Miroxyz** [comment]
> 隔壁支持v5了，不知道用的什么方法解决你这两个问题

@Pacio 来个链接，谢谢

**Comment by sbwml** [comment]
> > 隔壁支持v5了，不知道用的什么方法解决你这两个问题
> 
> @Pacio 来个链接，谢谢

404大佬 👍👍
https://github.com/QiuSimons/openwrt-mos

**Comment by sbwml** [comment]
v5 娱乐测试
https://github.com/sbwml/luci-app-mosdns/tree/v5-dev

**Comment by yyysuo** [comment]
> v5 娱乐测试 https://github.com/sbwml/luci-app-mosdns/tree/v5-dev

求编译文件，求注意事项，求详细说明。

**Comment by sbwml** [comment]
这可把我给难倒了，我不太熟悉github runner 的操作，不知道如何让非默认分支创建构建任务。

我个人是极不推荐在openwrt 上使用v5 版本。openwrt 应该用v3或v4。 dns 这块不为追新，为求稳

**Comment by yyysuo** [comment]
> 这可把我给难倒了，我不太熟悉github runner 的操作，不知道如何让非默认分支创建构建任务。
> 
> 我个人是极不推荐在openwrt 上使用v5 版本。openwrt 应该用v3或v4。 dns 这块不为追新，为求稳

听人劝，吃饱饭，目前只是尝鲜，没有在主路由上部署，倒是也没感觉到什么差别，用的是：https://github.com/MartialBE/luci-app-mosdns

看了一下代码，好像是作者自己转换好了规则，提供给大家使用的，不是直接使用的geosite的dat文件。

**Comment by sbwml** [comment]
使用geodate 最大的优势是它作为科学插件的依赖，无论在mosdns 或 科学插件更新它，他们同时得到最新的数据，并且因网络触发的进程重启，它都能随时随低有数据可读，而不需要每次依赖网络下载

**Comment by sbwml** [comment]
遗憾的是 v5 扔掉了文件变化mosdns 数据重载的功能，让这种便利降低了一大半

**Comment by yyysuo** [comment]
> 遗憾的是 v5 扔掉了文件变化mosdns 数据重载的功能，让这种便利降低了一大半

我也挺好奇作者重构的动力是什么，这种重构在开源界很普遍么？

**Comment by 4thanks** [comment]
> 遗憾的是 v5 扔掉了文件变化mosdns 数据重载的功能，让这种便利降低了一大半

在定时更新脚本加`/etc/init.d/mosdns reload`也一样吧

**Comment by yyysuo** [comment]
fork了一下大佬的v5分支，自己添加了一下token，然后自己发布一下，就会触发自动编译，等10多分钟就得到ipk了，安装之后正常运行，请问大佬有哪些问题需要测试验证么？

只参考了下列教程的token部分
https://www.cnblogs.com/YAN-HUA/p/13530906.html

**Comment by yyysuo** [comment]
求在v5界面中添加sp_low.tdata的开关，目前的sp_low.tdata，把www.163.com给加进去了。

**Comment by sbwml** [comment]
你直接把它从文件里删除吧，这个列表是一些死亡、危险连接，目的是避免局域网设备安装了一些威胁软件和一些奇奇怪怪的国产硬路由请求一些不明的死亡连接，它会造成mosdns疯狂打印错误日志。虽然不知道163 为什么会在里面

https://github.com/sbwml/luci-app-mosdns/commit/af99c8844c27ca1b2de8bbb86f0082bd882ff926

**Comment by yyysuo** [comment]
> 你直接把它从文件里删除吧，这个列表是一些死亡、危险连接，目的是避免局域网设备安装了一些威胁软件和一些奇奇怪怪的国产硬路由请求一些不明的死亡连接，它会造成mosdns疯狂打印错误日志。虽然不知道163 为什么会在里面
> 
> [af99c88](https://github.com/sbwml/luci-app-mosdns/commit/af99c8844c27ca1b2de8bbb86f0082bd882ff926)

好的，感谢。

**Comment by threerog** [comment]
现在情况如何

**Comment by sbwml** [comment]
只要你想，随时都在预发布里下载ipk（未跟进最后commit）   https://github.com/sbwml/luci-app-mosdns/releases

我没测试过，理论上没什么问题

**Comment by threerog** [comment]
有配合passwall使用的教程吗
smartdns转过来的，passwall+smartdns问题一大推 也没有统一的使用文档 折腾几天放弃了

**Comment by yyysuo** [comment]
> 有配合passwall使用的教程吗
> 
> smartdns转过来的，passwall+smartdns问题一大推 也没有统一的使用文档 折腾几天放弃了

![image](https://user-images.githubusercontent.com/10081071/227151401-6f644f4a-85b7-4431-8258-04f97c217be4.png)

openwrt dhcp dns转发填mosdns的服务端口，比如127.0.0.1#5454 pasawall里面远程dns选tcp，填mosdns的端口，比如127.0.0.1:5454

收工。

**Comment by threerog** [comment]
看到`v5`作为主分支了
意味着v5已经能完美平替v4了吗
