### ISSUE TITLE
关于V5的解包问题。

### ISSUE THREAD

**Issue by nil-ca** [sbwml/luci-app-mosdns#46]
Loyalsoldier大佬的github底下好像有自带的text文件比如：geoip和v2ray-rules-dat底下都有
![image](https://user-images.githubusercontent.com/18211135/217703244-3f3b1c48-6a36-43e5-9acb-e3505100028d.png)
直链是
https://github.com/Loyalsoldier/geoip/tree/release
https://github.com/Loyalsoldier/v2ray-rules-dat/tree/release
这里面的txt好像是跟着每次发布更新的。好像可以直接拿来使用吧，有了感叹号取反后，可以在geoip里面用cn.txt做取反操作吧。
https://github.com/Loyalsoldier/geoip/tree/release/text

**Comment by sbwml** [comment]
我知道，好多个仓库都有文本直供。但是我个人希望的是一库多用，v2ray-geodata 它本身就有了，像比如passwall 这类科学插件它本身就依赖v2ray-geodata 才能工作，既然它都已经存在于本地了，不用就浪费了

**Comment by nil-ca** [comment]
@sbwml 好的

**Comment by yyysuo** [comment]
邪门了，大佬，我用v5分支，解析www.163.com，总是返回NXDOMAIN，用V4分支就没有任何问题，用V5分支也暂时没有发现其它域名有问题。

**Comment by nil-ca** [comment]
> 邪门了，大佬，我用v5分支，解析www.163.com，总是返回NXDOMAIN，用V4分支就没有任何问题，用V5分支也暂时没有发现其它域名有问题。

我倒没用V5分支，我用的是原版的，配置是改的discussions讨论里面的别人分享的分流配置
