### ISSUE TITLE
兄台，防火墙规则还用加不？

### ISSUE THREAD

**Issue by ghost** [sbwml/luci-app-mosdns#48]
iptables -t nat -A PREROUTING -p udp --dport 53 -j REDIRECT --to-ports 53
iptables -t nat -A PREROUTING -p tcp --dport 53 -j REDIRECT --to-ports 53
[ -n "$(command -v ip6tables)" ] && ip6tables -t nat -A PREROUTING -p udp --dport 53 -j REDIRECT --to-ports 53
[ -n "$(command -v ip6tables)" ] && ip6tables -t nat -A PREROUTING -p tcp --dport 53 -j REDIRECT --to-ports 53
兄台，这4条规则还用在openwrt里加上不？

**Comment by sbwml** [comment]
不需要，不要与其它dns 使用的方法混淆。

你要使用mosdns ，只需要勾选 “启用“。要上网设备使用mosdns 解析就勾选 “DNS 转发”

**Comment by ghost** [comment]
> 不需要，不需要与它的dns使用的方法混杂。
> 
> 你要使用mosdns ，只需要勾选“启动”。要上网设备使用mosdns 解析就勾选“DNS转发”

好的，谢谢兄台。
