### ISSUE TITLE
需求请求--在luci设置中加入ipset相关选项

### ISSUE THREAD

**Issue by yyysuo** [sbwml/luci-app-mosdns#49]
大佬您好，仅建议，看您心情。
1：在luci中添加国内国外ipset名称选项，生成的配置文件中，自动把分流后的解析结果加入指定的ipset中。
2：ipset例外功能，指定IP或者域名不加入IPSET，避免机场域名被加入ipset导致科学失效。

**Comment by yyysuo** [comment]
可参考：https://github.com/IrineSistiana/mosdns/discussions/605

**Comment by sbwml** [comment]
mosdns 应该不会影响科学插件功能的啊，科学插件它本身就是有分流的，如果 mosdns dns 得到的ip它就是国外的地址，那这个ip 他就被科学给代理了。mosdns 它只是影响了不同的域名使用了不同的 dns 去解析    可以有效解决某些域名污染问题和一些dns优化上的事情，但是某个url或者ip 会不会被代理，不是mosdns来决定的

**Comment by yyysuo** [comment]
> mosdns 应该不会影响科学插件功能的啊，科学插件它本身就是有分流的，如果 mosdns dns 得到的ip它就是国外的地址，那这个ip 他就被科学给代理了。mosdns 它只是影响了不同的域名使用了不同的 dns 去解析 可以有效解决某些域名污染问题和一些dns优化上的事情，但是某个url或者ip 会不会被代理，不是mosdns来决定的

ssrp在/etc/ssrplus目录下有gfw_list.conf及gfw_base.conf配置文件

其中gfw_list.conf内容大致如下：
server=/samebags.com/127.0.0.1#5335
ipset=/samebags.com/gfwlist

gfw_base.conf内容大致如下：
ipset=/91smartyun.pt/gfwlist

意思是不是把指定域名的解析结果加入gfwlist这个ipset呢？用mosdns接管dns解析之后，这个写入动作就没有了吧，但是实际上并不影响科学，是不是按ssrp原来的逻辑写入ipset更好一些？passwall也有类似的配置。
IPSET_LANIPLIST="laniplist"
IPSET_VPSIPLIST="vpsiplist"
IPSET_SHUNTLIST="shuntlist"
IPSET_GFW="gfwlist"
IPSET_CHN="chnroute"
IPSET_BLACKLIST="blacklist"
IPSET_WHITELIST="whitelist"
IPSET_BLOCKLIST="blocklist"

IPSET_LANIPLIST6="laniplist6"
IPSET_VPSIPLIST6="vpsiplist6"
IPSET_SHUNTLIST6="shuntlist6"
IPSET_GFW6="gfwlist6"
IPSET_CHN6="chnroute6"
IPSET_BLACKLIST6="blacklist6"
IPSET_WHITELIST6="whitelist6"
IPSET_BLOCKLIST6="blocklist6"

**Comment by lengfwong** [comment]
> 

这个ipset 是支持的，我现在就是这样用的，一个gfwlist域名查询指定mosdns通过那个DNS查，同时加入一个ipset，防火墙规则让这个ipset的走代理。相关配置如下，只是luci界面没有，自己配置的gfwlist域名集合。另外第二条ipset例外，机场的域名加入灰名单或者白名单即可。
```

  - tag: gfwlist_domain
    file: "/etc/mosdns/gfwlist_domain.txt"
    auto_reload: true

  - tag: query_is_gfwlist_domain
    type: query_matcher
    args:
      domain:
        - "provider:gfwlist_domain"

  - tag: "ipset_gfwlist"
    type: "ipset"
    args:
      set_name4: "gfwlist"  
      mask4: 32 

          - if: query_is_gfwlist_domain
          exec:
            - _prefer_ipv4
            - forward_remote
            - modify_ttl
            - ipset_gfwlist
            - _return_

**Comment by yyysuo** [comment]
> > 
> 
> 
> 
> 这个ipset 是支持的，我现在就是这样用的，一个gfwlist域名查询指定mosdns通过那个DNS查，同时加入一个ipset，防火墙规则让这个ipset的走代理。相关配置如下，只是luci界面没有，自己配置的gfwlist域名集合。另外第二条ipset例外，机场的域名加入灰名单或者白名单即可。
> 
> ```
> 
> 
> 
>   - tag: gfwlist_domain
> 
>     file: "/etc/mosdns/gfwlist_domain.txt"
> 
>     auto_reload: true
> 
> 
> 
>   - tag: query_is_gfwlist_domain
> 
>     type: query_matcher
> 
>     args:
> 
>       domain:
> 
>         - "provider:gfwlist_domain"
> 
> 
> 
>   - tag: "ipset_gfwlist"
> 
>     type: "ipset"
> 
>     args:
> 
>       set_name4: "gfwlist"  
> 
>       mask4: 32 
> 
> 
> 
>           - if: query_is_gfwlist_domain
> 
>           exec:
> 
>             - _prefer_ipv4
> 
>             - forward_remote
> 
>             - modify_ttl
> 
>             - ipset_gfwlist
> 
>             - _return_
> 
> 

我的疑问是ssrp和passwall是否自动添加了防火墙规则，我应该向哪个ipset添加条目呢。

**Comment by sbwml** [comment]
你始终把mosdns和 代理插件给混淆了。

据我个人了解，ssrp 和 pw 都会添加防火墙规则（这是毋庸置疑的，科学插件必须如此）。同时这两者都有使用到字典，ipset list  你能看到他们。


但是这些和mosdns 我完全想不到有什么地方可以联动起来的。想ssrp，gfwlist 它不是哪个东西写入进去的，它是从网络上下载的，和 china ssr 列表一样都是网络下载回来并勇于不同的代理模式用的

**Comment by sbwml** [comment]
https://github.com/fw876/helloworld/blob/master/luci-app-ssr-plus/luasrc/model/cbi/shadowsocksr/advanced.lua#L48

https://github.com/fw876/helloworld/blob/master/luci-app-ssr-plus/root/etc/ssrplus/gfw_list.conf

**Comment by sbwml** [comment]
```lua
o = s:option(Value, "gfwlist_url", translate("gfwlist Update url"))
o:value("https://fastly.jsdelivr.net/gh/YW5vbnltb3Vz/domain-list-community@release/gfwlist.txt", translate("v2fly/domain-list-community"))
o:value("https://fastly.jsdelivr.net/gh/Loyalsoldier/v2ray-rules-dat@release/gfw.txt", translate("Loyalsoldier/v2ray-rules-dat"))
o:value("https://fastly.jsdelivr.net/gh/Loukky/gfwlist-by-loukky/gfwlist.txt", translate("Loukky/gfwlist-by-loukky"))
o:value("https://fastly.jsdelivr.net/gh/gfwlist/gfwlist/gfwlist.txt", translate("gfwlist/gfwlist"))
o.default = "https://fastly.jsdelivr.net/gh/YW5vbnltb3Vz/domain-list-community@release/gfwlist.txt"
```

这些是ssrp的gfwlist 的规则更新上游，他们都是经过筛选出来的是明确需要被代理的域名，而mosdns 是做不到这点的，mosdns 无法帮你判断某个域名是否被墙。

**Comment by yyysuo** [comment]
> 选出来的是明确需要被代理的域名，而mosdns 是做不到这点的，mosdns 无法帮你判断某个域名是否被墙。

您生成的默认的mosdns配置，是通过geosite来分流的吧，国内加入ssrp的国内ipset，国外加入ssrp的国外ipset不可以么？我可能想到问题所在了，我只想要简单的大陆白名单，所以分流是比较明确的，只要不是国内域名，都想简单的加入到gfwlist当中，而不是实现gfwlist这个ipset最初始的用途。gfwlist这个ipset，应该是ssrp或者passwall用来强制代理的清单吧，加进入不就能利用ssrp或者passwall原本的功能了么？

**Comment by sbwml** [comment]
> 您生成的默认的mosdns配置，是通过geosite来分流的吧，国内加入ssrp的国内ipset，国外加入ssrp的国外ipset不可以么？

这个mosdns luci 默认配置确实是使用geosite、geoip以及自定义规则进行分流，他们可以被写入到ipset ，但是没有这个必要，因为即使写入到ipset ，你其他插件要利用它，是没有办法直接利用到的。因为写入到字典肯定会以mosdns 来命名，其它插件要直接读它必须要改那个插件。另外我觉得当前的mosdns 内存读取会比读字典效率更高。

还有一点就是，mosdns 和代理插件其实都做了同样一件事情，就是分流。他们的呈现的效果是一致的，只是方式不同。他们完全没有必要互相替谁完成分流工作。

**Comment by yyysuo** [comment]
> > 您生成的默认的mosdns配置，是通过geosite来分流的吧，国内加入ssrp的国内ipset，国外加入ssrp的国外ipset不可以么？
> 
> 
> 
> 这个mosdns luci 默认配置确实是使用geosite、geoip以及自定义规则进行分流，他们可以被写入到ipset ，但是没有这个必要，因为即使写入到ipset ，你其他插件要利用它，是没有办法直接利用到的。因为写入到字典肯定会以mosdns 来命名，其它插件要直接读它必须要改那个插件。另外我觉得当前的mosdns 内存读取会比读字典效率更高。
> 
> 
> 
> 还有一点就是，mosdns 和代理插件其实都做了同样一件事情，就是分流。他们的呈现的效果是一致的，只是方式不同。他们完全没有必要互相替谁完成分流工作。

没明白呀，我用ipset list gfwlist命令，提到的只有ip地址范围呀，mosdns配置中写入ipset，是可以指定ipset名称的，比如我可以指定gfwlist，您说的以mosdns来命名是指哪个名称呢。

**Comment by yyysuo** [comment]
> > 
> 
> 
> 
> 这个ipset 是支持的，我现在就是这样用的，一个gfwlist域名查询指定mosdns通过那个DNS查，同时加入一个ipset，防火墙规则让这个ipset的走代理。相关配置如下，只是luci界面没有，自己配置的gfwlist域名集合。另外第二条ipset例外，机场的域名加入灰名单或者白名单即可。
> 
> ```
> 
> 
> 
>   - tag: gfwlist_domain
> 
>     file: "/etc/mosdns/gfwlist_domain.txt"
> 
>     auto_reload: true
> 
> 
> 
>   - tag: query_is_gfwlist_domain
> 
>     type: query_matcher
> 
>     args:
> 
>       domain:
> 
>         - "provider:gfwlist_domain"
> 
> 
> 
>   - tag: "ipset_gfwlist"
> 
>     type: "ipset"
> 
>     args:
> 
>       set_name4: "gfwlist"  
> 
>       mask4: 32 
> 
> 
> 
>           - if: query_is_gfwlist_domain
> 
>           exec:
> 
>             - _prefer_ipv4
> 
>             - forward_remote
> 
>             - modify_ttl
> 
>             - ipset_gfwlist
> 
>             - _return_
> 
> 

我不确定ssrp和passwall是不是默认就调用了ipset，passwall的ipset名称写在配置文件中，很明确。ssrp启用的时候，有时候有gfwlist这个名称的ipset，有时候没有，防火墙里面也看不到这些ipset的名称。

**Comment by sbwml** [comment]
> 
> 没明白呀，我用ipset list gfwlist命令，提到的只有ip地址范围呀，mosdns配置中写入ipset，是可以指定ipset名称的，比如我可以指定gfwlist，您说的以mosdns来命名是指哪个名称呢。

它都有名字给你叫了   ip  set  ，不是ip 还能是域名啊

我认为你对他们的工作流程很陌生，甚至可能不知道这些ip 地址从哪来，你的gfwlist 域名又去了哪里。


你应该前往这些插件的仓库看源码，了解一下他们是怎么工作的，他们和dnsmasq 是什么关系。

这些和mosdns 几乎可以说是 0 关系，mosdns 可以作为他们的上游，但是干涉不了那些插件自身的工作流程

**Comment by yyysuo** [comment]
> > 没明白呀，我用ipset list gfwlist命令，提到的只有ip地址范围呀，mosdns配置中写入ipset，是可以指定ipset名称的，比如我可以指定gfwlist，您说的以mosdns来命名是指哪个名称呢。
> 
> 它都有名字给你叫了 ip set ，不是ip 还能是域名啊
> 
> 我认为你对他们的工作流程很陌生，甚至可能不知道这些ip 地址从哪来，你的gfwlist 域名又去了哪里。
> 
> 你应该前往这些插件的仓库看源码，了解一下他们是怎么工作的，他们和dnsmasq 是什么关系。
> 
> 这些和mosdns 几乎可以说是 0 关系，mosdns 可以作为他们的上游，但是干涉不了那些插件自身的工作流程

是的，只有十分粗浅的了解。我只在op的日志里面看到，ssrp向op添加了奈飞相关的DNS规则，强制奈飞走了代理。
Sun Feb 26 19:19:15 2023 daemon.info dnsmasq[31214]: using nameserver 127.0.0.1#5335 for domain nflxext.com
Sun Feb 26 19:19:15 2023 daemon.info dnsmasq[31214]: using nameserver 127.0.0.1#5335 for domain netflix.net
Sun Feb 26 19:19:15 2023 daemon.info dnsmasq[31214]: using nameserver 127.0.0.1#5335 for domain netflix.com

但是gfwlist中的域名是怎么走的，我并不清楚，电报群里有人说gfwlist中的dns请求被一块打包直接发送到了代理服务器进行解析，这样本地好像确实没法干涉。不过我用Adguard Home占用了ipv4和ipv6的53端口，确实获取到了所有的dns请求，不知道ssrp是怎么实现劫持的。

大佬能指点一下学习的方向么？直接看源码肯定不是小白能做到的，就算能粗读源码，也不一定能理清其中的头绪。

**Comment by wsczx** [comment]
挖坟，请求添加ipset选项+1

**Comment by lengfwong** [comment]
> > > 
> > 
> > 
> > 这个ipset 是支持的，我现在就是这样用的，一个gfwlist域名查询指定mosdns通过那个DNS查，同时加入一个ipset，防火墙规则让这个ipset的走代理。相关配置如下，只是luci界面没有，自己配置的gfwlist域名集合。另外第二条ipset例外，机场的域名加入灰名单或者白名单即可。

> 
> 我不确定ssrp和passwall是不是默认就调用了ipset，passwall的ipset名称写在配置文件中，很明确。ssrp启用的时候，有时候有gfwlist这个名称的ipset，有时候没有，防火墙里面也看不到这些ipset的名称。

抱歉现在才看到，试着解释一下，如大佬所言，那些插件一定会该防火墙规则的。你列一下防火墙规则应该可以看的到，所有的数据分流只能通过防火墙完成，比如下面这几天简单的规则（firewall3版本，插件透明代理监听端口1080）：
```
ipset -N gfwlist iphash   ###创建一个名称为gfwlist的ipset。
iptables -t nat -i br-lan -A PREROUTING -p tcp -m set --match-set gfwlist dst -j REDIRECT --to-port 1080  ###目标地址在gfwlist 列表内的数据包都转发到openwrt的1080端口（就是插件的监听端口）
iptables -t nat -A OUTPUT -p tcp -m set --match-set gfwlist dst -j REDIRECT --to-port 1080  ##本机发出的目标地址在gfwlist 列表内的数据包也转发到1080端口
```
原理就是 本机的dns（dnsmasq、mosdns等）查询到需要科学的域名后把ip地址写入gfwlist集合（如所上附脚本），当目标地址在gfwllist内的数据包进入openwrt后，防火墙会把数据包转发到插件的监听端口。

另，openwrt现改用firewall4，默认的防火墙是nftables，这个默认的tables名称是fw4。mosdns5、firewall4部分配置为：
```
mosdns5：
  - tag: gfwlist_sequence
    type: sequence
    args:
      - exec: prefer_ipv4
      - exec: $forward_remote
      - exec: nftset inet,fw4,gfwlist,ipv4_addr,32

firewall4：
set gfwlist {
        type ipv4_addr 
   }

chain gfwlist-redirect {
        type nat hook prerouting priority dstnat; policy accept;
        ip daddr @gfwlist  ip protocol {tcp,udp} redirect to :1080 comment "!fw4: Forward lan  gfwlist  traffic"
    } 

```
