### ISSUE TITLE
初始状态，未更新geosite和geoip，会启动失败。

### ISSUE THREAD

**Issue by 4thanks** [sbwml/luci-app-mosdns#5]
内置配置还是自定义配置都会卡在query_is_local_domain加载那过不去，要手动更新或上传最新geosite和geoip才能启动。
建议和https://github.com/QiuSimons/openwrt-mos一样，在编译时就带最新的geosite和geoip。

**Comment by sbwml** [comment]
readme 有写 依赖这个geodata ，如果你拉取的其它插件库已经包含了这个插件包，你需要删除并替换为下面连接的。
depend：https://github.com/sbwml/v2ray-geodata

**Comment by sbwml** [comment]
并且这个 v2ray-geodata 只要你编译   就是最新日期的数据库，即使你误编译了其它的geodata 库，你依然可以在 luci 中更新数据库，他会自动下载最新的覆盖

**Comment by sbwml** [comment]
如果是在原生openwrt 中这样做是对的。

但是如果你使用 lede 或者 其它的openwrt 源码，它可能源码本身就已经包含了v2ray-geodata（这个是不可用的，因为它缺少mosdns 需要的多个 cn 类别）

无论你使用的是原生openwrt 或者 第三方衍生版本，你都可以通过这种方法来解决这个问题。

1、在你准备好所有源码后（mosdns 不包含在里面），在openwrt 源码目录执行这两个命令
```shell
find ./ | grep Makefile | grep v2ray-geodata | xargs rm -rf
find ./ | grep Makefile | grep mosdns | xargs rm -rf
```

2、最后再拉取 [mosdns](https://github.com/sbwml/luci-app-mosdns) 和 [v2ray-geodata](https://github.com/sbwml/v2ray-geodata) ，配置上 `CONFIG_PACKAGE_luci-app-mosdns=y` 开始编译固件

这样做的目的是在你拉取mosdns 之前，清理掉源码本身自带的 mosdns 包和 v2ray-geodata ，就可以彻底绝决存在多个源码被错误编译的情况
