### ISSUE TITLE
将下载Geo数据库作为可选项

### ISSUE THREAD

**Issue by yubanmeiqin9048** [sbwml/luci-app-mosdns#50]
在路由器上跑mosdns，如果路由器上装有OC一类的插件会自带GEO数据库，对于闪存较小的设备下两份GEO数据库空间是有些不足的

**Comment by sbwml** [comment]
下载？你说数据库更新吗

**Comment by benwwchen** [comment]
对小闪存路由友好的处理方式可以参考OpenClash把二进制文件和数据库都放/tmp，然后直接从内存启动
https://github.com/vernesong/OpenClash/issues/811
希望能支持这种方式
