### ISSUE TITLE
更新 GeoIP & GeoSite 数据库,不能更新出错！！！！！

### ISSUE THREAD

**Issue by gaohanping** [sbwml/luci-app-mosdns#51]
更新 GeoIP & GeoSite 数据库,不能更新出错，总是更新失败！！！！！

**Comment by sbwml** [comment]
更新这个东西需要有一定的网络条件，毕竟没用到国内节点

![1](https://user-images.githubusercontent.com/16485166/221071583-2247a16a-461e-4cb8-a117-4c2bfd81b318.png)


你也可以通过终端命令更新，终端会告诉你你为什么会失败

```shell
/usr/share/mosdns/mosdns.sh geodata
```

![2](https://user-images.githubusercontent.com/16485166/221071827-45ea1c8c-4322-4cf5-9a7b-7efada8bb76d.png)

**Comment by gaohanping** [comment]
> 更新这个东西需要有一定的网络条件，毕竟没用到国内节点
> 
> ![1](https://user-images.githubusercontent.com/16485166/221071583-2247a16a-461e-4cb8-a117-4c2bfd81b318.png)
> 
> 你也可以通过终端命令更新，终端会告诉你你为什么会失败
> 
> ```shell
> /usr/share/mosdns/mosdns.sh geodata
> ```
> 
> ![2](https://user-images.githubusercontent.com/16485166/221071827-45ea1c8c-4322-4cf5-9a7b-7efada8bb76d.png)

感谢回复，我用命令更新，是这个样子


root@OpenWrt:~# /usr/share/mosdns/mosdns.sh geodata
Downloading https://github.com/Loyalsoldier/v2ray-rules-dat/releases/latest/download/geoip.dat
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
100 9438k  100 9438k    0     0  4401k      0  0:00:02  0:00:02 --:--:-- 10.3M
Downloading https://github.com/Loyalsoldier/v2ray-rules-dat/releases/latest/download/geosite.dat
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
100 5029k  100 5029k    0     0  2377k      0  0:00:02  0:00:02 --:--:-- 29.2M
Downloading 
curl: (3) Error

**Comment by sbwml** [comment]
看起来你的网络没有问题，不过你可能需要更新一下 luci-app-mosdns，记得某一次提交中产生一个bug，在未打开ad过滤时，数据库更新错误。这个问题在后来被修复。

**Comment by gaohanping** [comment]
> 看起来你的网络没有问题，不过你可能需要更新一下 luci-app-mosdns，记得某一次提交中产生一个bug，在未打开ad过滤时，数据库更新错误。这个问题在后来被修复。

OK 感谢回复
