### ISSUE TITLE
自定义配置问题

### ISSUE THREAD

**Issue by Kryo123456** [sbwml/luci-app-mosdns#54]
我想让apple和microsoft的域名走远程dns解析，于是在非本地域名那里添加了两个geosite规则，但是查看dns解析发现它们还是走到大陆的dns服务器了，请问这是我写配置出错了么？请大佬帮忙看下，谢谢！

log:
  level: info
  file: "/tmp/mosdns.log"

include: []

data_providers:
  - tag: geoip
    file: "/usr/share/v2ray/geoip.dat"
    auto_reload: true

  - tag: geosite
    file: "/usr/share/v2ray/geosite.dat"
    auto_reload: true

  - tag: whitelist
    file: "/etc/mosdns/rule/whitelist.txt"
    auto_reload: true

  - tag: blocklist
    file: "/etc/mosdns/rule/blocklist.txt"
    auto_reload: true

  - tag: greylist
    file: "/etc/mosdns/rule/greylist.txt"
    auto_reload: true

  - tag: hosts
    file: "/etc/mosdns/rule/hosts.txt"
    auto_reload: true

  - tag: redirect
    file: "/etc/mosdns/rule/redirect.txt"
    auto_reload: true

  - tag: local_ptr
    file: "/etc/mosdns/rule/local-ptr.txt"
    auto_reload: true

  - tag: adlist
    file: "/etc/mosdns/rule/adlist.txt"
    auto_reload: true

plugins:
  - tag: lazy_cache
    type: cache
    args:
      size: 0
      lazy_cache_ttl: 0

  - tag: modify_ttl
    type: ttl
    args:
      minimal_ttl: 0
      maximum_ttl: 0

  - tag: "forward_local"
    type: forward
    args:
      upstream:
        - addr: 127.0.0.1:88

  - tag: "forward_remote"
    type: fast_forward
    args:
      upstream:
        - addr: tls://1.1.1.1
          enable_pipeline: true
        - addr: tls://8.8.8.8
          enable_pipeline: true

  - tag: query_is_whitelist_domain
    type: query_matcher
    args:
      domain:
        - "provider:whitelist"

  - tag: query_is_blocklist_domain
    type: query_matcher
    args:
      domain:
        - "provider:blocklist"

  - tag: query_is_greylist_domain
    type: query_matcher
    args:
      domain:
        - "provider:greylist"

  - tag: query_is_hosts_domain
    type: hosts
    args:
      hosts:
        - "provider:hosts"

  - tag: query_is_redirect_domain
    type: redirect
    args:
      rule:
        - "provider:redirect"

  - tag: query_is_local_domain
    type: query_matcher
    args:
      domain:
        - "provider:geosite:cn"

  - tag: query_is_non_local_domain
    type: query_matcher
    args:
      domain:
        - "provider:geosite:apple"
        - "provider:geosite:microsoft"
        - "provider:geosite:geolocation-!cn"

  - tag: response_has_local_ip
    type: response_matcher
    args:
      ip:
        - "provider:geoip:cn"

  - tag: query_is_ad_domain
    type: query_matcher
    args:
      domain:
        - "provider:adlist"

  - tag: match_local_ptr
    type: query_matcher
    args:
      qtype: [12]
      domain:
        - "provider:local_ptr"

  - tag: match_qtype65
    type: query_matcher
    args:
      qtype: [65]

  - tag: "main_sequence"
    type: "sequence"
    args:
      exec:
        - _misc_optm
        - query_is_hosts_domain
        - query_is_redirect_domain

        - if: query_is_whitelist_domain
          exec:
            - forward_local
            - modify_ttl
            - _return

        - if: "query_is_blocklist_domain || query_is_ad_domain || match_local_ptr || match_qtype65"
          exec:
            - _new_nxdomain_response
            - _return

        - lazy_cache

        - if: query_is_greylist_domain
          exec:
            - forward_remote
            - modify_ttl
            - _return

        - if: query_is_local_domain
          exec:
            - forward_local
            - modify_ttl
            - _return

        - if: query_is_non_local_domain
          exec:
            - _prefer_ipv4
            - forward_remote
            - modify_ttl
            - _return

        - primary:
            - forward_local
            - if: "(! response_has_local_ip) && [_response_valid_answer]"
              exec:
                - _drop_response
          secondary:
            - _prefer_ipv4
            - forward_remote
            - modify_ttl
          fast_fallback: 200

servers:
  - exec: main_sequence
    listeners:
      - protocol: udp
        addr: ":5335"
      - protocol: tcp
        addr: ":5335"

**Comment by sbwml** [comment]
也许这些域名存在于 whitelist 。优先级缘故 whitelist 权重比较高就走本地了

**Comment by Kryo123456** [comment]
> 也许这些域名存在于 whitelist 。优先级缘故 whitelist 权重比较高就走本地了

我whitelist里面的东西都删掉了。我想知道就是我这样写理论上应该没有问题吧。

**Comment by sbwml** [comment]
理论上没问题，我不懂这些东西

**Comment by Kryo123456** [comment]
> 理论上没问题，我不懂这些东西

找到原因了，可能是geosite:cn里面有部分apple和microsoft的域名，我把local和non_local的顺序调了下就可以了，谢谢大佬。

**Comment by coolzhi** [comment]
> > 理论上没问题，我不懂这些东西
> 
> 
> 
> 找到原因了，可能是geosite:cn里面有部分apple和microsoft的域名，我把local和non_local的顺序调了下就可以了，谢谢大佬。


可以分享下你的自定义配置吗？
zhibaba@gmail.com

**Comment by Kryo123456** [comment]
> > > 理论上没问题，我不懂这些东西
> > 
> > 
> > 找到原因了，可能是geosite:cn里面有部分apple和microsoft的域名，我把local和non_local的顺序调了下就可以了，谢谢大佬。
> 
> 可以分享下你的自定义配置吗？ [zhibaba@gmail.com](mailto:zhibaba@gmail.com)

就在上面啊

**Comment by hww-png** [comment]
![image](https://github.com/sbwml/luci-app-mosdns/assets/77440291/d8505761-80d9-41e0-b157-6c29d58327f0)
我这自定义配置mosdns都没法运行
