### ISSUE TITLE
手动点击更新 GeoIP & GeoSite 数据库会更新失败

### ISSUE THREAD

**Issue by umlka** [sbwml/luci-app-mosdns#56]
但是我到浏览器里面却可以打开https://github.com/Loyalsoldier/v2ray-rules-dat/releases/

**Comment by sbwml** [comment]
终端执行更新脚本并附上完整输出

```shell
/usr/share/mosdns/mosdns.sh geodata
```

**Comment by umlka** [comment]
> 终端执行更新脚本并附上完整输出
> 
> ```shell
> /usr/share/mosdns/mosdns.sh geodata
> ```

```
root@OpenWrt:~# /usr/share/mosdns/mosdns.sh geodata
Downloading https://github.com/Loyalsoldier/v2ray-rules-dat/releases/latest/download/geoip.dat
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 9602k  100 9602k    0     0  5692k      0  0:00:01  0:00:01 --:--:-- 30.7M
Downloading https://github.com/Loyalsoldier/v2ray-rules-dat/releases/latest/download/geosite.dat
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 5048k  100 5048k    0     0  3187k      0  0:00:01  0:00:01 --:--:-- 17.1M
Downloading https://raw.githubusercontent.com/privacy-protection-tools/anti-AD/master/anti-ad-domains.txt
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (60) SSL certificate problem: self signed certificate
More details here: https://curl.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
```

**Comment by sbwml** [comment]
你的固件问题，本地CA 不完整。

修复方案：不验证数据库更新地址的 SSL 证书 https://github.com/sbwml/luci-app-mosdns/commit/19ad398c2d5760ea1125e00395710e1e28ea4f82

**Comment by umlka** [comment]
> 你的固件问题，本地CA 不完整。
> 
> 修复方案：不验证数据库更新地址的 SSL 证书 [19ad398](https://github.com/sbwml/luci-app-mosdns/commit/19ad398c2d5760ea1125e00395710e1e28ea4f82)

谢谢大佬

**Comment by umlka** [comment]
> > 你的固件问题，本地CA 不完整。
> > 修复方案：不验证数据库更新地址的 SSL 证书 [19ad398](https://github.com/sbwml/luci-app-mosdns/commit/19ad398c2d5760ea1125e00395710e1e28ea4f82)
> 
> 谢谢大佬

修改了/usr/share/mosdns/mosdns.sh脚本对应的部分依旧更新失败,不过我把梯子关了就能更新,应该是梯子的节点域名出问题了

**Comment by umlka** [comment]
@sbwml 
测试了很久终于找到原因了, 更新数据库的时候除了更新v2ray-data还会更新adlist. adlist的域名raw.githubusercontent.com在路由器本机上面解析的时候被运营商DNS给污染后会返回0.0.0.0, 从而导致报错. 把LAN口自定DNS服务器设置为指向网关就行了
'uci set network.lan.dns='网关地址'

**Comment by sbwml** [comment]
牛逼

**Comment by oojcloo** [comment]
手动点击更新 GeoIP & GeoSite 数据库会更新失败
终端执行更新脚本完整输出
oot@ImmortalWrt:~# /usr/share/mosdns/mosdns.sh geodata
Downloading https://github.com/Loyalsoldier/v2ray-rules-dat/releases/gh-proxy.com/https://github.com/Loyalsoldier/geoip/releases/latest/download/geoip-only-cn-private.dat
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     9    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404

**Comment by sbwml** [comment]
你发出来这个信息   这个GEO数据库地址本来就是错的，失败也是预期结果。

要么这个插件你或者别人改过了，要么就是设置了什么奇奇怪怪的镜像地址

发自我的iPhone

**Comment by SinfulShell13** [comment]
> [@sbwml](https://github.com/sbwml) 测试了很久终于找到原因了, 更新数据库的时候除了更新v2ray-data还会更新adlist. adlist的域名raw.githubusercontent.com在路由器本机上面解析的时候被运营商DNS给污染后会返回0.0.0.0, 从而导致报错. 把LAN口自定DNS服务器设置为指向网关就行了 'uci set network.lan.dns='网关地址'

牛逼，用这个方法解决了
