### ISSUE TITLE
添加远程 DNS 连接复用选项的一点疑问

### ISSUE THREAD

**Issue by duzink** [sbwml/luci-app-mosdns#6]
第一时间更新了4.1.8
但无论如何都没能在界面上找到"添加远程 DNS 连接复用选项",包括重新安装,强制刷新,清理浏览器缓存等等.
谢谢您的辛苦付出!!!

**Comment by sbwml** [comment]
**如果正确更新了luci-app-mosdns，应该会看到多了下图的两个东西。不知道你的更新方式是编译还是下载ipk 安装**

![0BB1E5C5-E3E6-4F05-930B-A66A6E5E8B3E](https://user-images.githubusercontent.com/16485166/179372475-a6e354c6-87a9-4a39-bcb7-b48c789a9249.jpeg)
![3F482E30-C618-4EAD-9AAB-DE74EDCF3F94](https://user-images.githubusercontent.com/16485166/179372476-2251e223-fa2e-4ef9-aa64-430abb01f8dd.jpeg)

**Comment by chenhong3333** [comment]
建议删除旧版后再重装试试，直接更新安装因为版本号不变不会更新成功

**Comment by duzink** [comment]
> **如果正确更新了luci-app-mosdns，应该会看到多了下图的两个东西。不知道你的更新方式是编译还是下载ipk 安装**
> 
> ![1](https://user-images.githubusercontent.com/16485166/179372670-c3f31018-6aad-4358-8bfe-c186287c50af.png) ![2](https://user-images.githubusercontent.com/16485166/179372672-812f067b-f1a6-4d59-b3b9-17c8a18e4e43.png)

实在抱歉,自己没仔细看内置规则预设界面下的内容,您说支出的两个地方,全部都在,是我自己的疏忽,非常抱歉
