### ISSUE TITLE
最新代码更新数据库页签点击检查更新按钮，提示更新失败，请检查网络状态

### ISSUE THREAD

**Issue by yyysuo** [sbwml/luci-app-mosdns#66]
实际上查看/usr/share/v2ray下geosite和geoip文件，都已经下载成功了。

**Comment by sbwml** [comment]
未复现。`/usr/share/mosdns/mosdns.sh geodata` 命令检查

**Comment by yyysuo** [comment]
> /usr/share/mosdns/mosdns.sh geodata

root@Openwrt100:/tmp/tmp# /usr/share/mosdns/mosdns.sh geodata
Downloading https://github.com/Loyalsoldier/v2ray-rules-dat/releases/latest/download/geoip.dat
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 9443k  100 9443k    0     0  6903k      0  0:00:01  0:00:01 --:--:-- 53.9M
Downloading https://github.com/Loyalsoldier/v2ray-rules-dat/releases/latest/download/geosite.dat
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 5067k  100 5067k    0     0  3967k      0  0:00:01  0:00:01 --:--:-- 11.7M
/usr/share/mosdns/mosdns.sh: line 84: service: not found

第84行内容为service mosdns restart

单独执行此命令好像是好的。
root@Openwrt100:/tmp/tmp# service mosdns restart
root@Openwrt100:/tmp/tmp#

**Comment by sbwml** [comment]
你用的到底是不是[openwrt](https://openwrt.org/)

**Comment by yyysuo** [comment]
> 你用的到底是不是[openwrt](https://openwrt.org/)

koolshare v2.37
内核是5.4.108

**Comment by sbwml** [comment]
我不知道你这个是什么，在原生openwrt 上没有问题。

当然，你也可以自己尝试将 https://github.com/sbwml/luci-app-mosdns/blob/v5/luci-app-mosdns/root/usr/share/mosdns/mosdns.sh#L84 改为   `/etc/init.d/mosdns restart`

**Comment by yyysuo** [comment]
> /etc/init.d/mosdns restart

感谢，问题解决 。

**Comment by sbwml** [comment]
你能帮忙做个测试吗

**Comment by yyysuo** [comment]
> 你能帮忙做个测试吗

可以的

**Comment by sbwml** [comment]
终端复制内容

```shell
cat > test.sh <<"EOF"
#!/bin/sh
which service
echo $PATH
EOF
```

```shell
sh test.sh
```

给我看看终端输出的内容

**Comment by yyysuo** [comment]
> ```shell
> sh test.sh
> ```

root@Openwrt100:~# cat > test.sh <<"EOF"
> #!/bin/sh
> which service
> echo $PATH
> EOF
root@Openwrt100:~# sh test.sh
/koolshare/bin:/koolshare/scripts:/usr/bin:/sbin:/bin:/usr/sbin:/mnt/sda3/docker                                                                                                             /bin
root@Openwrt100:~#

**Comment by sbwml** [comment]
```shell
opkg info procd
```
 这个命令呢？

**Comment by yyysuo** [comment]
root@Openwrt100:~# opkg info procd
Package: procd
Version: 2021-03-21-7ee45634-1
Depends: libc, ubusd, ubus, libjson-script20210302, ubox, libubox20210302, libubus20210215, libblobmsg-json20210302, libjson-c5, jshn
Conflicts: procd-selinux
Status: install user installed
Architecture: x86_64
Installed-Time: 1617103570

**Comment by yyysuo** [comment]
大佬你是不是已经更改了mosdns重启服务时Kill的方式？重启服务或者重启openwrt时，最新代码是否会自动保存缓存到磁盘？

**Comment by sbwml** [comment]
你这个我不清楚   openwrt 21 & 22 上没问题 #63

**Comment by yyysuo** [comment]
> 实际上查看/usr/share/v2ray下geosite和geoip文件，都已经下载成功了。

我刚刚做了测试，重启服务肯定是可以正常保存了。我还没测试重启openwrt，我才发现重新载入服务的按钮没了啊。

**Comment by sbwml** [comment]
重载服务仅适用自定义配置下，默认配置下做任何参数更改他都会自动重载

**Comment by yyysuo** [comment]
测试过了，在我的环境下，不管是重启服务还是重启openwrt，都会自动保存缓存到磁盘。
