### ISSUE TITLE
mosdns开启DNS转发后部分网站无法访问

### ISSUE THREAD

**Issue by threerog** [sbwml/luci-app-mosdns#67]
如题
https://www.ldmnq.com/
http://www.lsplayer.com/
关闭DNS转发后就正常

mosdns v5.1.3

**Comment by threerog** [comment]
配置在这里
<img width="650" alt="Snipaste_2023-03-26_21-14-59" src="https://user-images.githubusercontent.com/87128510/227778165-ec21abb2-f4d6-40e8-8f0e-b1cb0e0ada1d.png">

**Comment by yyysuo** [comment]
清空/usr/share/mosdns/sp_low.tdata后重启服务试一下。

**Comment by sbwml** [comment]
关闭广告过滤功能，或尝试切换一个广告规则来源。`ldmnq.com` 域名被 [anti-AD](https://github.com/privacy-protection-tools/anti-AD/) 收录为广告域名，你也可以将那些被 “误拦” 的域名加入到 mosdns 白名单中。
