### ISSUE TITLE
passwall 4.61-3 luci分支版使用mosdns分流解析导致部分域名解析到国内无法连接

### ISSUE THREAD

**Issue by firkerword** [sbwml/luci-app-mosdns#69]
系统版本X86-64   lean源码
passwall版本：https://github.com/xiaorouji/openwrt-passwall/commit/dfe8eaa435a40d7806eb8e46a0909400328fe3b5
![image](https://user-images.githubusercontent.com/61251923/228502322-54bfc411-77bc-42ce-a385-a016a3dc220a.png)
passwall设置如图所示，就添加了节点，上网模式，规则等也都是默认设置
mosdns版本：https://github.com/sbwml/luci-app-mosdns/commit/f9852b8116bd7f6fe939917ccf0cffd21fc65d97 默认设置

问题说明：
日志显示github域名用了本地dns解析无法连接，如githubusercontent.com无法正确解析，也无法更新规则，配置文件和域名列表查看都没问题，而google等域名则解析正常，之后换成https://github.com/QiuSimons/openwrt-mos ，passwall同样的设置，mosnds也是默认设置，解析则正常了

今天编译了两个版本的固件且都是不保留配置刷机都有这个问题，实在找不到问题所在，想了解下是不是bug

**Comment by sbwml** [comment]
测试未复现。

mosdns v5 开始再无debug 日志，你是如何看到github连接转发到本地dns 的？

**Comment by firkerword** [comment]
> 测试未复现。
> 
> mosdns v5 开始再无debug 日志，你是如何看到github连接转发到本地dns 的？

upstream error	{"uqid": 7, "qname": "raw.githubusercontent.com.", "qtype": 1, "qclass": 1, "upstream": "202.102.224.68", "error": "context deadline exceeded"}

不知道问题出在哪  从编译 刷机 设置  各种方法都试了 哎

**Comment by sbwml** [comment]
各种环境试了一遍 ，均未复现

**Comment by umlka** [comment]
> 202.102.224.68
IP地址 数字地址 IP的物理位置
202.102.224.68 3395739716 中国河南郑州 联通
换个上游看看

**Comment by firkerword** [comment]
> 各种环境试了一遍 ，均未复现

那就真的奇怪了    只能先用隔壁的mosdns了😩

**Comment by firkerword** [comment]
> > 202.102.224.68
> > IP地址 数字地址 IP的物理位置
> > 202.102.224.68 3395739716 中国河南郑州 联通
> > 换个上游看看

根据规则逻辑  这个域名应该走国外dns啊   即便是我加入了灰名单依然解析到国内了

**Comment by qingtian110** [comment]
换上游吧年轻人，要么就是你家网络本身烂，要么你节点烂，域名远程解析失败被 fallback 了

**Comment by qingtian110** [comment]
要么直接找个可靠的国内纯净节点做远程上游   pw 直接设置国外列表时  直连DNS，就算网络多烂都不会出现这种情况

**Comment by qingtian110** [comment]
https://doh.apad.pro/dns-query

**Comment by qingtian110** [comment]
直接将它作为远程上游，pw 设置直连  DNS

**Comment by qingtian110** [comment]
sbwml 大佬截图里面自己就有提供直连dns   https://dns.cooluc.com/

**Comment by firkerword** [comment]
> 换上游吧年轻人，要么就是你家网络本身烂，要么你节点烂，域名远程解析失败被 fallback 了

感谢指点 我换隔壁mosdns就好着的啊   用smartdns也好着  所以就纳闷了

**Comment by umlka** [comment]
> > 换上游吧年轻人，要么就是你家网络本身烂，要么你节点烂，域名远程解析失败被 fallback 了
> 
> 那我换隔壁mosdns就好着的啊 用smartdns也好着 所以就纳闷了

试试[自定义配置](https://github.com/umlka/Actions-OpenWrt/blob/main/files/etc/mosdns/config_custom.yaml)

**Comment by firkerword** [comment]
> 试试[自定义配置](https://github.com/umlka/Actions-OpenWrt/blob/main/files/etc/mosdns/config_custom.yaml)

好的感谢 这个可以用

**Comment by firkerword** [comment]
> 各种环境试了一遍 ，均未复现

刚刚根据各位大佬的提点 测试了一下的确是本地dns需要用doh才行  使用本地wan口dns就不行   这是否说明我本地dns有问题  但是用[404大佬的mosnds](https://github.com/QiuSimons/openwrt-mos)  配置默认本地也是wan口的dns 解析就正常  有点不理解了
