### ISSUE TITLE
根据测试, 新加入的DDNS列表功能会造成国内解析服务器(forward_local)对所有域名进行抢答

### ISSUE THREAD

**Issue by umlka** [sbwml/luci-app-mosdns#71]
[这几行代码](https://github.com/sbwml/luci-app-mosdns/blob/v5/luci-app-mosdns/root/usr/share/mosdns/default.yaml#L147-L154)会造成[国内解析(forward_local)](https://github.com/sbwml/luci-app-mosdns/blob/v5/luci-app-mosdns/root/usr/share/mosdns/default.yaml#L89-L94)对所有域名进行抢答

具体测试方法:

1. 一个被污染的国外域名以及对应污染它的DNS服务器IP
2. forward_local那里的上游服务器只填一个上面的污染DNS服务器IP
3. 用被污染的域名进行请求(nslookup之类的), 正常情况下该域名应该会被转发给forward_remote

**Comment by sbwml** [comment]
感谢提出 issues，问题复现
