### ISSUE TITLE
openwrt下，使用自定义配置，开机自启动会启动失败

### ISSUE THREAD

**Issue by kingjoydom** [sbwml/luci-app-mosdns#75]
如题，在使用自定义配置的情况下，开机启动时mosdns会启动失败，需要重新切换到内置配置模式启动后，再切换为自定义配置模式下才可以启动。

**Comment by kingjoydom** [comment]
另外也问一个问题，如果不是用自定义配置，如何修改upstreams对应的IP地址？

**Comment by sbwml** [comment]
内置的 [自定义规则](https://raw.githubusercontent.com/sbwml/luci-app-mosdns/v5/luci-app-mosdns/root/etc/mosdns/config_custom.yaml) 下 ，开机自启测试没有问题

**Comment by sbwml** [comment]
Q2  本地DNS=国内    远程DNS=国外

**Comment by kingjoydom** [comment]
![image](https://user-images.githubusercontent.com/20087455/233241105-e5cdd734-c7fa-4353-b826-6f0cd56a8604.png)
![image](https://user-images.githubusercontent.com/20087455/233241154-c9c24e61-02eb-4780-8a12-3142c2a4d994.png)
大佬，这两个等价的？

**Comment by sbwml** [comment]
是
