### ISSUE TITLE
360V6应该下载哪一个呀？

### ISSUE THREAD

**Issue by xiaoqi2020** [sbwml/luci-app-mosdns#76]
360V6应该下载哪一个呀？

**Comment by sbwml** [comment]
如果是openwrt 固件，它可以帮到你   https://github.com/sbwml/luci-app-mosdns#how-to-install-prebuilt-packages

ps：这个luci 只支持 [openwrt](https://openwrt.org/)

**Comment by xiaoqi2020** [comment]
> 如果是openwrt 固件，它可以帮到你 https://github.com/sbwml/luci-app-mosdns#how-to-install-prebuilt-packages
> 
> ps：这个luci 只支持 [openwrt](https://openwrt.org/)

是刷的openwrt R23.1.20

**Comment by xiaoqi2020** [comment]
> 如果是openwrt 固件，它可以帮到你 https://github.com/sbwml/luci-app-mosdns#how-to-install-prebuilt-packages
> 
> ps：这个luci 只支持 [openwrt](https://openwrt.org/)

![image](https://user-images.githubusercontent.com/50669177/233791420-b5c93541-1c04-481d-a061-7dea268dfeac.png)

**Comment by sbwml** [comment]
能力有限，不支持这个

**Comment by xiaoqi2020** [comment]
> 能力有限，不支持这个

好吧，谢谢
