### ISSUE TITLE
Mosdns 5.1.3在openwrt重启时不会替换DHCP/DNS的监听端口

### ISSUE THREAD

**Issue by kingjoydom** [sbwml/luci-app-mosdns#77]
Mosdns 5.1.3在openwrt重启后，不会自动替换DHCP/DNS这边的DNS转发的端口
比如我的Mosdns监听的是5335，每次重启启动后监听的是7874，手动重启Mosdns才会自动替换为监听5335

**Comment by sbwml** [comment]
首先 MosDNS LuCi 如果勾选 “DNS 转发” 选项，它一定会设置 Dnsmasq DNS 转发端口。

至于你说的它会自动变更为其它端口，只能说明你安装其它某个插件并且该插件也做了DNS 转发的操作。这种情况和 mosdns 无关且没有任何方法阻止其它插件的操作。

**Comment by cpuer** [comment]
停用openclash的本地DNS劫持即可，不过建议你还是留着OC的DNS劫持，把mosdns的DNS转发关掉，前提是你在OC的国内和国外DNS设置为127.0.0.1:5335（udp）。

**Comment by kingjoydom** [comment]
好的，感谢，我去弄一下。
