### ISSUE TITLE
mosdns有些网站查询不到结果

### ISSUE THREAD

**Issue by xkcore123** [sbwml/luci-app-mosdns#78]
notion.site 
这个网站开启mosdns没有回答
关闭后正常
配置如图
![image](https://user-images.githubusercontent.com/70746008/235341151-7ca2dc2f-ba83-426d-b6f4-1189fbdd63c8.png)
![image](https://user-images.githubusercontent.com/70746008/235341168-4224273f-40fc-4349-875b-f21b5b38d568.png)

**Comment by xkcore123** [comment]
这个是开启的时候
![image](https://user-images.githubusercontent.com/70746008/235341242-d329261e-ab2e-483d-8d59-d218512cde77.png)
关闭的时候
![image](https://user-images.githubusercontent.com/70746008/235341277-f16333bb-3b57-4185-8b13-fb93ca3c7eeb.png)

**Comment by sbwml** [comment]
sp_low.tdata 不安全域名数据库 Site 关键词缘故，如果你是自己编译的插件，[最新提交](https://github.com/sbwml/luci-app-mosdns/commit/6452b77097948525f8c8d4c896961751d921ccb3) 已经移除 sp_low.tdata 可以解决这个问题。

或者你可以通过终端命令清空这个文件也可以解决

```shell
true > /usr/share/mosdns/sp_low.tdata
```

然后重启你的 mosdns 进程（关闭&开启）
