### ISSUE TITLE
遇到类似的问题

### ISSUE THREAD

**Issue by ssrubsd** [sbwml/luci-app-mosdns#80]
https://github.com/QiuSimons/openwrt-mos/issues/48

**Comment by sbwml** [comment]
这里提供的 mosdns 只有 dns 解析操作，它不关联任何其它插件的设置。如果你遇到的问题是**所有网站都无法打开**，那才是这个 mosdns 的问题。因为它只进行域名解析，别无其它操作。你提到的问题应该去那个插件寻找答案

**Comment by ssrubsd** [comment]
> 这里提供的 mosdns 只有 dns 解析操作，它不关联任何其它插件的设置。如果你遇到的问题是**所有网站都无法打开**，那才是这个 mosdns 的问题。因为它只进行域名解析，别无其它操作。你提到的问题应该去那个插件寻找答案

但是关闭mosdns插件或者ssrp的dns解析不设置为使用5335端口就不会出现此问题，所以也是启动顺序的原因吗？

**Comment by umlka** [comment]
把梯子节点的域名全部加入到白名单
