### ISSUE TITLE
net.core.rmem_max=4194304的作用是什么，如果本地已配置相同参数会如何呢？

### ISSUE THREAD

**Issue by yyysuo** [sbwml/luci-app-mosdns#82]
本地配置已配置了相同的参数
net.core.rmem_max=536870912
net.core.wmem_max=536870912

我看升级mosdns的时候提示如下：
Upgrading luci-app-mosdns on root from 1.5.3-1 to 1.5.4... net.core.rmem_max = 4194304 net.core.wmem_max = 4194304 Removing obsolete file /usr/share/mosdns/sp_low.tdata. Configuring luci-app-mosdns.

而实际查看/etc/sysctl.conf，配置的内容也并没有发生变化。

**Comment by sbwml** [comment]
作用：https://github.com/quic-go/quic-go/wiki/UDP-Receive-Buffer-Size

这个参数是直接写入到内核。内核默认的缓冲大小只有 200 kb 左右，不管你系统上配置过多少次，只要 ≥ 2048 kb 就可以。

`sysctl -a 2>&1 | grep rmem_max`  可查看当前内核的 buffer size

**Comment by sbwml** [comment]
不过你说你本地已经有配置到  `net.core.rmem_max=536870912` ？你确定这个值不是娱乐搞笑？你应该不是openwrt，至少openwrt 不会这么娱乐

**Comment by yyysuo** [comment]
> sysctl -a 2>&1 | grep rmem_max


root@OpenWrt:~# sysctl -a 2>&1 | grep rmem_max
net.core.rmem_max = 536870912

小白不懂瞎搞，让大佬见笑了。缘起lean大神在openwrt分支上移植了cloudflare的高性能补丁
https://blog.cloudflare.com/when-the-window-is-not-fully-open-your-tcp-stack-is-doing-more-than-you-think/

添加了如下参数：
#cloudflare超大TCP并发补丁优化参数
net.ipv4.tcp_adv_win_scale = -2

在某电报群中有网友分享了相关的配置，就照抄了。这个内存缓冲参数，只要实际运行中不满，不超过系统限制，设置多少应该都没有什么大影响吧？目前openwrt是分了2G内存，没有用光。

目前在用的完整参数如下：
# Defaults are configured in /etc/sysctl.d/* and can be customized in this file
#重启或者执行 modprobe ip_conntrack 和 sysctl -p生效 可清空失效 网上收集
vm.overcommit_memory=1
fs.file-max=1000000
fs.inotify.max_user_instances=8192
net.core.rmem_default=536870912
net.core.rmem_max=536870912
net.core.wmem_default=536870912
net.core.wmem_max=536870912
net.core.netdev_max_backlog=1048576
net.core.somaxconn=1048576
net.core.optmem_max=81920
net.ipv4.tcp_moderate_rcvbuf=1
net.ipv4.tcp_mem=536870912 536870912 536870912
net.ipv4.tcp_max_tw_buckets=1048576
net.ipv4.tcp_keepalive_time=1800
net.ipv4.tcp_keepalive_intvl=30
net.ipv4.tcp_keepalive_probes=3
net.ipv4.tcp_sack=1
net.ipv4.tcp_fack=1
net.ipv4.tcp_timestamps=0
net.ipv4.tcp_window_scaling=1
net.ipv4.tcp_syncookies=1
net.ipv4.tcp_tw_reuse=1
net.ipv4.tcp_fin_timeout=30
net.ipv4.ip_local_port_range=10240 65535
net.ipv4.tcp_fastopen=3
net.ipv4.tcp_no_metrics_save=1
net.ipv4.tcp_max_orphans=32768
net.ipv4.tcp_max_syn_backlog=1048576
net.ipv4.tcp_syn_retries=1
net.core.netdev_budget=20000
#IPV6设置
#net.ipv6.conf.all.disable_ipv6=1
#net.ipv6.conf.default.disable_ipv6=1
#net.ipv6.conf.lo.disable_ipv6=1
net.netfilter.nf_conntrack_max=1048576
net.nf_conntrack_max=1048576
net.netfilter.nf_conntrack_tcp_timeout_fin_wait=30
net.netfilter.nf_conntrack_tcp_timeout_time_wait=30
net.netfilter.nf_conntrack_tcp_timeout_close_wait=15
net.netfilter.nf_conntrack_tcp_timeout_established=300
# Disable TCP slow start on idle connections
net.ipv4.tcp_slow_start_after_idle=0
# If your servers talk UDP, also up these limits
net.ipv4.udp_rmem_min=81920
net.ipv4.udp_wmem_min=81920
net.ipv4.udp_mem=262144 327680 393216
#cloudflare超大TCP并发补丁优化参数
net.ipv4.tcp_adv_win_scale = -2
net.ipv4.tcp_collapse_max_bytes = 6291456
net.ipv4.tcp_notsent_lowat = 131072
net.ipv4.tcp_rmem=8192 262144 536870912
net.ipv4.tcp_wmem=4096 16384 536870912
#某机场场主额外配置
net.ipv4.tcp_mtu_probing=1
net.ipv4.tcp_retries2=8
net.ipv4.route.gc_timeout=100
net.ipv4.tcp_synack_retries=1
