### ISSUE TITLE
请大佬检查下我的配置是否正确，《旁路网关mosdns搭配passwall2》

### ISSUE THREAD

**Issue by GD2021** [sbwml/luci-app-mosdns#84]
![image](https://github.com/sbwml/luci-app-mosdns/assets/81171294/7bc52d43-a5df-4376-85a4-0d05c4b47c23)
![image](https://github.com/sbwml/luci-app-mosdns/assets/81171294/b8d2fcb5-86dc-4e7c-be5b-26081a9f1d7e)
![image](https://github.com/sbwml/luci-app-mosdns/assets/81171294/db209877-8c62-4aec-99e3-d0f170c86c37)
![image](https://github.com/sbwml/luci-app-mosdns/assets/81171294/a36daaf6-fd85-40ac-a860-c8795b0b5ac6)
![image](https://github.com/sbwml/luci-app-mosdns/assets/81171294/615e1aea-b613-49b4-a967-9cd2ff06d7d7)

目前不明白这个api端口有何用
![image](https://github.com/sbwml/luci-app-mosdns/assets/81171294/7b108713-6f8b-4fc9-806b-2de94ea71963)

**Comment by GD2021** [comment]
补充：防火墙wan规则删掉了

**Comment by sbwml** [comment]
API 说明：https://irine-sistiana.gitbook.io/mosdns-wiki/mosdns-v5/api-shuo-ming

至于mosdns的使用，图一  和 图二的操作是正确的，其它的设置是多余的。当你勾选 DNS 转发 选项时，mosdns 已经帮你自动完成 dnsmasq 的设置。禁止ipv6 更是多余了，mosdns 会自动对海外域名优先使用ipv4 地址解析，手动去使用固件的禁用v6 功能意味着你会彻底失去ipv6 的网络使用（即使是国内站）

**Comment by GD2021** [comment]
> API 说明：https://irine-sistiana.gitbook.io/mosdns-wiki/mosdns-v5/api-shuo-ming
> 
> 至于mosdns的使用，图一 和 图二的操作是正确的，其它的设置是多余的。当你勾选 DNS 转发 选项时，mosdns 已经帮你自动完成 dnsmasq 的设置。禁止ipv6 更是多余了，mosdns 会自动对海外域名优先使用ipv4 地址解析，手动去使用固件的禁用v6 功能意味着你会彻底失去ipv6 的网络使用（即使是国内站）

好的，佬，受教了
