### ISSUE TITLE
mosdns fallback规则与dns泄露的问题

### ISSUE THREAD

**Issue by yyysuo** [sbwml/luci-app-mosdns#85]
现在都流行检测dns泄露，只要是真正的dns大陆白名单，一般就不会有泄露。大佬默认生成的配置文件，fallback部分默认是发送到国内dns的。

  - tag: fallback
    type: fallback
    args:
      primary: query_is_local_ip
      secondary: query_is_remote
      threshold: 500
      always_standby: true

改成只发送到国外dns就没有dns泄露的问题了。

  - tag: fallback
    type: fallback
    args:
      primary: query_is_remote
      secondary: query_is_remote
      threshold: 500
      always_standby: true

能否在luci中提供一个选项，使生成的fallback规则默认是发往国外公共dns的？

**Comment by sbwml** [comment]
这样子的话，这个 `fallback` 就没有它的意义了

**Comment by yyysuo** [comment]
> fallback


我理解的fallback等同于surge中的final，看来理解得不太对。改成这样行么？不并发执行，设置一个长的超时机制。

tag: fallback
type: fallback
args:
primary: query_is_remote
secondary: query_is_local_ip
threshold: 2500
always_standby: false
