### ISSUE TITLE
使用内置预设配置文件，dns服务器表单里的“自定义”如何正确添加不在下拉菜单内的节点

### ISSUE THREAD

**Issue by kalagxw** [sbwml/luci-app-mosdns#86]
如题

**Comment by kalagxw** [comment]
![image](https://github.com/sbwml/luci-app-mosdns/assets/3965683/a8fad7fa-b8e7-4701-b686-8da542b0a94f)

**Comment by sbwml** [comment]
不同协议的填写方式（所有协议都支持自定义端口，以 `:5533` 方式指定端口）

UDP: 8.8.8.8
TCP: tcp://8.8.8.8
DoT: tls://8.8.8.8
DoH: https://8.8.8.8/dns-query
