### ISSUE TITLE
mosdns在istoreos（最新版）启动问题

### ISSUE THREAD

**Issue by jesse26wong** [sbwml/luci-app-mosdns#87]
向你反应一个问题：我用的是istoreos(最新0512版）下载了你的mosdns v5版本安装使用，发现一个问题：MOSDNS自定义配置文件(用的是内置预设文件修改），无论怎么去试启动或重载文件都不能正常启动，但一旦我改成用内存文件正常启起动后，手动取消“启动”勾后，再选回自定义的配置，再勾选启动，mosdns又能正常启动。但重启istoreos后，这个问题又会重现，必须人动先切换内置配置正常启动一次后，再切换自定义才能启动。

**Comment by sbwml** [comment]
请勿重复 #88 打开 issues
