### ISSUE TITLE
istoreos安装mosdns V5启动问题

### ISSUE THREAD

**Issue by jesse26wong** [sbwml/luci-app-mosdns#88]
向你反应一个问题：我用的是istoreos(最新0512版）下载了你的mosdns v5版本安装使用，发现一个问题：MOSDNS自定义配置文件(用的是内置预设文件修改），无论怎么去试启动或重载文件都不能正常启动，但一旦我改成用内存文件正常启起动后，手动取消“启动”勾后，再选回自定义的配置，再勾选启动，mosdns又能正常启动。但重启istoreos后，这个问题又会重现，必须人动先切换内置配置正常启动一次后，再切换自定义才能启动。

**Comment by sbwml** [comment]
自定义配置文件是提供给用户完全个性化定制的，不推荐直接拷贝内置预设的配置文件使用，因为内置预设配置是会根据luci 的参数设定在启动前做一些准备操作的。

其次是启动失败的原因检查方法：在自定义配置模式下，勾选 “启用” 选项后（当它处于未运行状态下），打开终端执行 `/usr/bin/mosdns start -c /etc/mosdns/config_custom.yaml`  ，终端会抛出配置异常的地方，并针对这个异常对自定义配置文件进行修改。

**Comment by jesse26wong** [comment]
你的意思是如果是自定义的话，就用你内置的那个自带的custom文件而不是内设配置文件来配置，对吧？好的，我用终端来检查下看下我修改配置文件哪里出问题。如果说这个配置文件有问题的话，为什么我先把它切换成内置的文件启动一下？然后再切换成自定义，它又能启动呢？

**Comment by jesse26wong** [comment]
你的意思是如果是自定义的话，就用你内置的那个自带的custom文件而不是内设配置文件来配置，对吧？好的，我用终端来检查下看下我修改配置文件哪里出问题。如果说这个配置文件有问题的话，为什么我先把它切换成内置的文件启动一下？然后再切换成自定义，它又能启动呢？

**Comment by sbwml** [comment]
原因只有终端去启动才知道

**Comment by jesse26wong** [comment]
这是终端错误反馈：
Error: failed to init plugin #9 adlist, failed to init plugin: failed to load file #0 /var/disable-ads.txt, open /var/disable-ads.txt: no such file or directory

**Comment by sbwml** [comment]
这就是内置配置文件引起的，内置配置的广告过滤功能，在配置文件上把它移除就可以启动了

**Comment by jesse26wong** [comment]
是的，我找到原因了，谢谢
