### ISSUE TITLE
mosdns设置白名单不起作用？

### ISSUE THREAD

**Issue by jesse26wong** [sbwml/luci-app-mosdns#89]
adg(53)上游填127.0.0.1:5335指向mosdns。mosdns设好本地及远程（指向oc地址：127.0.0.1:7874）。在mosdns自定义配置添加了白名单，但将oc关掉，暂停mosdns的远程转发。测试国名网址www.yinfans.me（该域名没有添加在白名单）是否能打开，该域名ip是美国理论是应该打不开的？？但事实是可以打开。同时我又试了www.z2py.com(ip是美国)，该域名没有添加到白名单也没有关键词在白名单，但同样也是可以打开。那问题是这两个网址都是国外域名，为什么我把远程oc关掉停掉转发，mosdns为什么依然可以解析dns？同样道理我，然后又把github原先在白名单里的关健词删掉，在其添加到灰名单，原意是强制mosdns转发远程oc(已关闭状态）解析，理论是打不开网址的，但一轮操作下来，github依然能打开。是不是自定义配置文件不可以使用白名单黑名单？盼解疑！
![yinfans](https://github.com/sbwml/luci-app-mosdns/assets/133888713/ceafa6b5-52a0-451d-a5ab-09bfae1f9805)

**Comment by sbwml** [comment]
`规则列表仅适用于 “内置预设” 配置文件`，如果你使用内置预设配置，那么 luci 提供的所有选项均可用。

[自定义配置](https://github.com/sbwml/luci-app-mosdns/blob/v5/luci-app-mosdns/root/etc/mosdns/config_custom.yaml) 它本身的意义是提供给用户进阶的操作，它的工作效果和用户自己编写的配置有关，具体可参考 [mosdns 官方文档](https://irine-sistiana.gitbook.io/mosdns-wiki/mosdns-v5/ru-he-pei-zhi-mosdns)。

如果你非要让`规则列表` 应用到自定义配置上，可以设置成内置预设配置下启动并参考生成的配置文件：`/etc/mosdns/config.yaml`

**Comment by jesse26wong** [comment]
如果你非要让规则列表 应用到自定义配置上，可以设置成内置预设配置下启动并参考生成的配置文件：/etc/mosdns/config.yaml

是不是我将自定义配置改名成config.yaml替换自身的那份，然后用新config.yaml启动即可？

**Comment by sbwml** [comment]
你可以这样做，如果遇到启动问题可以参考 #88

对于自定义配置，可以前往 mosdns 官方仓库的讨论组，那里会有更多的配置文件上的交流学习和分享

**Comment by wuyuqq** [comment]
> 你可以这样做，如果遇到启动问题可以参考 #88
> 
> 对于自定义配置，可以前往 mosdns 官方仓库的讨论组，那里会有更多的配置文件上的交流学习和分享

我也遇到这个问题，设置5335转发，用LUCI的配置抄下来 只去掉广告AD的相关代码，放到自定义配置能跑起来，白名单设置的域名不起作用 但黑名单有效果能用，配合使用的是passwall，很奇怪....passwall里设置的白名单有效果，黑名单又没效果不起作用......

**Comment by jesse26wong** [comment]
好像不能将内设好的配置文件通过改名为config.yaml就行了，因为就算我先关闭mosdns然后删除了内置config.yaml文件，然后将改好名的新config.yaml拷贝过来，但回到mosdns界面，上面的设置还是之前的设置，并没按改的配置导入。而且一旦开启mossns，config文件又被改回原样。

**Comment by sbwml** [comment]
自定义使用的配置为：`/etc/mosdns/config_custom.yaml`
默认预设使用的配置为：`/etc/mosdns/config.yaml`

这是写死的


我的意思是如果你要把预设配置搬到自定义模式下使用，那就把预设生成的 /etc/mosdns/config.yaml 内容复制粘贴到 自定义配置的编辑框里去

**Comment by sbwml** [comment]
> 我也遇到这个问题，设置5335转发，用LUCI的配置抄下来 只去掉广告AD的相关代码，放到自定义配置能跑起来，白名单设置的域名不起作用 但黑名单有效果能用，配合使用的是passwall，很奇怪....passwall里设置的白名单有效果，黑名单又没效果不起作用......

如果是正确的把luci 的配置抄下来，那么luci 的`规则列表` 肯定是可以用的，但是千万不要混淆一个概念，mosdns 的规则列表和科学插件是不挂钩的，不是说你把域名放在mosdns 的白名单或黑名单，科学插件就会去代理或者不代理那些名单，可以说这两者几乎没有什么联系

**Comment by wuyuqq** [comment]
> > 我也遇到这个问题，设置5335转发，用LUCI的配置抄下来 只去掉广告AD的相关代码，放到自定义配置能跑起来，白名单设置的域名不起作用 但黑名单有效果能用，配合使用的是passwall，很奇怪....passwall里设置的白名单有效果，黑名单又没效果不起作用......
> 
> 如果是正确的把luci 的配置抄下来，那么luci 的`规则列表` 肯定是可以用的，但是千万不要混淆一个概念，mosdns 的规则列表和科学插件是不挂钩的，不是说你把域名放在mosdns 的白名单或黑名单，科学插件就会去代理或者不代理那些名单，可以说这两者几乎没有什么联系

是我理解有误，谢谢大佬解疑！

**Comment by jesse26wong** [comment]
> 那就把预设生成的 /etc/mosdns/co

我本来的自定义配置文件就是这样来的哦。就是用内置配置然后修改参数并增加注析，但好像有对某些不要的册除掉了，难道是因为我删掉了某些段导致配置文件不完整，所以导致黑白黑名单生效不了？

**Comment by sbwml** [comment]
如果是这样，你应该检查你多个dns插件套娃，他们的顺序逻辑是否正确了

首先mosdns 以外的插件我肯定无法帮到你，因为我也没用过。

测试 mosdns 名单是否工作：
1、openwrt 安装 `bind-dig ` 软件包
2、把 mosdns 远程dns 设置成一个错误的地址，比如 6.6.6.6（这个dns不存在，目的为了抛异常）
3、添加 www.baidu.com 到灰名单
4、在openwrt 终端使用mosdns 端口测试dig：`dig @127.0.0.1 -p 5335 www.baidu.com`

如果无法解析出IP，说明灰名单工作了，baidu.com 被强制使用了远程dns（因为远程dns是错误地址，所以得不到结果，另外测试需要关闭或清空mosdns 缓存）

同样的方式，你可以把所有的名单都测试出来。

如果使用dig 测试名单是通过的，那就是你dns套娃的逻辑出问题了。

**Comment by jesse26wong** [comment]
> 如果是这样，你应该检查你多个dns插件套娃，他们的顺序逻辑是否正确了
> 
> 首先mosdns 以外的插件我肯定无法帮到你，因为我也没用过。
> 
> 测试 mosdns 名单是否工作： 1、openwrt 安装 `bind-dig ` 软件包 2、把 mosdns 远程dns 设置成一个错误的地址，比如 6.6.6.6（这个dns不存在，目的为了抛异常） 3、添加 [www.baidu.com](http://www.baidu.com) 到灰名单 4、在openwrt 终端使用mosdns 端口测试dig：`dig @127.0.0.1 -p 5335 www.baidu.com`
> 
> 如果无法解析出IP，说明灰名单工作了，baidu.com 被强制使用了远程dns（因为远程dns是错误地址，所以得不到结果，另外测试需要关闭或清空mosdns 缓存）
> 
> 同样的方式，但可以把所有的名单都测试出来。
> 
> 如果使用dig 测试名单是通过的，那就是你dns套娃的逻辑出问题了。

用你的方法去试dig了，发现添加远程6.6.6.6，灰名单里的domain/关键词全部都能解析得出来。
Mosdns请直接用内置预设，做了简单的设定：
1. 本地DNS: 加 223.5.5.5/DNSPOD DOH
2. 远程：6.6.6.6
3. Bootstrap DNS 服务器： 119.29.29.29
4. 监听端口： 5335
5. DNS 服务器并发数（默认 1）：3
6. 灰规则： 增加 www.baidu.com
7. 其他默认

**Comment by jesse26wong** [comment]
> 如果是这样，你应该检查你多个dns插件套娃，他们的顺序逻辑是否正确了
> 
> 首先mosdns 以外的插件我肯定无法帮到你，因为我也没用过。
> 
> 测试 mosdns 名单是否工作： 1、openwrt 安装 `bind-dig ` 软件包 2、把 mosdns 远程dns 设置成一个错误的地址，比如 6.6.6.6（这个dns不存在，目的为了抛异常） 3、添加 [www.baidu.com](http://www.baidu.com) 到灰名单 4、在openwrt 终端使用mosdns 端口测试dig：`dig @127.0.0.1 -p 5335 www.baidu.com`
> 
> 如果无法解析出IP，说明灰名单工作了，baidu.com 被强制使用了远程dns（因为远程dns是错误地址，所以得不到结果，另外测试需要关闭或清空mosdns 缓存）
> 
> 同样的方式，你可以把所有的名单都测试出来。
> 
> 如果使用dig 测试名单是通过的，那就是你dns套娃的逻辑出问题了。

这个是dig出来的解析结果：

root@iStoreOS:~# dig @127.0.0.1 -p 5335 google.com

; <<>> DiG 9.18.11 <<>> @127.0.0.1 -p 5335 google.com
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 21622
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;google.com.			IN	A

;; ANSWER SECTION:
google.com.		300	IN	A	59.24.3.174

;; Query time: 0 msec
;; SERVER: 127.0.0.1#5335(127.0.0.1) (UDP)
;; WHEN: Sun May 21 07:59:06 CST 2023
;; MSG SIZE  rcvd: 54

root@iStoreOS:~# dig @127.0.0.1 -p 5335 www.baidu.com

; <<>> DiG 9.18.11 <<>> @127.0.0.1 -p 5335 www.baidu.com
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 54862
;; flags: qr rd ra; QUERY: 1, ANSWER: 3, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;www.baidu.com.			IN	A

;; ANSWER SECTION:
www.baidu.com.		300	IN	CNAME	www.a.shifen.com.
www.a.shifen.com.	300	IN	A	39.156.66.18
www.a.shifen.com.	300	IN	A	39.156.66.14

;; Query time: 0 msec
;; SERVER: 127.0.0.1#5335(127.0.0.1) (UDP)
;; WHEN: Sun May 21 07:59:16 CST 2023

**Comment by sbwml** [comment]
虽然我不知道你是怎么操作的，但是名单，在测试中它是工作的

![image](https://github.com/sbwml/luci-app-mosdns/assets/16485166/06597926-1d1c-4c6e-9e42-73d796a363e6)

**Comment by jesse26wong** [comment]
> 虽然我不知道你是怎么操作的，但是名单，在测试中它是工作的
> 
> ![image](https://user-images.githubusercontent.com/16485166/239728982-06597926-1d1c-4c6e-9e42-73d796a363e6.png)

说实话，我也不知道我怎么操作的。istoreos，我已经重装两次了，然后第一时间就先装mosdns不装其他插件，dnsmasq也不设置端口dns转发到mosdns。mosdns，就用内置设置文件就分以下两种情况分程对白灰名单的域名和keyword测试：
1. 增加本地DNS的上游服务器，Bootstrap服务器留空。
2. 关闭本地DNS，添加Bootstrap服务器。

**Comment by jesse26wong** [comment]
这个问题我已经弄了几天，一直没弄好。我用手机拍了视频，上传到阿里云盘。你看一下，方便的话能看一下我这问题不？很想去难分流，但就是弄不好。

https://www.aliyundrive.com/s/fUTtEm3Lr68

Bard ***@***.***> 于2023年5月21日周日 16:22写道：

**Comment by qingtian110** [comment]
我也测试了一下内置预设、和复制预设配置到自定义模式下，我也确认了  白名单、黑名单、灰名单、DDNS 域名、Hosts、重定向 这些名单都是OK的

只有PTR 黑名单没有测试，不太懂 PTR 黑名单的作用和测试方法

**Comment by yukari190** [comment]
请问我换了一台设备如何把原来的配置直接导入过去呢？我复制config.yaml过去，但是只要启动服务这个文件就会被覆盖回初始状态，因为规则比较多，重新配置起来太麻烦了

**Comment by sbwml** [comment]
打包  /etc/mosdns 目录过去可能会有用

从 Windows 版邮件发送

发件人: yukari190
发送时间: 2023年10月19日 0:40
收件人: sbwml/luci-app-mosdns
抄送: Bard; State change
主题: Re: [sbwml/luci-app-mosdns] mosdns设置白名单不起作用？ (Issue #89)

请问我换了一台设备如何把原来的配置直接导入过去呢？我复制config.yaml过去，但是只要启动服务这个文件就会被覆盖回初始状态，因为规则比较多，重新配置起来太麻烦了

**Comment by yukari190** [comment]
> 打包 /etc/mosdns 目录过去可能会有用 从 Windows 版邮件发送 发件人: yukari190 发送时间: 2023年10月19日 0:40 收件人: sbwml/luci-app-mosdns 抄送: Bard; State change 主题: Re: [sbwml/luci-app-mosdns] mosdns设置白名单不起作用？ (Issue #89) 请问我换了一台设备如何把原来的配置直接导入过去呢？我复制config.yaml过去，但是只要启动服务这个文件就会被覆盖回初始状态，因为规则比较多，重新配置起来太麻烦了 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you modified the open/close state.Message ID: ***@***.***>



> 打包 /etc/mosdns 目录过去可能会有用 从 Windows 版邮件发送 发件人: yukari190 发送时间: 2023年10月19日 0:40 收件人: sbwml/luci-app-mosdns 抄送: Bard; State change 主题: Re: [sbwml/luci-app-mosdns] mosdns设置白名单不起作用？ (Issue #89) 请问我换了一台设备如何把原来的配置直接导入过去呢？我复制config.yaml过去，但是只要启动服务这个文件就会被覆盖回初始状态，因为规则比较多，重新配置起来太麻烦了 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you modified the open/close state.Message ID: ***@***.***>

感谢，回头试试

**Comment by WinterBoring** [comment]
> 我也测试了一下内置预设、和复制预设配置到自定义模式下，我也确认了 白名单、黑名单、灰名单、DDNS 域名、Hosts、重定向 这些名单都是OK的
> 
> 只有 PTR 黑名单没有测试，不太懂 PTR 黑名单的作用和测试方法

你好，大哥！向你请教一下。
一。Hosts重写支持自动匹配子域名吗？比如写828282.xyz 12.13.14.15，支持pp.828282.xyz吗？
二。白名单可以直接填域名，不用强制这种格式？如domain:qq.com
我是使用的内置预设模式，规则列表里面填写，十分感谢

**Comment by qingtian110** [comment]
1、支持规则匹配，但是不支持你写的那种 `828282.xyz 12.13.14.15` 它不包含 pp.828282.xyz
2、支持纯域名，效果等同 `full:abc.baidu.com`

**Comment by WinterBoring** [comment]
> 1、支持规则匹配，但是不支持你写的那种 `828282.xyz 12.13.14.15` 它不包含 pp.828282.xyz 2、支持纯域名，效果等同 `full:abc.baidu.com`

谢谢。就是说要host重写只有精确填写域名，只写主域名，二级域名就不能用，只能pp.828282.xyz  12.13.14.15，对吧！
那这种泛域名写法可以吗？*.828282.xyz 12.13.14.15

**Comment by qingtian110** [comment]
不能。`domain:baidu.com 123.123.123.123`  = `你所理解的 *.baidu.com`

**Comment by WinterBoring** [comment]
> domain:baidu.com 123.123.123.123
就是说host重写只能精准匹配域名，也不能这样写：domain:baidu.com 123.123.123.123？只能pp.828282.xyz 12.13.14.15，对吧！
谢谢
