### ISSUE TITLE
 EDNS和DNS缓存这两个是不是有冲突的可能性~

### ISSUE THREAD

**Issue by Pacio** [sbwml/luci-app-mosdns#90]
RTRTRT

**Comment by sbwml** [comment]
mosdns 的 edns 会直接被缓存忽略。https://irine-sistiana.gitbook.io/mosdns-wiki/mosdns-v5/ru-he-pei-zhi-mosdns/ke-zhi-hang-cha-jian#cache

99.9% 的人一般情况下是不需要开启它的，只有当远程DNS 非海外 `公共` DNS 时，且远程DNS为国内无污染节点时才会有启用的需要，这个选项仅对远程 DNS 有效
