### ISSUE TITLE
默认api监听端口与transmussion默认webui端口冲突

### ISSUE THREAD

**Issue by wxg1015** [sbwml/luci-app-mosdns#91]
如题  transmission的默认webui也是9091   ，如果tr向外端口映射时9091 to 9091 ，就会发生路由器网络下用域名无法访问的 情况
总之  端口冲突    建议更换一下端口

**Comment by sbwml** [comment]
这个不是问题，如果有端口冲突在luci上改一下保存应用即可。开源程序非常多，难免遇到端口相同情况

**Comment by qingtian110** [comment]
自己设置一个端口不就好了

**Comment by wxg1015** [comment]
> 这个不是问题，如果有端口冲突在luci上改一下保存应用即可。开源程序非常多，难免遇到端口相同情况

这个我知道   不过鉴于tr用户其实还蛮多的  属于比较出名的占用9091的应用吧   所以感觉默认避开比较好   当然不避开也合情合理  所以只是个建议 😃  我是刚好发现tr打不开页面排查到被占用了 所以提一嘴

**Comment by wxg1015** [comment]
> 自己设置一个端口不就好了

嗯嗯 已经自己改了
