### ISSUE TITLE
旁路由下访问国外网站屏蔽ipv6访问

### ISSUE THREAD

**Issue by 875355038** [sbwml/luci-app-mosdns#95]
旁路由使用passwall+mosdns，当访问一些特定的国外网站时，会被识别出中国的ipv6地址，从而禁止被访问，比如nivod3.tv。
有没有什么办法，访问需要代理的网站时直接禁止ipv6，只让网站检测到代理的ipv4；而访问国内网站则检测到双栈

**Comment by sbwml** [comment]
mosnds 默认就是如此，国外域名优先v4，国内域名则不做设定。nivod3.tv 就拿这个域名测试也是如此，通过 mosdns 默认配置测试，它只返回了 A 记录。至于你为什么会在这个域名上拿到v6 地址我不清楚，因为我不懂，也没有使用过旁路由

**Comment by sbwml** [comment]
不过我相信，如果是在正确使用mosdns 的情况下，它肯定是会对国外域名优先使用 v4 地址。

如果确定不是mosdns问题？工具：https://github.com/natesales/q/releases/tag/v0.11.1

将其下载到openwrt，执行：

```shell
./q nivod3.tv @127.0.0.1:5335
```

测试 mosdns 端口解析，假如只看到 ipv4 地址，说明 mosdns 没有问题，问题在其它的地方

**Comment by 875355038** [comment]
![image](https://github.com/sbwml/luci-app-mosdns/assets/66000685/3d2bed67-a578-4b1e-aba6-0c9e1827a99d)
请问返回这个，这是正常的吗

**Comment by sbwml** [comment]
我不知道怎么说，但是你下载错了架构，q 没有执行起来

**Comment by 875355038** [comment]
![image](https://github.com/sbwml/luci-app-mosdns/assets/66000685/3d619dd0-d4da-4e68-880a-d633024e7ce5)
不好意思，眼花了，谢谢大佬，看来问题不在mos，我再排查其他方面吧

**Comment by ColderCoder** [comment]
> mosnds 默认就是如此，国外域名优先v4，国内域名则不做设定。

为什么要这么做呢？通过把ipv6结果丢弃的方式实现“优先”，是不是太丑陋了？
大陆访问Cloudflare CDN，ipv6远比ipv4稳定

**Comment by sbwml** [comment]
> > mosnds 默认就是如此，国外域名优先v4，国内域名则不做设定。
> 
> 为什么要这么做呢？通过把ipv6结果丢弃的方式实现“优先”，是不是太丑陋了？ 大陆访问Cloudflare CDN，ipv6远比ipv4稳定

虽然我不知道你从哪道听途说打听到 `“优先”=“丢弃”`，但优先v4就绝对是“优先”而不是所谓单纯的“丢弃” http://v6.testmyipv6.com/
![image](https://github.com/sbwml/luci-app-mosdns/assets/16485166/af76a356-6688-49b9-82e5-6cf447f3c724)


但是我肯定知道你根本不懂 mosdns 到底是什么，而你也绝对没有使用 mosdns 的需求。
