### ISSUE TITLE
做个轻量版的ipk

### ISSUE THREAD

**Issue by ThermalEng** [sbwml/luci-app-mosdns#97]
1. geodata 的下载路径可以在界面里面设置，openclash 已经下载了的，就不用再下载，可以重复利用。
2. 界面不用那么多选项，就是每页一个服务器，每个模块一个编辑框，完美的贴合mosdns的设计逻辑。有利于充分发挥mosdns强大的性能，同时又不会沦为单纯的config文件编辑器。

**Comment by sbwml** [comment]
轻量版有现成的了   不需要依赖geodata工作  https://github.com/QiuSimons/openwrt-mos
