### ISSUE TITLE
 Cannot install package luci-app-mosdns

### ISSUE THREAD

**Issue by Mrican** [sbwml/luci-app-mosdns#98]
root@GL-MT3000:~# sh -c "$(curl -ksS https://raw.githubusercontent.com/sbwml/luc
i-app-mosdns/v5/install.sh)"

Checking available space  ...

Checking platform  ...

Update opkg sources ...
Downloading https://fw.gl-inet.cn/releases/v21.02.3/kmod-4.2.1/aarch64_cortex-a5                                                                             3/mediatek/mt7981/Packages.gz
Updated list of available packages in /var/opkg-lists/glinet_core
Downloading https://fw.gl-inet.cn/releases/v21.02.3/packages-4.0/aarch64_cortex-                                                                             a53/glinet/Packages.gz
Updated list of available packages in /var/opkg-lists/glinet_gli_pub
Downloading https://fw.gl-inet.cn/releases/v21.02.3/packages-4.0/aarch64_cortex-                                                                             a53/packages/Packages.gz
Updated list of available packages in /var/opkg-lists/glinet_gli_packages
Updating database.
Database update completed.
Package luci-compat (git-22.046.85744-f08a0f6) installed in root is up to date.
Updating database.
Database update completed.

Download Packages ...

Download https://github.com/sbwml/luci-app-mosdns/releases/download/v5.1.3/mosdn                                                                             s_5.1.3-1_aarch64_cortex-a53.ipk ...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 5598k  100 5598k    0     0  1859k      0  0:00:03  0:00:03 --:--:-- 1943k
Download https://github.com/sbwml/luci-app-mosdns/releases/download/v5.1.3/v2dat                                                                             _2022-12-15-47b8ee51-1_aarch64_cortex-a53.ipk ...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 2487k  100 2487k    0     0   963k      0  0:00:02  0:00:02 --:--:--  964k
Download https://github.com/sbwml/luci-app-mosdns/releases/download/v5.1.3/luci-                                                                             app-mosdns_1.5.4_all.ipk ...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 14010  100 14010    0     0  11835      0  0:00:01  0:00:01 --:--:-- 11852
Download https://github.com/sbwml/luci-app-mosdns/releases/download/v5.1.3/luci-                                                                             i18n-mosdns-zh-cn_git-23.136.50293-39c9008_all.ipk ...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  4035  100  4035    0     0   3613      0  0:00:01  0:00:01 --:--:--  3618
Download https://github.com/sbwml/luci-app-mosdns/releases/download/v5.1.3/v2ray                                                                             -geoip_2023-05-02_all.ipk ...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 34239  100 34239    0     0  26275      0  0:00:01  0:00:01 --:--:-- 26297
Download https://github.com/sbwml/luci-app-mosdns/releases/download/v5.1.3/v2ray                                                                             -geosite_2023-05-02_all.ipk ...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 1256k  100 1256k    0     0   485k      0  0:00:02  0:00:02 --:--:--  486k

Install Packages ...

Installing v2ray-geoip (2023-05-02) to root...
Configuring v2ray-geoip.
Updating database.
Database update completed.
Installing v2ray-geosite (2023-05-02) to root...
Configuring v2ray-geosite.
Updating database.
Database update completed.
Installing v2dat (2022-12-15-47b8ee51-1) to root...
Configuring v2dat.
Updating database.
Database update completed.
Installing mosdns (5.1.3-1) to root...
Configuring mosdns.
Updating database.
Database update completed.
Unknown package 'luci-app-mosdns'.
Collected errors:
 * pkg_hash_check_unresolved: cannot find dependency luci-lua-runtime for luci-a                                                                             pp-mosdns
 * pkg_hash_fetch_best_installation_candidate: Packages for luci-app-mosdns foun                                                                             d, but incompatible with the architectures configured
 * opkg_install_cmd: Cannot install package luci-app-mosdns.
Unknown package 'luci-i18n-mosdns-zh-cn'.
Collected errors:
 * pkg_hash_check_unresolved: cannot find dependency luci-app-mosdns for luci-i1                                                                             8n-mosdns-zh-cn
 * pkg_hash_fetch_best_installation_candidate: Packages for luci-i18n-mosdns-zh-                                                                             cn found, but incompatible with the architectures configured
 * opkg_install_cmd: Cannot install package luci-i18n-mosdns-zh-cn.
Done!

求助

设备新买的，今早一早是成功安装，后来见你更新了，就卸载了重新安装，就装不上

**Comment by sbwml** [comment]
该死的 openwrt 23.05 sdk 惹的祸

**Comment by Mrican** [comment]
期待大佬你修复

**Comment by sbwml** [comment]
你现在应该已经可以安装

**Comment by Mrican** [comment]
搞掂，多谢大佬！

**Comment by Mrican** [comment]
刚更新了什么，有必要同步更新吗？
